### PR TITLE
bunch of spelling fixes

### PR DESCRIPTION
**Pull request by rachelappel**
When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

### CODE REVIEW

**Comment by ohseongkooi** [comment]
(s)

**Comment by guardrex** [comment]
Oh ... sorry ... I was a little bit too late with other suggestions. I'll open a new PR. Those changes to the topic (those sections) were added at some point after I wrote it, and I didn't see them get merged at the time.

**Comment by rachelappel** [comment]
This was just some spelling corrections, no topic changes.

**Comment by guardrex** [comment]
I think the content was handed over from engineering like that. I fixed the other little nits on another PR, so we're good now. Sorry for the bother.

**Comment by rachelappel** [comment]
No worries. I go by the "fix it when you see it" mantra esp for little things like this.

**Pull request merged**
