### PR TITLE
move the policy id

### PR DESCRIPTION
**Pull request by spottedmahn**
https://github.com/MicrosoftDocs/azure-docs/pull/7207

>Being that p is a custom parameter, it fits better in the URL then the query parameters. It is a more "standards compliant" way.

### CODE REVIEW

**Comment by blowdart** [comment]
This would be a question for someone in AAD I'm afraid.

**Comment by spottedmahn** [comment]
Hey @yoelhor - can you comment? Thanks! 🙏

**Comment by scottaddie** [comment]
@parakhj Any other feedback on this PR?

**Comment by parakhj** [comment]
Looks good! #sign-off

**Comment by scottaddie** [comment]
Thank you for your help, @spottedmahn!

**Comment by spottedmahn** [comment]
that's great 👍

and np! 😊

#CommunityDrivenDevelopment 😜

**Pull request merged**
