### PR TITLE
the default model class is `ErrorViewModel`, not `ErrorModel`

### PR DESCRIPTION
**Pull request by johnmwright**
You can see the correct name is already used the the code sample two sentences down

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @johnmwright ... This passage refers to a Razor Pages app. It refers to the template code of the `ErrorModel` ...

```csharp
namespace Sample.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }
        
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}
```

The example below the next paragraph refers to an MVC app.

**Comment by guardrex** [comment]
btw - It wouldn't be terrible to have that code on display in the text. However, the engineers change the content of the `ErrorModel`. They changed it between 2.0 and 2.1. If we were to include the code, it would require versioning in the topic, and it would be fragile going forward. We'd likely miss a change at some point in the future and end up with a stale code example when the engineers make additional changes.

**Comment by guardrex** [comment]
@Rick-Anderson Do u think we should maintain example code for the `ErrorModel`? I'm not really feel'in it based on the template churn. This page model was changed between 2.0 and 2.1 ... and it's [changing again for 2.2 (click to see the 2.2 version)](https://github.com/aspnet/Templating/blob/master/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Pages/Error.cshtml.cs). We might be fighting a losing battle if we go down this road. ⚠️

**Comment by Rick-Anderson** [comment]
See my commit, that should solve the problem.

**Comment by Rick-Anderson** [comment]
@scottaddie  another WIP bug. No WIP in commit title or label.

**Comment by Rick-Anderson** [comment]
No WIP link either
image

**Pull request merged**
