### PR TITLE
Update aspnet-core-module.md

### PR DESCRIPTION
**Pull request by rockydevnet**
Small correction to the documentation, it turns out the request timeout has a validation that requires whole minutes only.

[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/hosting/aspnet-core-module?branch=pr-en-us-4928#configuration-via-webconfig)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@rockydevnet  shouldn't it be hours:minutes:seconds, with hour, minutes, and seconds as whole numbers?

**Comment by Rick-Anderson** [comment]
cc @guardrex

**Comment by guardrex** [comment]
I know it converts the string into a timespan (ticks) and then divides that by 10000 to get milliseconds, which it passes to WinHTTP (prob as `dwConnectTimeout`). However, *YES!* the problem reported by @rockydevnet is easy to repro ... I just had it :boom: on me here.

As for a validation that requires whole minutes only, idk about that ... I checked and didn't see that in the module's ref source.

Even if it is broken and requires a fix in the ANCM repo, we probably need to say something here until a patch is issued.

**Comment by shirhatti** [comment]
Good catch folks. @pan-wang @jkotalik  Can you confirm?

**Comment by jkotalik** [comment]
From what I can tell, it looks like the requestTimeout is being rounded to the nearest minute. Ex: 2:01 would turn into 2:00. This is a quick fix; I'll make an issue for now and fix after the refactor is in.

**Comment by pan-wang** [comment]
This is by design. the schema definition for requestTimeout is timespan and the validation is (0,1296000,60) which means the step is 60 seconds. if we really want to change it, we need to change the schema file.

**Comment by scottaddie** [comment]
@jkotalik Can you please link your issue to this PR?

**Comment by jkotalik** [comment]
https://github.com/aspnet/AspNetCoreModule/issues/270
@scottaddie I was incorrect in my check above. It seems that this validation is done by the schema rather than in code. We would need to update the aspnetcore_schema, which is a more involved process.

**Comment by scottaddie** [comment]
@jkotalik In the meantime, should the proposed text change say something like "The requestTimeout value is rounded to the nearest minute"? When you say "rounded", is it using something like `Math.Round`, `Math.Floor`, or `Math.Ceiling`?

**Comment by jkotalik** [comment]
@scottaddie I was incorrect in my analysis before. Add "The requestTimeout value must be specified in whole minutes, else it will default to 2 minutes." 

I was originally verifying with values just above 2 minutes, so I thought it rounded down to 2 minutes, not that the default is 2 minutes.

**Comment by scottaddie** [comment]
@rockydevnet Thank you for your efforts and for bringing this issue to our attention. Also, congratulations on your 1st contribution to the ASP.NET Core docs.

**Pull request merged**
