### PR TITLE
Bug 1088971

### PR DESCRIPTION
**Pull request by v-savila**
update link on aspnet hub

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@v-savila  can you sign the CLA?

**Comment by Rick-Anderson** [comment]
@v-savila  can you give me some background on this change?

**Comment by v-savila** [comment]
@Rick-Anderson APEX production was asked to get this page, https://review.docs.microsoft.com/en-us/prod-test/hubs/aspnet/index?branch=master, pushed live. The update to this page was updating the link to API Reference to https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.0. We normally don't push a page live unless the client request it, is this something you can push live since our production team usually merge to master?

**Comment by Rick-Anderson** [comment]
@v-savila  sign the CLA and then I can merge & push live.

**Comment by Rick-Anderson** [comment]
@v-savila  I asked to the API doc link to be updated. Why are there so many other changes? I didn't realize this was in our repro when I asked to get the link updated.

**Comment by v-savila** [comment]
@Rick-Anderson the only update to that page was the link for API Reference. I thought in order to push this page live, I need to fork/clone the aspnet/docs repo and update the aspnet/index.md. If that is the wrong process, please revert my change. BTW - I've signed the CLA. Moving forward, if Kim request for the page to be pushed live, do I contact you to push live?

**Comment by Rick-Anderson** [comment]
I can make the change. Check the [files changed link](https://github.com/aspnet/Docs/pull/4457/files) - there are alot of changes. 
Also check the CLA, it shows it's not signed.
For/clone and PR is usually the right approach. For a simple change like this you can just edit the file in the browser and create a PR.
Closing now, I'll make the change and mention you for review.

**Comment by v-savila** [comment]
@Rick-Anderson sorry, it's now signed. I've copied/paste the content from DocsProd (/hub/aspnet/index.md) to the aspnet repo (I think that file was a redirect) so you can revert my changes if needed and for simple changes like this next time, I'll edit directly in the browser and create a PR.

**Comment by Rick-Anderson** [comment]
@v-savila  that's not the right file to make this change. Look at the original file, it's a redirect that goes to another redirect. I can't find https://docs.microsoft.com/en-us/aspnet/#pivot=core in our repo.

**Pull request closed without merging**
