### PR TITLE
Added Description for AdditionalFields Property of Remote Attribute

### LINKED ISSUE #4754: Describe AdditionalFields Property of RemoteAttribute in Model Validation Topic
The `[Remote]` validation attribute has an `AdditionalFields` property that, while kind of self-explanatory, has some quirks that could use more explanation, such as how to specify multiple additional fields.

I plan to provide a PR for this issue, but its getting late so I won't be able to turn that around as quick as I did for issues #4750 and #4752 😛.

## Suggested Reviewers:
@rachelappel 
@Rick-Anderson 
@isaac2004 
@guardrex 
@v-anpasi

### PR DESCRIPTION
**Pull request by Rabadash8820**
Fixes #4754

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Rabadash8820  nice work. I made some slight changes:

* Removed future tense. We avoid future tense.
* Shortened long sentence. My rewrite isn't great but we need to keep sentences short. The machine language translates can't do very well on long sentences.

**Comment by Rabadash8820** [comment]
@Rick-Anderson Any reason for the rapid closing/re-opening earlier?

**Comment by Rabadash8820** [comment]
Also, out of curiosity, is there an error with the syntax highlighting in the published page?  All of the controller action method code in the Remote validation section is just white text, but the model properties still look correct.

**Comment by Rick-Anderson** [comment]
The doc build engine was not running. Sometimes closing/opening fixes that. Where exactly is highlighting missing?

**Comment by Rabadash8820** [comment]
Highlighting is missing on the VerifyEmail and VerifyName snippets in the
Remote Validation section.

**Comment by Rick-Anderson** [comment]
What's the offending markup?

**Comment by Rabadash8820** [comment]
@Rick-Anderson I think this new PR (#4781) will fix it.

**Pull request merged**
