### PR TITLE
Wrong highlight lines on sample9.cshtml

### PR DESCRIPTION
**Pull request by a-iafrate**

### CODE REVIEW

**Comment by GuardRex** [comment]
@Rick-Anderson @tdykstra I confirmed that the range change here is correct.

**Comment by Rick-Anderson** [comment]
@GuardRex  I can't find any of the text surrounding that change.

**Comment by GuardRex** [comment]
I believe its in the `aspnet` ... old skool :grin: docs.

**Comment by Rick-Anderson** [comment]
That explains it.

**Comment by Rick-Anderson** [comment]
@a-iafrate  Thanks!

**Comment by GuardRex** [comment]
@Rick-Anderson ... Your duties have expanded, Sir! ...... just when you thought you didn't have enough on your plate, right? :smile:

**Pull request merged**
