### PR TITLE
Typos in Conceptual Overview

### LINKED ISSUE #187: Typos in Conceptual Overview
*conceptual-overview/aspnet.rst* - "The built-it configuration providers" should be "The built-in configuration providers"

*conceptual-overview/dnx.rst* - "It provide a host process" should be "It provides a host process"

I've created a PR with these fixes. Apologies for combining multiple issues into one, but they are such small changes I thought it prudent.

### PR DESCRIPTION
**Pull request by richardszalay**
Fixes #187

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@richardszalay__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@richardszalay__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by danroth27** [comment]
@richardszalay Looks like you caught us just as we were switching CLAs. Sorry about that! Could you please sign the new one so we can pull your edits in? Thanks!

**Comment by richardszalay** [comment]
@danroth27 Ha, just my luck! I've sorted the CLA and rebased against HEAD.

**Pull request merged**
