### PR TITLE
Fixed view folder Todo to match controller name

### PR DESCRIPTION
**Pull request by nikibobi**
The controller name is **ToDo**Controller and the view was in Views/**Todo**/Index.cshtml
I just renamed the folder with capital D and it is now properly displaied

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Thanks but we generally don't make changes that could break the build and don't add much value.

**Comment by nikibobi** [comment]
But currently the sample does not work. If I start the sample and go to /api/todo I get 404. Thats because controller's name does not match View folder's name. And my second commit passes the build!

**Comment by Rick-Anderson** [comment]
You must be using OSX or Linix.

**Comment by nikibobi** [comment]
Yes I'm using Linux and probably there is no problem on Windows because the filesystem isn't case-sensitive

**Pull request merged**
