### PR TITLE
Response Caching topic enhancements

### LINKED ISSUE #1679: performance/caching/response  "Response Caching"
- [x] Update ResponseCaching docs  #1969 
- [x] graphic needs to be updated to include the caching done by the middleware on the server
- [ ] Add fiddler image of cache header
- [ ] See [this SO thread](http://stackoverflow.com/questions/40369112) When updating doc, use fiddler to show how it works.
- [ ] UE Edit
- [ ] line numbers off
- [ ] DISQUS 
- [x] Update to RTM
- [ ] Document cache tag helper in response caching doc  #1948 
- [ ] Add response caching middleware content to the response caching doc  #1947 
- [ ] #1969  update to reflect the addition of the VaryByQueryKey property that was added in https://github.com/aspnet/Mvc/pull/5383 and the addition of the response caching middleware on the server.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #1679

Notes:
* Also patches up the file naming and UIDs of tag helper topics. The file names should be lowercase with a dash for spaces. The UIDs should be the same.
* The term "Response Caching Middleware" is a proper noun here, so it should be capitalized everywhere.
* Both the middleware and response caching topics need a blurb that demystifies why the middleware isn't a completely server-controlled cache. These comments should also talk about other caching features available to devs that are completely developer-controlled (i.e., irrespective of the `Cache-Control` header sent by the client).
* For the response caching topic, the updates here largely target the introduction, where I felt it didn't offer enough detail on the general concepts and definitions pertaining to response caching. For example, the directives were only explained by linking to the spec. I think we can say (quickly, generally) what these directives mean (and link them to the spec). @JunTaoLuo, consider this just a suggestion ... a show-'n-tell ... for what the intro could look like. If you want me to revert any of this, just say the word.
* I think the factors specifying HTTP caching (under the spec) should be clearly delineated from other ASP.NET Core technologies pertaining to caching, so I split out *Other caching technology in ASP.NET Core* (listing and linking them) from *HTTP-based caching*.
* Guidelines adherence, present tense, 🌹 table beautification 💐, and contractions updates as usual (but I don't care for "mustn't" over "must not," so I use "must not" in the text).

cc/ @JunTaoLuo

### CODE REVIEW

**Comment by guardrex** [comment]
Stand-by ... I'll fix these conflicts up.

**Comment by scottaddie** [comment]
@JunTaoLuo Please review.

**Comment by guardrex** [comment]
Thanks @JunTaoLuo. @scottaddie one thing bug'in me ... IIRC sentences that immediately precede tables might not be allowed to end in a colon. I can't check the style manual. If you know or if you can check and find out that's the case, I'll make a quick change to three sentences here that will permit me to drop their terminal colons.

**Comment by guardrex** [comment]
@scottaddie Stand-by a sec, too, on the file name changes. I need to get the redirects in place. I'll do that now.

**Comment by scottaddie** [comment]
@guardrex You are correct. Here's the rule:

> If there’s text that introduces the table, it should be a complete sentence and end with a period, not a colon.

**Comment by guardrex** [comment]
Ah ... good ... My memory hasn't totally crapped out yet. Lol

I'll get a commit in as soon as I get back from the :muscle: gym.

**Pull request merged**
