### PR TITLE
Update Startup.cs in Formatting

### PR DESCRIPTION
**Pull request by omarmaher100**
Make default format xml

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@ardalis  please review

**Comment by ardalis** [comment]
The new code is just comments. Is it meant to just be FYI for readers or should the line to add the filter be I uncommented?

**Comment by omarmaher100** [comment]
If i want to make xml global format i should make this lines uncommitted to be more easy for the readers

**Comment by Rick-Anderson** [comment]
@omarmaher100  Thanks!

**Comment by omarmaher100** [comment]
UR Welcome @Rick-Anderson  :)

**Pull request merged**
