### PR TITLE
Added database check.

### PR DESCRIPTION
**Pull request by Aaron-KSOC**
In the most up to date version of .Net Core running the code as it was constantly tried to recreate the database which errored it out.

I would have simply left this as a comment on the page but commenting is apparently being overhauled.  I've never done a pull request on GitHub so if I've done something bad here please let me know.

### CODE REVIEW

**Comment by guardrex** [comment]
Would be nice tho to combine the two checks. There's already one check in `Initialize` ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/SeedData.cs#L20

**Comment by Aaron-KSOC** [comment]
That's true but unfortunately it was passing that check and then failing when it tried to recreate the database anyway.  I'm not sure why...

**Comment by Rick-Anderson** [comment]
@bricelam  per [Appling migrations in production](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations#appling-migrations-in-production)

We recommend production apps should not call Database.Migrate at application startup. ... (more on the topic)

But we've found adding it to our sample lowers friction of customers running the sample app.

Having said that, is the the pattern we should follow?

**Comment by bricelam** [comment]
I'll defer to @ajcvickers and @divega

**Comment by Rick-Anderson** [comment]
per [Appling migrations in production](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations#appling-migrations-in-production)

We recommend production apps should not call `Database.Migrate` at application startup. ... (more on the topic)

But we've found adding `Migrate`  to our sample lowers friction of customers running the sample app.

 @ajcvickers or @divega can you check this 2 line change?

**Comment by ajcvickers** [comment]
@Rick-Anderson There should never be a need for an exists check before calling Migrate, unless the database was not created using Migrations, but in that case Migrate should not be there at all.

**Comment by bricelam** [comment]
Yeah, I don't think it helps anything. The original description is interesting--that certainly shouldn't happen.

**Pull request closed without merging**
