### PR TITLE
Updating helpfulness to use new api

### PR DESCRIPTION
**Pull request by mscommunities**
Using new api for helpfulness

### CODE REVIEW

**Comment by danroth27** [comment]
@shirhatti Please verify what this looks like on readthedocs.com.

**Comment by shirhatti** [comment]
image

**Comment by shirhatti** [comment]
Based on our email thread I combined the changes in #874 and #875 and the result renders fine on Desktop/Tablet browsers. However it is broken on mobile. 

image

**Comment by shirhatti** [comment]
Closing for now. Re-open the PR when ready for review

**Pull request closed without merging**
