### PR TITLE
Rename ASP.NET 5 to ASP.NET Core and other general cleanups

### PR DESCRIPTION
**Pull request by danroth27**
ASP.NET 5 -> ASP.NET Core
MVC 6 -> ASP.NET Core MVC
MVC 5 -> ASP.NET MVC
ASP.NET Identity -> ASP.NET Core Identity
Entity Framework 7 -> Entity Framework Core
Core CLR, CoreCLR -> .NET Core
Visual Studio 2015 -> Visual Studio
Remove product source GitHub links
Cleanup sample code GitHub links and standardize text
Remove WebSocketMiddleware content
``project.json`` -> *project.json*
Remove explicit https://docs.asp.net links
Use contents directive
Move author links to authors.txt
Clean up whitespace

### CODE REVIEW

**Comment by danroth27** [comment]
@shirhatti @Rick-Anderson @rachelappel @ardalis Please review.

**Comment by danroth27** [comment]
Stuff not in scope for this PR:
- Updated Getting Started content (blank for now)
- Updated API ref
- Update package IDs and API ref links
- Update articles for RC2

**Comment by shirhatti** [comment]
https://github.com/aspnet/Docs/blame/master/aspnet/tutorials/your-first-aspnet-application.rst#L91
.NET Core 5?

**Comment by shirhatti** [comment]
:shipit:

**Pull request merged**
