### PR TITLE
Adding info for the correct EF package

### LINKED ISSUE #7866: Errors at the "Create the database context" step
I get a bunch of errors at that step, they are all about EF.
```
The type or namespace name 'DbContext' could not be found (are you missing a using directive or an assembly reference?)
```
Did I miss a step to add a specific EF nuget package? If so, which one? (I dont know because I dont use EF)

I also get this warning in the output window....  
warning NU1604: Project dependency Microsoft.AspNetCore.App does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.  (I dont use package ref either)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by StingyJack**
Fixes #7866

I'm sure better text can be crafted so have at it =D.

### CODE REVIEW

**Comment by guardrex** [comment]
A few touch-ups:

* Link the API
* Move it into the 2.1 versioned content, since the `All` package (2.0) has the package.

**Comment by scottaddie** [comment]
There's no need to install `Microsoft.EntityFrameworkCore`. The `Microsoft.AspNetCore.App` metapackage pulls it in for you.

**Comment by guardrex** [comment]
I see it now. I thought that was one of the ones that was factored out.

**Comment by StingyJack** [comment]
Is that some kind of "fake" package?

**Comment by scottaddie** [comment]
@StingyJack The `Microsoft.AspNetCore.App` package is a monolithic package that contains everything needed to use ASP.NET Core and Entity Framework Core. Read more about it here: https://docs.microsoft.com/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1.

**Comment by scottaddie** [comment]
Closing, as we know for sure that the `Microsoft.EntityFrameworkCore` package shouldn't be added directly.

**Pull request closed without merging**
