### PR TITLE
Add wwwroot assets to the ResponseFormattingSample

### PR DESCRIPTION
**Pull request by guardrex**
Add-on PR due to the unexpected presence of *wwwroot* in the *.gitignore* file.

### CODE REVIEW

**Comment by scottaddie** [comment]
@madskristensen @bowdenk7 Does VS 2017 15.3 still read the *_references.js* file? I thought this was no longer needed.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie Forgive me if you already know this, but I wanted to get a little more info for myself. I chatted with [@]davkean on the presence of ...

```xml
<ItemGroup>
  <Folder Include="wwwroot\" />
</ItemGroup>
```
... in the templates to determine where/when it would be required in a sample. He confirmed it *isn't* needed when the *wwwroot* folder has content. It's only present to get an empty *wwwroot* folder into the source tree that MSBuild uses. Since (probably) all of the web app samples have a *wwwroot* folder with *something* inside of it, they're good and samples don't need the Folder-include in their project files.

cc/@dasMulli

**Comment by bowdenk7** [comment]
@scottaddie you are correct, `_references.js` is no longer consumed.

**Comment by guardrex** [comment]
I'll remove it now. Stand-by. Thanks @bowdenk7.

**Pull request merged**
