### PR TITLE
Key Vault Config Provider topic and sample updates

### LINKED ISSUE #7380: Azure KeyVault configuration provider for dotnet core: include MSI piece
It looks like version `2.1.1` of `Microsoft.Extensions.Configuration.AzureKeyVault` includes the awesome hidden gem that has Managed Service Identity support. It reduces the overhead of managing secrets/certificates as long as you're hosting in Azure with integrated Active Directory.

```
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((context, config) =>
                {
                    var builtConfig = config.Build();
                    var keyVaultConfigBuilder = new ConfigurationBuilder();
                    keyVaultConfigBuilder.AddAzureKeyVault(builtConfig["KeyVaultUrl"]);
                    var keyVaultConfig = keyVaultConfigBuilder.Build();
                    config.AddConfiguration(keyVaultConfig);
                })
                .Build();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #7932: Access Denied
I've been banging my head on this all day. 

Does this only work if the application is hosted on Azure? Is there something else that needs to happen in order to authenticate from an on prem server to Azure Key Vault - perhaps through Azure AD?

I have the VaultName, ClientId, and ClientSecret. The app is registered in Azure AD and I just flat out get an Access Denied every time I try and run this code. I feel like I'm missing something in this documentation somewhere.

I'm running on .net core 2.1.300

@Rick-Anderson 	edit: 3.9 K PV
Comment Hub: I like the content, but clear cut example of how to programatically access a simple secret (most simple use case) is obscured.
Content-Accuracy 12/19/2018  It is too abstract. The reader is viewing this page in order to add support for keyvault access to an application. This document does not focus on the practical steps required to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #10216: Enhance the topic and convert the 2.x samples to use Razor Pages apps.
Moved from #6821
Enhance the topic and convert the 2.x samples to use Razor Pages apps.
See: #7908
See: #7932

443 PV/month so low priority.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #7380 
Fixes #7932 
Fixes #10216 

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&branch=pr-en-us-10669)

@Rick-Anderson I guess we should wait on convo with AKV engineering (get the Azure CLI/Cloud Shell to register the app for the vault), or do you want to proceed with that section using the Azure portal to perform that step? Except for that bit in the *Use Application ID and Client Secret* section, this is ready for a look.

* Overhaul/update of the topic.
* Add MSI, including to the sample.
* Sample app to 2.2.
* Reduce samples from two to one and use a pre-proc directive to switch between AppID/Password and MSI approaches.
* Keep the non-RP app after all. It's simple and works well for this demo.
* Use the Secret Manager/User Secrets for dev and AKV for production and make the sample show the difference.
* Drop PS for Azure CLI/Cloud Shell instructions.
* The words "configuration provider" are a proper noun when referring directly to the "Azure Key Vault Configuration Provider," so that's now capitalized where the specific technology name is used.
* For the *key name prefix* bit, let's just have that in-text and not part of the sample. It's fairly straightforward to explain, the sample does enough, and I wanted to reduce this from two samples down to one.

### CODE REVIEW

**Comment by scottaddie** [comment]
@guardrex Please have Prashanth Yerramilli (the Key Vault PM) review the changes.

**Comment by guardrex** [comment]
Thanks @scottaddie.

@prashanthyv ... can we chat here over offine (email) WRT an AKV doc issue here?

**Comment by prashanthyv** [comment]
Sure


________________________________

**Comment by guardrex** [comment]
@prashanthyv -- What's best for you email (llatham - aquent.com) or here on the issue? Here on the issue, see my remark above :point_up:. I hit a roadblock getting the Azure CLI/Cloud Shell to mirror an action that I can take in the portal to give an external app access to AKV.

**Comment by Rick-Anderson** [comment]
@prashanthyv moving to #10790

**Pull request merged**
