### PR TITLE
Beef up log message template language in logging.md

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #4093 
Addresses https://github.com/aspnet/Logging/issues/694

The topic already addressed the main misunderstanding that log message text is really a log message *template* with some particular requirements for the sequence of parameters.

What I do here is beef it up a hair 🐄🔔 by referencing the string passed as a "template" in most places. I call out that it can be a string but go with "template" elsewhere in the section.

cc/ @davidfowl @pakrym

### CODE REVIEW

**Comment by scottaddie** [comment]
@davidfowl Please review.

**Comment by anurse** [comment]
I like it. Could we be even more forceful somewhere and state clearly that this is **not** a format string and that placeholders should be named, not numbered? Also, @pakrym built some Roslyn analyzers (https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.Analyzers) for exactly this, but I'm not sure how/when they're going to ship (ping @davidfowl @Eilon)

**Comment by guardrex** [comment]
@anurse I made it say exactly that under the section heading. It starts ...

> Each time you write a log message, you provide a message template. The message template can be a string or it can contain named placeholders into which argument values are placed. The template isn't a format string, and placeholders should be named, not numbered.

Next, it shows the example with two templates, each with an `{ID}` placeholder.

**Comment by anurse** [comment]
Nice, that's pretty clear. Thanks!

**Pull request merged**
