### PR TITLE
removed self-reference in a section

### PR DESCRIPTION
**Pull request by tugberkugurlu**
It seems like it's referring to its own section.

### CODE REVIEW

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
You missed the other self reference :)

So the first "key lifetime section" link should go to the data-protection-implementation-key-management-expiration reference (in key-management.rst)

The second "subkey derivation section" should go to the data-protection-implementation-subkey-derivation-aad reference (in subkeyderivation.rst).

Kevin do you want to update your PR (or would you rather I just do a new one?)

**Comment by blowdart** [comment]
Grr. Not Kevin. Jetlag. You're all mergeing into one mega-contributer :D

**Comment by ardalis** [comment]
@tugberkugurlu Can you update the PR with @blowdart 's above feedback (or reply to his comment)?

**Comment by tugberkugurlu** [comment]
@blowdart Thx! Yeah, you can go ahead and do it. Feel free to close the PR if it will be irrelevant after that point.

**Comment by blowdart** [comment]
@ardalis do you want to address it, or shall I pick it up later this week?

**Comment by ardalis** [comment]
@blowdart all yours; I haven't even looked at it, just trying to keep the PRs flowing. Thanks.

**Comment by blowdart** [comment]
Closing, addressed in 2d8067aeae205cad5d0b744d35d4a08bc7e51a62

**Pull request closed without merging**
