### PR TITLE
Update TodoController.cs

### PR DESCRIPTION
**Pull request by avangeline**
Parameter of _context.TodoItems.Update should be "todo" instead of "item"

When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

* Suggest reviewers if you know who should review the PR, using the GitHub **Reviewers** UI.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  please review. We should review all the EF code and see if we can simplify and remove unnecessary code ( like checking Id = item.id).

**Comment by Rick-Anderson** [comment]
@avangeline  Thanks!

**Comment by Rick-Anderson** [comment]
@tdykstra  can we push to live again today? I'd like to get this bug fix pushed.

**Comment by tdykstra** [comment]
Done

**Pull request merged**
