### PR TITLE
Scopes are created by calling BeginScope

### PR DESCRIPTION
**Pull request by cesarbs**
Also specifying the method is in the `ILogger` interface.

cc @danroth27 @BrennanConroy

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Looks good. Do we need ship it from @BrennanConroy  ?

**Comment by BrennanConroy** [comment]
Should it be `BeginScope<TState>`?

**Comment by cesarbs** [comment]
@BrennanConroy We're just pointing out the method name, I think including the generic parameter would be just noise here.

**Comment by BrennanConroy** [comment]
Fine, so why add ILogger?

**Comment by cesarbs** [comment]
Because `BeginScope` belongs somewhere.

**Comment by cesarbs** [comment]
I'll add `<TState>` so this is settled.

**Comment by cesarbs** [comment]
Rebased & updated.

**Comment by cesarbs** [comment]
Ping.

**Comment by BrennanConroy** [comment]
:sheep: :it:

**Comment by cesarbs** [comment]
@Rick-Anderson Will you merge or can I push it myself?

**Pull request merged**
