### PR TITLE
Updates TaskCache to Task

### PR DESCRIPTION
**Pull request by motowilliams**
Since [TaskCache](https://github.com/aspnet/Common/issues/238) was removed this updates the sample to use `Task.CompletedTask` instead

Source page is [Custom Model Binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding)

### CODE REVIEW

**Comment by scottaddie** [comment]
@motowilliams Thank you for your contribution! This change is only valid for ASP.NET Core 2.x apps. Would you mind creating an additional sample app for 2.0? I can then take care of adding the necessary versioning tabs to the doc.

**Comment by Rick-Anderson** [comment]
@scottaddie  or we could update the code for 2.x and not keep the 1.x code.

**Comment by Rick-Anderson** [comment]
@danroth27  I propose we update this topic for 2.x and drop 1.x support. If you want 1.x support we can attach a PDF of the 1.1 version

**Comment by danroth27** [comment]
I think `TaskCache` only existed because `Task.CompletedTask` wasn't available in .NET Standard 1.6. I think it was always available in .NET Core. This is a .NET Core app, not a .NET Standard class library, so I think we can take this change as is.

**Comment by scottaddie** [comment]
@motowilliams Sorry for the delay on this one. We really appreciate you taking the time to contribute, and we look forward to seeing more from you in the near future. By the way, congrats on your 1st docs contribution!

**Pull request merged**
