### PR TITLE
IIS hosting and troubleshooting updates (Stage 3)

### LINKED ISSUE #5135: UE pass topics in the Host and Deploy section of the TOC
UE pass topics in the *Host and deploy* section of the TOC, especially the new IIS troubleshooting topic.

The IIS topic had a CSAT in the 70% range in the 1.0-era following a major content expansion. The topic's content didn't significantly change over time, but CSAT saw a drop to ~53% before bouncing back to the current 57%. We attribute this to a more diverse set of readers accessing the topic with a wider array of IIS skills. I'll take this into account when working on the topic. There are helpful community feedback comments in Comment Hub to address.

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #5100 
Fixes #5135 

[Internal Review Topic (IIS troubleshooting)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?branch=pr-en-us-5374&tabs=framework-dependent-deployment)
[Internal Review Topic (Host with IIS)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?branch=pr-en-us-5374&tabs=aspnetcore2x%2Cwindowsserver)

### CODE REVIEW

**Comment by guardrex** [comment]
@Rick-Anderson The most important problem to address is the troubleshooting topic for IIS. We want to reverse the slide in CSAT for IIS hosted app troubleshooting.

The former IIS hosting topic (that included troubleshooting advice) had a CSAT that dropped from ~70% down to 50+% range in approval over a year without significant changes to the topic.

ASP.NET Core is gaining wider attention and adoption, and the topics in this area of the TOC are receiving wider scrutiny from the community. We've made a good move to split the "hosting" bits from the "troubleshooting" advice.

Although these changes move in the right direction, more work will need to be done. Let's not make "perfect" the enemy of "good" here. I'd like to make this pass, ask 🎸 @Tratcher and @shirhatti 🚀 for feedback, and then even return to these topics for 2.1 with another pass.

**Comment by Tratcher** [comment]
This is pretty substantial, I'm not sure when I'll get a chance to go over it. @shirhatti can you do a first pass?

**Comment by guardrex** [comment]
@Tratcher I apologize for that. It's been a while since I've really gone over this. So many lessons have been learned (by me anyway :smile:). Would it be better for you if I broke this up into smaller bite-size, single doc changes? We can just go piece by piece over a week's time and not have this be such a crazy burden.

**Comment by Tratcher** [comment]
If you have logical units to review, sure.

**Comment by guardrex** [comment]
Yeah ... let's do it. It'll be a lot easier on you and @shirhatti that way.

I'll put the troubleshooting topic on a PR this afternoon ... *and **only** the troubleshooting topic*. lol

**Pull request closed without merging**
