### PR TITLE
Fix urls linking to non-existing dev branch

### PR DESCRIPTION
**Pull request by Rutix**
I noticed that some links point to https://github.com/aspnet/Mvc/blob/dev/src/ but since that one doesn't exist (anymore?). I fixed them to point to master.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Rutix  Much appreciated.

**Comment by Rick-Anderson** [comment]
@guardrex  can you search for these and open an issue if you find more?

**Comment by Rutix** [comment]
@Rick-Anderson Your welcome. I am going through some more files. I will open a PR if I find more 👍

**Comment by guardrex** [comment]
@Rutix Let me know if you're going to search the whole repo for them. If so, I'll let you handle it. If not, I'll do a search this weekend.

**Comment by Rutix** [comment]
@guardrex I searched the whole repo for github links to branches and checked if they existed. I found a couple more which were dead and are now in https://github.com/aspnet/Docs/pull/7606

**Comment by guardrex** [comment]
Thanks ... Much appreciated.

**Pull request merged**
