### PR TITLE
distributed cache -migrate to csproj

### LINKED ISSUE #2705: aspnetcore/performance/caching/distributed.md
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed

### PR DESCRIPTION
**Pull request by Rick-Anderson**
fixes #2705

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@GuardRex  please review

**Comment by GuardRex** [comment]
I'm pulling down the sample to repro it's all good.

FYI tho: Check that `web.config` ... It's got a wacky character at the start of the file that needs to be deleted.

Also note that server GC will be the default, so I think that `runtimeconfig.template.json` file can go adios: https://github.com/dotnet/cli/pull/5537

**Comment by GuardRex** [comment]
... and unused references and out of order `usings` ...

*Program.cs* unused ...
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
```
*StartTimeHeader.cs* unused ...
```
using System;
using System.Collections.Generic;
using System.Linq;
```
... and the `usings` are out of order.

*Startup.cs* unused ...
```
using Microsoft.Extensions.Caching.SqlServer;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Caching.Redis;
```
... `usings` out of order, too.

**Comment by Rick-Anderson** [comment]
Let's just stick with the project.json to csproj conversions this pass

**Comment by GuardRex** [comment]
The sample doesn't run OOB ...
```
System.InvalidOperationException: Either absolute or sliding expiration needs to be provided.
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.ValidateOptions(Nullable`1 slidingExpiration, Nullable`1 absoluteExpiration)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.SetCacheItem(String key, Byte[] value, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.SqlServer.SqlServerCache.Set(String key, Byte[] value, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.Set(IDistributedCache cache, String key, Byte[] value)
   at DistCacheSample.Startup.Configure(IApplicationBuilder app, IDistributedCache cache)
```
Let me play with it a bit and see what I can work out ...
```
Either absolute or sliding expiration needs to be provided.
```
... doesn't sound toooo bad (famous last words :smile:)

**Comment by GuardRex** [comment]
I don't have a local SQL Server instance to fully test, but it looks like it will run with this change ...

Add/update `Configure` in *Startup.cs*:
```c#
var cacheEntryOptions = new DistributedCacheEntryOptions()
    .SetSlidingExpiration(TimeSpan.FromSeconds(30));
cache.Set("lastServerStartTime", val, cacheEntryOptions);
```
... and it's only throwing "You don't have SQL Server installed you GooberRex:tm:!"

**Comment by GuardRex** [comment]
Don't forget to kill that strange 1st character in the *web.config* file.

**Comment by Rick-Anderson** [comment]
I'm not seeing the strange char in _web.config_ with either VS17 or VS Code.

**Comment by GuardRex** [comment]
Open it in the GH UI online ... you'll see that character.

**Comment by GuardRex** [comment]
Everything else LGTM.

I'll have those samples updated to csproj to the "new-csproj" branch in a few hours, and I'll get the Pub IIS thing squared away, too.

**Comment by Rick-Anderson** [comment]
@GuardRex  we see that character frequently (as the first char in the file) in MD files.  We haven't figured out where it's coming from.

**Comment by GuardRex** [comment]
You floated the idea that it might be when people work with the file using the GH UI, but I've been exclusively working with GH UI for PR updates and new docs, and I don't see that character cropping up when I work on the files.

**Comment by Rick-Anderson** [comment]
moved to PR #2738

**Comment by GuardRex** [comment]
@Rick-Anderson *X-Files: The Mystery of the Strange Character*

Some believe that the character was inserted by 👽 to track human activity in advance of an invasion!

Actually, you probably knew or guessed it was the UTF8 BOM (`ï»¿`) ...

capture

If I save a file out of Notepad in UTF8, upload it to a repo, the BOM is there, so it seems like someone or some software has saved/copied a file with UTF8 encoding.

**Comment by Rick-Anderson** [comment]
We see that so frequently I'm a bit skeptical it from copy/paste with notepad.
cc/ @tdykstra @mairaw

**Comment by mairaw** [comment]
@Rick-Anderson not with regular ANSI encoding, right? I think it makes sense. I also see sometimes the red marks for line endings too like in this commit that all I did was to add a space: https://github.com/mairaw/SCCMdocs/commit/ebbc2b250d651aa8befd7f2458d67bf0f4a8ff10#diff-3eb3e38b128dd94833c21d4a73c80a22

**Comment by GuardRex** [comment]
This turned out to be a funky spot for the BOM thing. Just for tracking purposes tho, I'll add it here:

I was just looking at the sample for https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation in the GH UI and see it ...

capture

@Rick-Anderson Curious: You did the sample (I guess) and was wondering how you prepared it? That might explain at least one source of the :alien: BOM. I mean if that software is saving UTF8 that would explain this case.

**Comment by Rick-Anderson** [comment]
We see that frequently and have conjectured it's from web editing. We never figured out where it comes from.

**Comment by GuardRex** [comment]
I do a lot of web editing tho thru the GH UI ... e.g., most of those middleware docs and many of the IIS doc updates were all done via the GH UI ... and I didn't seem to be generating them. Could there be a difference when web editing on non-Windows platforms? Anyway ... this was prob a bad spot to ask/mention it. There isn't a dedicated issue on it AFAIK, so I just plopped that here with the rest of the comments.

**Pull request closed without merging**
