### PR TITLE
Adding blank lines around ::: moniker

### PR DESCRIPTION
**Pull request by JasonCard**
@Rick-Anderson cc @nokura 
Adding blank lines around ::: moniker to fix layout issue for localized live pages.

When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@guardrex  do you know enough regex magic to search for `:::moniker` with no blank lines?

@scottaddie  should I open an OPS bug and have them check for this?

**Comment by guardrex** [comment]
Yes ... I can do it. Shall I open an issue? I take care of it tomorrow morning if you want.

**Comment by Rick-Anderson** [comment]
@guardrex  perfect. thanks

**Comment by scottaddie** [comment]
@Rick-Anderson Please open a bug. DocFX doesn't currently warn of this, but it should if it results in localization issues.

**Comment by Rick-Anderson** [comment]
The issue has been successfully logged as Live Site Incident 84152879.

**Comment by Rick-Anderson** [comment]
@JasonCard do you know if your loc publishing report showed any errors when you didn't have blank lines? We might need to revert this commit and try to reproduce the error.

cc @v-saambe @herohua

**Comment by guardrex** [comment]
> revert this commit and try to reproduce the error.

Recommend one (new) commit to one topic for a test. Things could :boom: :cry: if we revert #8540 given the churn.

**Comment by herohua** [comment]
@JasonCard , with the bug fix you mentioned, can LOC pipeline correct handle span tags with moniker tags for SxS scenario? Is there anything else you need from Markdown engine?

**Comment by JasonCard** [comment]
@herohua When there was no blank line between the moniker range and INCLUDES reference, it caused the transformer to parse the INCLUDES reference a localizable string, so span tags were applied to it.
When source is fixed by adding the blank line, the INCLUDES reference is no longer parsed as localizable string, so span tags are not applied to it and INCLUDES reference is rendered correctly.

**Comment by herohua** [comment]
@JasonCard , thanks for the info. This scenario is actually legitimate for en-us contents. Is it possible to fix the transformer to correctly pass INCLUDES immediately after moniker range?

**Comment by JasonCard** [comment]
@herohua Actually, I just tried with standalone transformer and INCLUDES reference was no longer parsed as localizable string, so it seems to be fixed already. I'll check with Yufei if I see similar issue in the future.

**Comment by herohua** [comment]
Sure, thanks @JasonCard

**Pull request merged**
