### PR TITLE
Fix mulitple typos

### PR DESCRIPTION
**Pull request by ExplodingCabbage**

### CODE REVIEW

**Comment by ExplodingCabbage** [comment]
Oh, really, Pull Request Bot? It was three characters!

**Comment by ExplodingCabbage** [comment]
Wait, what? I'm required to put in my physical mailing address in order to sign the CLA, without any indication of why. I thought that normally the personal information that you give when signing a CLA ended up on a publicly-viewable contributors list; is that what will happen here? Without there being any indication of what my *physical address* is being demanded for, I can't tell if it's going to be published, and without knowing that I'm not willing to give it, and without giving it I'm not even allowed to read the CLA that the system wants me to sign.

Do with this PR as you please; I don't think there are any intellectual property issues with accepting a 3-character change. Meanwhile, whoever created your CLA system might want to clarify whether you're requiring all contributors to dox themselves or not, and if not why it is that they require real-world addresses. I've signed a few CLAs for big-corporate-backed software projects before, and none of them have had such a requirement.

**Comment by Rick-Anderson** [comment]
@ExplodingCabbage  Sorry, it seems like a small change to me. Most small changes don't require signing the CLA, I'm not sure why this one does.  [is:pr is:closed ](https://github.com/aspnet/Docs/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed) shows most small changes don't require CLA. 

Thanks for pointing out the error.

@dend  can you respond to @ExplodingCabbage CLA concerns?

**Comment by ExplodingCabbage** [comment]
@Rick-Anderson no worries about the bot wanting the CLA signed - I guess it's kind of inevitable that any simple attempt to programmatically distinguish "minor" from "non-minor" changes to prose is gonna have perverse results in some edge cases. Maybe your bot is counting the characters changed, but also treating all the characters on a changed line as changed, and so making a one-character edit to three reasonable-length lines seems to add up to about a paragraph of prose and gets treated as non-minor?

I'd have no problem at all signing the CLA if it wasn't for the mailing address thing, but requesting mailing addresses from people in circumstances where:

- doing so is (as far as I know) not typical industry practice, and
- there's no *obvious* reason to request the mailing address, and
- there's no *stated* purpose for requesting the mailing address, and
- the address is mixed in with information (email address and name) that is usually publicly disclosed in the course of contributing to an open source project, with no indication of whether the address itself will be publicly visible

seems to me like a pretty unfriendly practice that could be easily fixed on Microsoft's end, and I'm surprised that nobody has complained before now.

**Comment by Rick-Anderson** [comment]
@ExplodingCabbage  Thanks for bringing this up. Those are all good questions. I'd like to get answers for when it comes up again. No one has brought this to my attention on this repo, but this repo is a very small subset of our repo's. 

@dend are you the right resource to respond to CLA questions? If not, who is?

**Comment by Rick-Anderson** [comment]
@ExplodingCabbage  I raised this to the licensing folks. They did point out that the .   [Google iCLA](https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_INDIVIDUAL), [Google cCLA](http://www.apache.org/licenses/icla.pdf), [Apache cCLA]([url](http://www.apache.org/licenses/cla-corporate.txt)), and [Apache iCLA](http://www.apache.org/licenses/icla.pdf) are require physical address - not saying that makes it right.

Closing for now - thanks again.

**Comment by ExplodingCabbage** [comment]
> They did point out that the . Google iCLA, Google cCLA ... require physical address

Huh, you're right. I didn't recall having to enter an address there, but I must've done.

A significant difference, though, is that Google states that the address will be held privately, whereas with Microsoft I have no idea whether it will or not.

**Pull request closed without merging**
