### PR TITLE
WIP: Secure user data

### PR DESCRIPTION
**Pull request by Rick-Anderson**
This is what [@]blowdart reported:

```
using Microsoft.AspNetCore.Authorization.Infrastructure;
 
// Add https://github.com/blowdart/AspNetAuthorization-Samples/blob/master/src/AspNetAuthorization/Authorization/DocumentAuthorizationHandler.cs
// MapClaimsToOperations
 
namespace ContactManager.Authorization
{
    public static class ContactOperationsRequirements
    {
        public static OperationAuthorizationRequirement Create =  // Add a create handler
            new OperationAuthorizationRequirement { Name = "Create" };
        public static OperationAuthorizationRequirement Read =
            new OperationAuthorizationRequirement { Name = "Read" };  // Add a read handler
        public static OperationAuthorizationRequirement Update =
            new OperationAuthorizationRequirement { Name = "Update" }; // Add a delete handler
        public static OperationAuthorizationRequirement Delete =
            new OperationAuthorizationRequirement { Name = Constants.canDelete };
        public static OperationAuthorizationRequirement ContainsOne =
          new OperationAuthorizationRequirement { Name = Constants.ContainsOne };
    }
 
    public class Constants
    {
        public static readonly string canDelete = "canDelete";
        public static readonly string ContainsOne = "ContainsOne";
    }
}
```
// operations are not permission, permissions are what grant operations
This appears to be mixed up operations and permissions. For example you've defined the name of the create operation as canCreate, which is the actual permission. This isn't what I'd expect, I'd expect the operation name to be create, and then you have a mapping table to map the permission role or claim to the actual operation name inside the handler, or in a helper.
 
 
He said I need to do what he did in https://github.com/blowdart/AspNetAuthorization-Samples/blob/master/src/AspNetAuthorization/Authorization/DocumentAuthorizationHandler.cs

```
private IEnumerable<OperationAuthorizationRequirement> MapClaimsToOperations(string claimValue)
        {
            var mappedPermissions = new List<OperationAuthorizationRequirement>();
 
            if (claimValue.Contains('C'))
            {
                mappedPermissions.Add(Operations.Create);
            }
            if (claimValue.Contains('R'))
            {
                mappedPermissions.Add(Operations.Read);
            }
            if (claimValue.Contains('U'))
            {
                mappedPermissions.Add(Operations.Update);
            }
            if (claimValue.Contains('D'))
            {
                mappedPermissions.Add(Operations.Delete);
            }
 
            return mappedPermissions;
        }
```
Not sure how much value adding create/read/delete handlers would add, but Barry said think about that.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@joeaudette I'm converting the completed project to VS 2017

**Comment by joeaudette** [comment]
@Rick-Anderson I'm not really clear on what the ask/task is, a new sample project or update to an existing one, a new doc, an update to an existing doc? I'm glad to help if I can but don't feel like I know what is being asked for at a high level. I could use some contextual info.

**Comment by Rick-Anderson** [comment]
@joeaudette  sorry-  When [@]blowdart did a security review of the code/article he left the comment above. The code in *Docs\aspnetcore\security\authorization\secure-data\samples\final15* needs to be fixed per his comments. That was created using VS 2015. I'm cleaning up the article and converting all the code to VS 2017. Once I finish cleaning up the article and code I was hoping I could send you a copy of the built article and you could figure out how to fix the code - that is add `MapClaimsToOperations` and make the code work like the [blowdart/AspNetAuthorization-Samples](https://github.com/blowdart/AspNetAuthorization-Samples)

**Comment by joeaudette** [comment]
@Rick-Anderson sounds good, be glad to help with that

**Comment by Rick-Anderson** [comment]
@joeaudette  open aspnetcore/security/authorization/secure-data/samples/final15/15FinalCM.sln
Open a command window in the project folder and run
```
dotnet user-secrets set SeedUserPW <password>
dotnet ef database update
```
Run the app, tap the contactManager link - that will redirect you to the login page. Log in with the test account ( `test@example.com` ) using the password you set. You're now logged in as the owner of the test data and also an admin.

Log off and create another account - you can see all the data but only edit your data. Create some contacts. Log in the test account and you can delete all the data (but you can't edit other users data).

I need to rewrite the tutorial but before I start we need to make the security change Barry requested.

**Comment by joeaudette** [comment]
@Rick-Anderson what repo do I need to clone/fork? I don't see that below https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authorization

**Comment by Rick-Anderson** [comment]
@joeaudette  It's only in this PR
`git fetch origin pull/3225/head:secure-data`

**Comment by joeaudette** [comment]
@Rick-Anderson sorry I'm not as expert at git as I should be. I forked the Docs repo, opened the git shell and ran the command indicated and got an error. I'm sure I'm doing something wrong.

    C:\_joe\__projects\dotnet\Docs [master ↑1551]> git fetch origin pull/3225/head:secure-data
    fatal: Couldn't find remote ref pull/3225/head
    C:\_joe\__projects\dotnet\Docs [master ↑1551]>

do I need to change to a specific branch first?

**Comment by joeaudette** [comment]
ok, I changed to your branch ra/secure-user-data2 and now I see the samples

**Pull request closed without merging**
