### PR TITLE
fix template option error

### PR DESCRIPTION
**Pull request by lovelangy**
There is no such  template option named 'webapp'. we should use 'mvc' or 'razor' instead.

### CODE REVIEW

**Comment by scottaddie** [comment]
@lovelangy The "razor" alias doesn't appear in the CLI output; however, it is valid. See https://github.com/aspnet/Templating/blob/1dfe06323f84e4c25356e6befe8b052cdf0c3707/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/.template.config/template.json#L17. The first alias in the `shortName` array is the alias that displays in the CLI output.

**Comment by lovelangy** [comment]
@scottaddie  oh, i see.  'webapp' is introduced in .net core 2.2.   It doesn't work on .net core 2.1.

**Comment by lovelangy** [comment]
@scottaddie   I am afraid that is not the case.  

 This is what I have done test on my laptop:

1. Install .net core, 2.2.100-preview3-009430,   i can run "dotnet new webapp --auth Individual -o WebApp1" successfully.
2. Uninstall   .net core, 2.2.100-preview3-009430, verify the version via "dotnet --version".
3. it says "2.1.202", which means it is .net core 2.1
4. run "dotnet new webapp --auth Individual -o WebApp1" again.
5. it returns "No templates matched the input template name: webapp." 

Also, Based this doc,  webapp alias is not in .net core 2.1.
[dotnet new command](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore21)

**Comment by scottaddie** [comment]
@lovelangy Here's the ASP.NET Core 2.1 RTM templates release branch showing that both `webapp` and `razor` were supported in the Razor Pages project template:
https://github.com/aspnet/Templating/blob/release/2.1/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/.template.config/template.json#L15

.NET Core SDK 2.1.300 was the RTM version of .NET Core 2.1. I see you're using .NET Core SDK 2.1.202, which would've installed the ASP.NET Core 2.0 runtime (2.0.9 to be exact). See https://www.microsoft.com/net/download/dotnet-core/2.0.

The doc you linked to needs to be updated. I'll take care of that right now. Thank you for pointing this out!

**Pull request closed without merging**
