### PR TITLE
C19394: Missing hyperlink due to incorrect structure

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @rick-anderson,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version.  

 Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.

Many thanks in advance.

When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

### CODE REVIEW

**Comment by scottaddie** [comment]
Thank you, @carolinacmoravia!

**Comment by Rick-Anderson** [comment]
@scottaddie  doesn't VSC addons catch that? I wasn't using VSC at the time.

**Comment by scottaddie** [comment]
@Rick-Anderson I don't think this would've been caught by those add-ons.

**Comment by Rick-Anderson** [comment]
@scottaddie I'm pretty sure it warns about naked links. I got that warning before and thought it was a bogus warning.

**Pull request merged**
