### PR TITLE
Identity Scaffolding creates empty Services folder 8233

### LINKED ISSUE #8233: Identity Scaffolding creates empty Services folder
https://github.com/aspnet/Scaffolding/issues/857

cc @isaac2004
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by isaac2004**
Document fact that services are not generated when scaffolding Identity 
Fixes #8233 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&branch=pr-en-us-8257&tabs=visual-studio)

### CODE REVIEW

**Comment by isaac2004** [comment]
@Rick-Anderson FYI

**Comment by Rick-Anderson** [comment]
@isaac2004  take a look at the code just above [Changes to Razor Pages projects Razor files](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-razor-pages-projects-razor-files)

```
 // Register no-op EmailSender used by account confirmation and password reset 
    // during development
    services.AddSingleton<IEmailSender, EmailSender>();
}
```

Why did I need to add that to a 2.0 project converted to 2.1 and using the Identity RCL?  The 2.1 templates don't need `services.AddSingleton<IEmailSender, EmailSender>();`

**Comment by Rick-Anderson** [comment]
@isaac2004  please review [this](https://github.com/aspnet/Docs/pull/8257/commits/190df8bd12ce0cbf2c0d6d70aa4293c9727990fb) commit.

**Comment by isaac2004** [comment]
Maybe @blowdart can chime in but if you look at the Identity UI code (on mobile so can't link well) The service is stubbed out so it won't actually send anything. If the user wants to send emails and sms, I believe you have to write your own service and register. I may be incorrect here

**Comment by Rick-Anderson** [comment]
@isaac2004  that's correct. [Account confirmation and password recovery](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=visual-studio) is mentioned in the note and it shows how to do that.

Even when it generated stubs in the past, they were just stubs and didn't send email.

**Comment by Rick-Anderson** [comment]
@scottaddie  way is WIP blocking? I don't see it in any commit.

**Comment by scottaddie** [comment]
@Rick-Anderson Not sure what was going on, but it's unblocked now.

**Pull request merged**
