### PR TITLE
user-secret -> dotnet user-secrets

### PR DESCRIPTION
**Pull request by iscifoni**
Add new sample on AccountConfermation to use RC2 version and SendGrid.NetCore
Update documet AccountConfirmation to use new sample
Update document Two-factor authentication with SMS user-secret -> dotnet user-secrets

issue #919

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@iscifoni  Thanks, this really needed to be updated. We're swamped right now so it will take me at least a week to get to this.

**Comment by danroth27** [comment]
These changes look good. The Travis failure is due to a limitation in the C# lexer that we can easily work around. Also, we should remove the old sample.

**Comment by iscifoni** [comment]
Ok i'll  do it .

thanks

**Comment by danroth27** [comment]
I took care of it for you: https://github.com/aspnet/Docs/pull/1529. Thank you!

**Comment by danroth27** [comment]
a28d47e61ca7bbc4e0487d8b4b8a708aa5c174a7

**Pull request closed without merging**
