### PR TITLE
add to TOC

### PR DESCRIPTION
**Pull request by tdykstra**

### CODE REVIEW

**Comment by ardalis** [comment]
You were going to add the Custom Storage Providers TOC entry and placeholder file, too, right?

**Comment by tdykstra** [comment]
Sorry, misunderstood what you were asking.  I wouldn't merge the TOC change pointing to a stub, though -- we could merge this, and I could create a branch with the TOC and stub, and you can work off of that branch, does that sound OK?

**Comment by ardalis** [comment]
Sure, that works fine, too. I figured we wanted the stub with the wrench but if we don't I'm fine with that as well.

**Comment by tdykstra** [comment]
We decided to get rid of all the wrench stubs as they seemed to cause more low satisfaction ratings without effectively eliciting offers to write them.
I'm creating a branch with toc and stub for you now.

**Comment by tdykstra** [comment]
New branch is ardalis-identity

**Comment by ardalis** [comment]
You rock, thanks!

**Pull request merged**
