### PR TITLE
add essential step in NGINX tutorial

### PR DESCRIPTION
**Pull request by user135711**

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @user135711 for mentioning it.

This reminds me that I'll need to address the same scenario for full IIS hosting.

We'll probably look at how this is phrased. It probably should go along the lines of ...

> When using a \`dotnet new\` template and not \[configuring Nginx for HTTPS](#configure-ssl), disable the \[HTTPS Redirection Middleware](xref:security/enforcing-ssl) (\`app.UseHttpsRedirection();\`) in \`Startup.Configure\`. Either remove the line or comment it out. If the middleware is active but Nginx can't forward the request because it isn't configured for HTTPS, the web app won't be reachable after the redirect to the secure endpoint.

... something like that.

**Comment by user135711** [comment]
@guardrex The second sentence (If the middleware is active) needs to be clearer because non experts like me need to understand it. By Nginx isn't configured to use https you mean that the server block passes to the local app with the directive `proxy_pass         http://localhost:5000/;` which has it's own redirect to https://localhost:5000 which will then return to NGINX (this step is what makes it a reverse proxy) which then will use the default proxy_redirect command, which reverses the location header with the unwritten default command `proxy_redirect http://localhost:5001 /;` It takes the second argument as from the location and in the server block location appended to the $host_proxy and exchanges it to be the original $host. Since an asymmetric reverse step comes from a secure host, you could still do it but you need to use `proxy_redirect https://localhost:5001 /;`

**Comment by guardrex** [comment]
Indeed ... it is best if you and @shirhatti work out the language, and I'll just handle the grammar+style guidelines part.

A bit unrelated to your issue, but I was just looking at how the middleware attempts to determine the secure port. Apparently when IIS doesn't have a secure port for the app, the ANCM forwards that fact via the `IServerAddressesFeature`'s binding address. Without a secure port, the middleware no-ops.

**Comment by user135711** [comment]
How does this version sound?
> When using a `dotnet new` template and not [configuring Nginx for HTTPS](#configure-ssl), disable the [HTTPS Redirection Middleware](xref:security/enforcing-ssl) (`app.UseHttpsRedirection();`) in `Startup.Configure`. Either remove the line or comment it out. If the middleware is active but Nginx  forwards the request to an insecure localhost, the web app won't be reachable after the redirect to the secure endpoint because the reverse redirection to the public address won't occur. Only host production apps which are not on the same server or internal network as Nginx using [Nginx configured for HTTPS](#configure-ssl).

**Comment by guardrex** [comment]
Sounds good to me ... let's see what `@shirhatti` says. You can update the PR with that text if you like.

**Comment by shirhatti** [comment]
I'm not a fan of this.
If you **choose** to disable HTTPS of your own volition, I'd rather you start out with `dotnet new webapp --no-https` rather than going down this approach

**Comment by shirhatti** [comment]
That being said, we still need to document everything it entails to run behind a proxy (#6538)

**Comment by guardrex** [comment]
@shirhatti Does the Nginx and the middleware configuration handle the secure port in a similar fashion to IIS? ...

1. No secure port is configured for the app in Nginx
1. `IServerAddressesFeature` addresses don't have a bound address with an HTTPS scheme
1. The middleware no-ops

**Comment by guardrex** [comment]
@user135711 I'm going to close on @shirhatti's advice. Thanks anyway for opening the PR and the discussion.

**Pull request closed without merging**
