### PR TITLE
Update identity-enable-qrcodes.md

### LINKED ISSUE #5320: QR codes update
Copied from `@PinpointTownes` in #5144
You may also want to revamp https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes#adding-qr-codes-to-the-2fa-configuration-page and remove the last paragraph of https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes#using-a-different-qr-code-library as it recommends using `Html.Raw` for invalid reasons (which is double-terribad :sweat_smile:)

From https://github.com/aspnet/Docs/issues/5144

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #5320

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?branch=pr-en-us-5323)

@PinpointTownes  what about this raw?

 ` text: "@Html.Raw(Model.AuthenticatorUri)",`

```
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script type="text/javascript" src="~/lib/qrcode.js"></script>
    <script type="text/javascript">
        new QRCode(document.getElementById("qrCode"),
            {
                text: "@Html.Raw(Model.AuthenticatorUri)",
                width: 150,
                height: 150
            });
    </script>
}
```

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@PinpointTownes please review.

**Comment by Rick-Anderson** [comment]
@HaoK  please review.

**Comment by PinpointTownes** [comment]
@Rick-Anderson IMHO, keeping `Html.Raw` is meh. Instead, consider reading the `data-url` attribute of the `qrCodeData` div using the DOM APIs.

**Comment by HaoK** [comment]
This looks fine to me, @blowdart should review though since I know there was some security related fixes around 2fa recently...

**Comment by blowdart** [comment]
Ah here HtmlRaw is fine, because it's binding to the model, and the model binding is now fixed.

**Comment by PinpointTownes** [comment]
In the advisory, you included a step to remove `Html.Raw`. For consistency, you should do the same thing in the JS code.

**Pull request merged**
