### PR TITLE
Add CLA completion link in contributing doc

### PR DESCRIPTION
**Pull request by AdrienTorris**
Add the CLA completion link in contributing.md, with others details about complex PR.

I had to complete the CLA and it was difficult to know what the procedure is. On google, you'll find multiple links and posts, all wrong or obsolete : https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=CLA+microsoft+github&start=0

The only one good information I found was here : https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/AdrienTorris/Docs/blob/patch-2/CONTRIBUTING.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C23%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611231318263508-2237%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@tdykstra  please review.  Should we link to https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md?

**Comment by tdykstra** [comment]
@Rick-Anderson I prefer to leave here the direct link to cla2.dotnetfoundation.org.  The aspnet/home/contributing.md is more about contributing to the product than the docs.

**Comment by Rick-Anderson** [comment]
@tdykstra  OK.

**Comment by Rick-Anderson** [comment]
@tdykstra  is this ready to merge?

**Pull request merged**
