### PR TITLE
[WIP] Fix property assignment in primitives example

### PR DESCRIPTION
**Pull request by user135711**
Fixed a bug where CurrentState is assigned the wrong value on each invocation followed by being assigned the correct value in index. Also fixed an np completeness inefficiency by passing a lamda instead of a method group since I was editing the line, and used a non primitive state object so that the value is passed by reference to reflect the current state. For np explanation see
<a href="https://blogs.msdn.microsoft.com/ericlippert/2007/03/26/lambda-expressions-vs-anonymous-methods-part-four/">here</a>and
<a href="https://blogs.msdn.microsoft.com/ericlippert/2007/03/28/lambda-expressions-vs-anonymous-methods-part-five/">here</a>

### CODE REVIEW

**Comment by user135711** [comment]
I didn't realize that github would squash any commit into my repository into any pull requests so this commit now has an unrelated commit included which makes webcache compilable. This fixes #6299.

**Comment by guardrex** [comment]
Hello @user135711! Thanks for submitting this.

Would you mind removing the changes for the WebCache sample from this? We wouldn't want both samples updated on the same PR, and we can't take a PR for the WebCache sample at this time. For one thing, we can't upgrade it to 2.1 until 2.1 RTM. Also, it's due for a significant overhaul when it is upgraded that will go beyond just making it run under 2.1. We're tracking the work for it on #5495.

**Comment by guardrex** [comment]
RE: The ChangeTokens updates

The changes proposed require matching changes to the topic's text for the `ConfigurationMonitor` ctor and the `InvokedChange` callback on the same PR so that the live sample doesn't become out-of-sync with the topic when the PR is merged.

https://docs.microsoft.com/aspnet/core/fundamentals/primitives/change-tokens#monitoring-configuration-changes-as-a-service

**Comment by user135711** [comment]
@guardrex That's a good point, thanks...

**Comment by guardrex** [comment]
If you prefer that this just be taken into account for the Change Tokens 2.1 update, I recommend just opening an issue referencing this, then I'll add a note to the tracking issue for it.

**Comment by guardrex** [comment]
Alternatively, feel free to go ahead with a PR on the Change Tokens topic with these changes now, and I'll ping engineering to take a look.

**Comment by user135711** [comment]
@guardrex Shrug, if you're doing it anyway, I'll just let you update them at once. I do have some suggestions for the change tokens update that I'll post directly to the issue so you'll consider including it and save me some time if you do it.

**Comment by guardrex** [comment]
ok ... sounds good.

**Pull request closed without merging**
