### PR TITLE
Deployiis

### PR DESCRIPTION
**Pull request by pgoldman5699**

### CODE REVIEW

**Comment by guardrex** [comment]
@Rick-Anderson I can review this if it can wait a few days.

 ... I'm buried in **_COMMON ERRORS_** at the moment. :smile: lol

**Comment by pgoldman5699** [comment]
#hold-off

**Comment by pgoldman5699** [comment]
Okay, thanks! I still need a peer review on this one.

________________________________

**Comment by guardrex** [comment]
@pgoldman5699 "peer review" ... do you have another reviewer before you want me to look, or do you mean *me*? We generally don't look at these while "[WIP]" is on the title. When you're ready, remove the "[WIP]," and that let's us know you're ready for review.

**Comment by pgoldman5699** [comment]
Hi Luke:


Thanks, but I'm waiting on one more peer review. I was told to put '[WIP]' in front of the title while peer reviews are still taking place. I used to comment '#hold-off' but was told [WIP] is how they want it now.


~Paul

________________________________

**Comment by guardrex** [comment]
Yes, you're correct. I just wanted to confirm that by "peer review" you weren't talking about the docs team.

Yes, I'll keep an eye out for when you take the "[WIP]" off of the title.

**Comment by pgoldman5699** [comment]
@tdykstra @Rick-Anderson , this PR is ready for your review. Please let me know what you'd like changed.

**Comment by guardrex** [comment]
@pgoldman5699 I'll look this over soon ... hopefully later today (1/15).

**Comment by guardrex** [comment]
I tried to get to this today but was 🏃🏃🏃😅 on other tasks. I'll try again tomorrow (Wed, 1/16).

**Comment by pgoldman5699** [comment]
No problem, take your time. :-)

________________________________

**Comment by Rick-Anderson** [comment]
@guardrex I'm too late for this PR, but I noticed you changed "have to" to "must" everywhere : "have to" is approved usage.  See for example https://review.docs.microsoft.com/en-us/help/contribute/writing-principles-voice-job-aid?branch=master

cc @tdykstra 	in case I'm wrong.

**Pull request merged**
