### PR TITLE
Update an-overview-of-project-katana.md

### PR DESCRIPTION
**Pull request by sultanimbayev**
Quotes fix at owin.RequestProtocol

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@sultanimbayev  looks like you have a commit with https://github.com/aspnet/Docs/pull/4859

**Comment by sultanimbayev** [comment]
I'm sorry. I didn't mentioned that i have opened two pull requests with the same changes

**Comment by sultanimbayev** [comment]
can you just drop changes of sample4.cs?

**Comment by sultanimbayev** [comment]
I will open another pull request.

**Pull request closed without merging**
