### PR TITLE
First App - Update to step and image.

### PR DESCRIPTION
**Pull request by Erikre**

### CODE REVIEW

**Comment by Erikre** [comment]
@Rick-Anderson @danroth27 Quick update. Need shipit and publish. Thanks

**Comment by Rick-Anderson** [comment]
:shipit:  @rachelappel  can you merge?

**Comment by rachelappel** [comment]
Merged.  92a0a356f87e536bfe3c70d54feafb895d27c66f

**Comment by rachelappel** [comment]
Merged. 92a0a356f87e536bfe3c70d54feafb895d27c66f

**Pull request merged**
