### PR TITLE
Use  CreateWebHostBuilder in localization samples

### PR DESCRIPTION
**Pull request by hishamco**
Addresses a part of issue #5495
@Rick-Anderson @guardrex please update the tracker

### CODE REVIEW

**Comment by guardrex** [comment]
> update the tracker

#5495

**_Done!_** ... and the :pray: server gods :pray: bless you for the work here.

**Comment by hishamco** [comment]
Thanks @guardrex, hope I got a time to close almost the issues in the tracker, but frankly focusing on localization once 😄

**Comment by hishamco** [comment]
BTW @guardrex you missed to update the work item `fundamentals\portable-object-localization.md`

**Comment by Rick-Anderson** [comment]
@hishamco 	much appreciated.

**Pull request merged**
