### PR TITLE
Update DataProtection

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
@Tratcher To take a look at the cookie sharing specifically

**Comment by Tratcher** [comment]
:+1:

**Comment by BrennanConroy** [comment]
@Rick-Anderson @danroth27

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Docs/issues/1105

**Comment by Rick-Anderson** [comment]
:shipit:

**Pull request merged**
