### PR TITLE
fix DocFX builds

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@bradygaster  please review ASAP.  The docFX.json, toc.md, index.md all need work. This builds without warnings/errors and serves content correctly from DocFX builds.

**Comment by bradygaster** [comment]
@Rick-Anderson you can remove the metadata section with the "src" stuff in it. this docset contains no source code or api docs

**Comment by Rick-Anderson** [comment]
@bradygaster  fixed. Can you approve and I'll merge

**Comment by bradygaster** [comment]
lgtm

**Comment by Rick-Anderson** [comment]
@bradygaster  can you approve? Also unrelated see build error
https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201610282147367165-2021%5Cworkflow_report.html

**Pull request merged**
