### PR TITLE
Update Introduction to Identity with ASP.NET Core 2 API's

### LINKED ISSUE #4043: Intro to Identity Needs Updated to 2.0
This [article](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?tabs=visual-studio) still uses the 1.x API's for configuring Cookies.  These API's are missing in 2.x.

Specifically this:
```csharp
services.Configure<IdentityOptions>(options =>
{
    // Cookie settings
    options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromDays(150);
    options.Cookies.ApplicationCookie.LoginPath = "/Account/LogIn";
    options.Cookies.ApplicationCookie.LogoutPath = "/Account/LogOut";
});
```

Should be this:
``` csharp
services.ConfigureApplicationCookie(
{
    // Cookie settings
    options.Cookie.Expiration= TimeSpan.FromDays(150);
    options.LoginPath = "/Account/Login";
    options.LogoutPath = "/Account/Logout";
});
```

Happy to send a PR (for real this time!), but didn't know if this was already a WIP somewhere that I didn't see already, and if you wanted to have tabs for 1.x vs 2.x behavior like other places on the docs.

Thanks!

### PR DESCRIPTION
**Pull request by scottsauber**
Fixes #4043 

[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/security/authentication/identity?branch=pr-en-us-4236)

@scottaddie

### CODE REVIEW

**Comment by scottsauber** [comment]
@scottaddie

**Comment by scottsauber** [comment]
The v1 snippets do not have the snippet_ prefix. Do you want me to fix those as well in this PR?

**Comment by HaoK** [comment]
In the 2. Configure Identity services and add middleware section:

> UseAuthentication adds cookie-based authentication middleware to the request pipeline.

This is no longer correct, its actually AddIdentity that adds cookie-based authentication.  UseAuthentication adds the authentication middleware to the request pipeline.

**Comment by HaoK** [comment]
Side note: we need to update https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-primary-key-configuration?branch=pr-en-us-4236 for 2.0 as well as a few smallish things have changed in there too

**Comment by scottaddie** [comment]
@scottsauber If you have time, please fix those as well.

**Comment by scottsauber** [comment]
Let me know if anything else needs updating.

**Comment by scottaddie** [comment]
@scottsauber Awesome work! Thank you for your help updating this doc. Your changes will go live within the next 24 hours.

**Comment by scottsauber** [comment]
Thanks for your help guiding me @scottaddie and @HaoK!

**Pull request merged**
