### PR TITLE
Authz DI

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@blowdart  can you help me with this?

**Comment by blowdart** [comment]
Darn it, stop adding my name in there. Seriously, I don't put my name on my docs, because it doesn't matter to me.

It might be worth pointing that handlers which take DI classes which are from EF shouldn't be registered as singletons :)

**Comment by Rick-Anderson** [comment]
@blowdart  fixed. Feel free to suggest better verbage.

**Comment by Rick-Anderson** [comment]
@blowdart removed your name and added EF caveat.  Is my rewrite OK? - please suggest a better write up if I missed it up.

**Comment by Rick-Anderson** [comment]
@blowdart  I need a shipit or reject :-(

**Comment by blowdart** [comment]
:shipit:

**Pull request merged**
