### PR TITLE
Fix create directory PS command

### PR DESCRIPTION
**Pull request by fvoronin**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@sayedihashimi  please review.
@fvoronin  if accepted, you'll need to make this change at https://github.com/Microsoft/Docs-1

**Comment by danroth27** [comment]
LGTM - we should get this integrated into the new markdown based content.

@fvoronin Can you update the PR?

**Comment by sayedihashimi** [comment]
:shipit:

**Comment by Rick-Anderson** [comment]
@fvoronin we can update the PR if you like

**Comment by Rick-Anderson** [comment]
moved to https://github.com/aspnet/Docs/pull/2080

**Pull request closed without merging**
