### PR TITLE
TOTP

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes some of  #7326 
Internal review URLs follow
[2FA](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.0&branch=pr-en-us-7330)
[TOTP](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-2.0&branch=pr-en-us-7330)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@skyflyer  please review mitigating update.

**Comment by Rick-Anderson** [comment]
@blowdart  this PR deals with the 
>I couldn't find it documented anywhere. 
portion of #7326
I'll handle enable/opt-in/out in another PR

**Comment by skyflyer** [comment]
> @skyflyer please review mitigating update.

This document (2fa.md mainly) still emphasises SMS for 2FA, even though TOTP 2FA is supported out of the box now (and mentioned in the doc as industry standard).

I know you haven't prepared opt in/out info yet and that's what I would expect in this page. More background info and magic demystified :). My sentiment is similar to that in #7212.

I would expect something along those lines in the 2FA document (the current pretext is fine):

* TOTP 2FA is enabled by default. You don't need to configure it. Users can use authenticator apps, etc.
* If you want to disable TOTP 2FA, you can ....
* If you want to use SMS or email for 2FA, it is enabled by...

**Comment by Rick-Anderson** [comment]
@skyflyer  TOTP details go on the [TOTP](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes) page, not the SMS page. The SMS page should only recommend TOTP and point to it.

**Comment by Rick-Anderson** [comment]
@skyflyer  Those are all good comments for the [TOTP](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes) page, not the SMS page. This PR is about the SMS page and increasing SEO for TOTP (your first complainant).

**Comment by skyflyer** [comment]
OK. I just don't find the "TOTP" page to be intuitive about TOTP authenticator, but rather about QR code generation for it. The URL and the title are both very explicit what that page is about: "Enable QR Code generation for TOTP authenticator apps in ASP.NET Core".

Perhaps it is just me, so please, don't take this the wrong way. But what I'm missing is *information* about TOTP authenticator. The QR Code generation should be either in a linked page or below that more important bits of information. The 2FA page should list available 2FA options, and provide specifics further down.

Thanks for the good work!

**Pull request merged**
