### PR TITLE
typo: initializator -> initializer

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@nschonni  hold off on the PR's, the aspnet framework repo is frozen.

**Comment by Rick-Anderson** [comment]
The new repo is https://github.com/aspnet/AspNetDocs
I'm not sure we can easily migrate thesee to https://github.com/aspnet/AspNetDocs
cc @scottaddie

**Comment by nschonni** [comment]
if you're going to mark this repo as archived, then i think you can move the issues fairly easily, but PRs I don't think are easily migrateable

**Comment by Rick-Anderson** [comment]
BTW, it's just the ASP.NET Framework docs were moving, not the Core stuff.

**Comment by Rick-Anderson** [comment]
cc @tdykstra @guardrex

**Comment by Rick-Anderson** [comment]
@nschonni  sorry this repo is being migrated to https://github.com/aspnet/AspNetDocs

**Pull request closed without merging**
