### PR TITLE
Added code location to options

### PR DESCRIPTION
**Pull request by user135711**
Added the source location of each code sample of ASP.NET Core Fundamentals [Options ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options)topic to increase readability. In addition, I would suggest adding a code example using IOptionsMonitor, IOptionsFactory and IPotionsMonitorCache.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@user135711  thanks for this. The document is not a beginning tutorial and dev's will be able to find the right location. Some files like options don't need to go where you specified.

**Comment by user135711** [comment]
Sure. It was just a novice suggestion. On the same lines, whoever is in charge of the livefyre comments should allow the side comments to be deleted by the commentor because it's easy to make mistakes in comments or realize later that something asked is already in the document or obvious. The comments at the bottom are already self deletable, and I don't see why the side comments aren't.

**Comment by Rick-Anderson** [comment]
We've made that suggesting to LiveFyre many times.  We hope to have that resolved in the next couple of months.

**Comment by user135711** [comment]
Also, the reference source link for ioptionsfactory is still broken at the bottom of the options page.

**Comment by Rick-Anderson** [comment]
Which one exactly? they're all working for me.

**Comment by user135711** [comment]
@Rick-Anderson https://github.com/aspnet/Options/blob/release/2.0.0/src/Microsoft.Extensions.Options/OptionsFactory.cs gives me 404

**Comment by Rick-Anderson** [comment]
Thanks. It should be https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options/OptionsFactory.cs
can you create a PR with that fix and ask @guardrex  to review it?

**Comment by user135711** [comment]
Yup.

**Comment by guardrex** [comment]
Hold on a sec @user135711 ... I need to check something.

**Comment by guardrex** [comment]
@user135711 Use this one (the current link is missing an "I" for `IOptionsFactory`. We don't want to doc dev features, so it's best to peg the version to 2.0.

https://github.com/aspnet/Options/blob/release/2.0/src/Microsoft.Extensions.Options/IOptionsFactory.cs

**Comment by user135711** [comment]
@guardrex ok

**Pull request closed without merging**
