### PR TITLE
NanoServer

### PR DESCRIPTION
**Pull request by GuardRex**
Addresses #194

### CODE REVIEW

**Comment by GuardRex** [comment]
@Rick-Anderson I'm going to re-run the full doc start to finish tomorrow ... VM's from scratch and the works.

@benaadams I ended up not using the `Restart-Computer` cmdlet. It crashed my PS ISE instance! Right now, I have it back to (1) Exit the PS session, (2) Close the remote PS tab, (3) Restart the Nano in the Azure Portal. I'll try again with `Restart-Computer` on my next run-through of the whole doc, which will be tomorrow.

Oh ... and @Rick-Anderson could you clarify this line for me from the guidelines ...
 > Don't update or merge your branch after you submit your pull request

... what is it telling me **not** to do? I guess I'm asking broadly, how are additional commits (updates) submitted out of Github for Windows?

**Comment by benaadams** [comment]
@GuardRex should have told you, you have to close the tab before it crashes :grin:

**Comment by GuardRex** [comment]
@benaadams Gee ... thanks ...... I think! :smile:

**Comment by GuardRex** [comment]
@Rick-Anderson The Travis failure is a dup link in the Additional Resources. I took it out locally and committed locally but that didn't lick it. Was I supposed to Publish to my branch prior to submitting the PR, then additional commits will get pushed from my branch to master when I make them?

**Comment by GuardRex** [comment]
@Rick-Anderson oh ... I think I got it. Yes! Got it. Sorry.

**Comment by GuardRex** [comment]
ooops! I knew I was going to break something. :cry:

**Comment by GuardRex** [comment]
There are minor grammatical updates coming this afternoon (e.g., Conventions used table, minor phrasing issues here and there, etc.). I'll get it ship-shape by 6pm PST today.

**Comment by Rick-Anderson** [comment]
I'll work on a quick start using this great info. Nano team has requested a simpler quick start.

**Pull request closed without merging**
