### PR TITLE
Update Azure deployment via VS tutorial

### PR DESCRIPTION
**Pull request by cesarbs**
Few textual changes. Updated all screenshots.

I didn't like the alising on most screenshots due to image resizing, so I made new screenshots that fit in the docs without resizing. I had to cut out some dialog pieces in a few cases where I couldn't resize those dialogs down to the proper width.

cc @Rick-Anderson @danroth27

### CODE REVIEW

**Comment by cesarbs** [comment]
@Rick-Anderson Two questions on style:

* Why don't we end bullet items with periods?
* Why do we use "tap" instead of "click" or "select"?

**Comment by Rick-Anderson** [comment]
@cesarbs  that's MS modern style - used by most progressive companies.  Same reason titles/heading use sentence casing ( for example: https://docs.asp.net/en/latest/tutorials/first-mvc-app/index.html but I need to fix  the last few starting with Validation )
new style
Adding a controller
Old
Adding a Controller

**Comment by Rick-Anderson** [comment]
@cesarbs  you can use directives with images: 
.. image:: picture.jpeg
   :height: 100px
   :width: 200 px
   :scale: 50 %
   :alt: alternate text
   :align: right

**Comment by Rick-Anderson** [comment]
:shipit:

**Pull request merged**
