### PR TITLE
Dotnet watch update

### LINKED ISSUE #1902: The dotnet-watch sample does not compiles.
Hi. I followed the documentation and I want to test the dotnet watch but when I add the Watcher to tool like the following:

```
"tools": {
        "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
},
```

Then I get the following error in the time of restoring:

C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample>dotnet restore
log  : Restoring packages for C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample\WebAppTests\project.json...
log  : Restoring packages for C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample\WebApp\project.json...
error: Unable to load the service index for source https://dotnet.myget.org/F/aspnet1/api/v3/index.json.
error:   Response status code does not indicate success: 404 (Feed does not exist.).

### PR DESCRIPTION
**Pull request by spboyer**
Closes #1902 
Closes #1909

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/mvc/views/tag-helpers/toc.md](https://github.com/aspnet/Docs/blob/dotnet-watch-1994/aspnetcore/mvc/views/tag-helpers/toc.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/views/tag-helpers/toc.md)
[aspnetcore/tutorials/dotnet-watch.md](https://github.com/aspnet/Docs/blob/dotnet-watch-1994/aspnetcore/tutorials/dotnet-watch.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/tutorials/dotnet-watch.md)



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C15%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611151619300732-2174%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@spboyer  is this ready for review?

**Comment by spboyer** [comment]
Yes it was a small edit

**Comment by Rick-Anderson** [comment]
I just merge small edits without a review (after validation passes).

**Pull request merged**
