### PR TITLE
React to AuthorizationHandler changes

### PR DESCRIPTION
**Pull request by sebastienros**
This is WIP, please do not merge yet.

### CODE REVIEW

**Comment by sebastienros** [comment]
Open for review.

/cc @HaoK

**Comment by HaoK** [comment]
LGTM, @blowdart ?

**Comment by blowdart** [comment]
@danroth27 is dev where rtm docs go? Frankly this needs to be updated everywhere, not just in resource

**Comment by danroth27** [comment]
@blowdart Are these changes specific to the RTM bits, or are they also relevant for the RC2 bits? Only RTM specific stuff needs to go into dev. Most stuff can go into RC2.

**Pull request merged**
