### PR TITLE
Update ASP.NET Core Logging Extensions name

### LINKED ISSUE #9968: Update ASP.NET Core Logging Extensions name
The name will change at 3.0 RTM to the singular "extension."

Work tracked in engineering by https://github.com/aspnet/AspNetCore/issues/4570.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.2#monitoring-and-logging)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #9968

Cross-ref: [Build 3.0 AggregateSite extension (aspnet/AspNetCore \#6849](https://github.com/aspnet/AspNetCore/pull/6849)

@pakrym Do I need to version this in the topic for 3.0, or is the new name in effect at this time?

### CODE REVIEW

**Comment by pakrym** [comment]
We didn't ship new logging site extensions in 3.0 yet but as soon as it goes out it preview3 this would be the only name around.

**Comment by guardrex** [comment]
mmmmm 🤔 Let's not version this then and just hold it here for a bit.

**Comment by guardrex** [comment]
Preview3 landed but the name hasn't changed yet. I'll keep an :eye: on it.

capture

**Comment by guardrex** [comment]
@Rick-Anderson @pakrym Going by what I'm seeing in the portal, this looks like it will be a 3.0 update. Let's version this and get it merged. I can strip the old bit out after I see that it's disappeared in the portal later :point_right: [Strip logging extension versioned content (aspnet/Docs \#11658)](https://github.com/aspnet/Docs/issues/11658).

**Pull request merged**
