### PR TITLE
Cosmetic changes for multiple files

### LINKED ISSUE #7252: Redundant usings?
Is there a reason the generated files reference both `using RazorPagesMovie.Models;` and `private readonly RazorPagesMovie.Models.RazorPagesMovieContext _context;`? 

Wouldn't it only need `private readonly RazorPagesMovieContext _context;`? 

It doesn't look like it's confusing Visual Studio, so it may not be important for anything more than showing multiple ways of utilizing namespaces, I guess...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by daveabrock**
As I was preparing to rewrite a Razor Pages topic, I came across some minor cosmetic things while running through the Razor Pages tutorial. Since they were a bunch of little things, I thought I would group it into one request. As I'm fairly new at this, if you would like me to do it a different way in the future, just let me know.

Changes of note (all others were cosmetic and not worth discussing):
* `aspnetcore/includes/RP/razor-pages-start.md`: Moved description of `_ViewStart.cshtml` after `_ViewImports.cshtml` because that is how it is displayed in Visual Studio. Also added a short description of the `Privacy` page.
* `aspnetcore/tutorials/razor-pages/model/_static/conan.png`: Updated screenshot to contain `ReleaseDate` label and not `Release Date.` The display annotation is not discussed until later in the tutorial.
* `...als/razor-pages/razor-pages-start/sample/RazorPagesMovie21/Data/RazorPagesMovieContext.cs`: Removed unused usings and also removed the unnecessary FQNs. Same for the other code samples in this pull request.

Fixes #7252

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@daveabrock looks good. A couple minor changes in my commits.

**Comment by daveabrock** [comment]
I see you pushed to my branch (thank you). Do you need anything else from me on this one?

**Comment by Rick-Anderson** [comment]
@daveabrock 	thanks. NIce work.

**Comment by Rick-Anderson** [comment]
@daveabrock 	it's more efficient to make changes than to request changes.

**Comment by daveabrock** [comment]
Completely agree - thanks!

**Pull request merged**
