### PR TITLE
Added Sample VS Project.  Updated AnchorTagHelper.md to include refer…

### PR DESCRIPTION
**Pull request by pkellner**
…ence to SpeakerController.cs.  Improved AnchorTagHelper.md documentation to be more consistent per docs guide.

### CODE REVIEW

**Comment by pkellner** [comment]
@Rick-Anderson as you suggested, I believe I've created a clean fork, updated it with the sample data and also worked on AnchorTagHelper.md to include the SpeakerController.cs file from samples directory (which I also added)

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/global.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/global.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Controllers/HomeController.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Controllers/HomeController.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/AboutBlog.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/AboutBlog.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/Index.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/Index.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/BuiltInTag.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/BuiltInTag.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/HomeController.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/HomeController.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/SpeakerController.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/SpeakerController.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/PrettyTagHelperTagHelper.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/PrettyTagHelperTagHelper.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Program.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Program.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Startup.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Startup.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/TagHelpersBuiltInAspNetCore.xproj](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/TagHelpersBuiltInAspNetCore.xproj) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/BuiltInTag/AnchorTagHelper.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/BuiltInTag/AnchorTagHelper.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/About.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/About.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Contact.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Contact.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Index.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Index.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/Error.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/Error.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/_Layout.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/_Layout.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Detail.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Detail.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Evaluations.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Evaluations.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Index.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Index.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewImports.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewImports.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewStart.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewStart.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/appsettings.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/appsettings.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bower.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bower.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bundleconfig.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bundleconfig.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/project.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/project.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/web.config](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/web.config) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C30%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611300608422301-2272%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by pkellner** [comment]
Just checking back here to see if @Rick-Anderson is waiting on anything from me.

**Comment by Rick-Anderson** [comment]
@pkellner  nope, just trying to catch up. Hopefully I can work on this next week.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/global.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/global.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Controllers/HomeController.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Controllers/HomeController.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/AboutBlog.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/AboutBlog.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/Index.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Areas/Blogs/Views/Home/Index.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/BuiltInTag.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/BuiltInTag.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/HomeController.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/HomeController.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/SpeakerController.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Controllers/SpeakerController.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/PrettyTagHelperTagHelper.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/PrettyTagHelperTagHelper.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Program.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Program.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Startup.cs](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Startup.cs) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/TagHelpersBuiltInAspNetCore.xproj](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/TagHelpersBuiltInAspNetCore.xproj) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/BuiltInTag/AnchorTagHelper.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/BuiltInTag/AnchorTagHelper.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/About.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/About.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Contact.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Contact.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Index.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Home/Index.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/Error.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/Error.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/_Layout.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Shared/_Layout.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Detail.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Detail.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Evaluations.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Evaluations.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Index.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/Speaker/Index.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewImports.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewImports.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewStart.cshtml](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/Views/_ViewStart.cshtml) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/appsettings.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/appsettings.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bower.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bower.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bundleconfig.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/bundleconfig.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/project.json](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/project.json) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/web.config](https://github.com/pkellner/Docs/blob/pkellner-builtIn-TH/aspnetcore/mvc/views/tag-helpers/builtin/sample/TagHelpersBuiltInAspNetCore/src/TagHelpersBuiltInAspNetCore/web.config) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C7%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612070302107484-2272%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by pkellner** [comment]
Hi @Rick-Anderson Hoping to get started soon on the other built in tag helpers but don't want to put to much work in if my first one needs a lot of work.  Just a little "nudge". No emergency.

**Comment by pkellner** [comment]
Any update here? I'm hoping to work on this over the holidays, airplanes, etc and a first review of the Anchor Tag Helper would be helpful. I assume @Rick-Anderson will be doing this?  true?

**Comment by pkellner** [comment]
Hi again @Rick-Anderson .  Just checking back.  I've not heard anything since thanksgiving.  Are you still planning on reviewing this? I've started working on some other built in tag helpers but don't want to get to far out of sync until you've had a chance to review this. Please let me know.

**Comment by Rick-Anderson** [comment]
@pkellner  I'll take a look next week.

**Comment by pkellner** [comment]
Hi @Rick-Anderson   I'm not quite following what you did and what my next steps are.  Did you approve the tag helper I wrote up and the intro page?  I assume we are going to keep the pkellner-builtin-TH branch until I've done all the tag helpers, and then merge it into production.  Please explain the plan.

**Comment by pkellner** [comment]
@Rick-Anderson My understanding for how this will work is that we will keep the pkellner-builtin-TH tag helper branch until all tag helpers are completed and then that branch, once all approved will be moved into production. I'm understading the comment "the pkellner-builtin-th branch can be safely deleted".

**Pull request merged**
