### PR TITLE
Support .NET API xref links in ASP.NET Core docs

### PR DESCRIPTION
**Pull request by scottaddie**
Fixes https://github.com/aspnet/Docs/issues/7064

Modified 1 doc to demonstrate the new syntax. See http://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-services for more context around the *docfx.json* file change.

[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/?branch=pr-en-us-8112&view=aspnetcore-2.1#additional-resources)

/cc: @mairaw I took a different approach than how it's done in the dotnet/docs repo. Copying you in case you're interested in this solution.

### CODE REVIEW

**Comment by mairaw** [comment]
Interesting, thanks for including me. I wasn’t familiar with the advanced options.

**Comment by scottaddie** [comment]
@guardrex @tdykstra This change may interest you too. Once merged, it allows us to replace /dotnet/api link with xref links. One benefit is that API ref links will be validated during the build.

**Comment by guardrex** [comment]
What would the difference be if the asterisk isn't included? It seems like (*wildly guessing*, of course) that it would also assume no particular overload as well ... at least for the link URL. Is it used for the link text somehow? The broader question is: Are we always going to use the asterisk for API refs that don't point to an overload?

Also ... and perhaps this is more of a @Rick-Anderson decision ... are going to use the `text` param? ... what's the repo-wide convention going to be going forward?

**Comment by Rick-Anderson** [comment]
@scottaddie  are these case sensitive? Could you have replaced `(/dotnet/api/` with `<xref:` ?
How are you looking up the new references?

**Comment by scottaddie** [comment]
@Rick-Anderson The API names are case sensitive. For example, the following wouldn't work: `<xref:microsoft.aspnetcore.mvc.fromformattribute>`. The following does work: `<xref:Microsoft.AspNetCore.Mvc.FromFormAttribute>`. The uid that follows `<xref:` is found by locating the value of the `ms.assetid` meta tag on the API ref page. For example, go [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fromformattribute?view=aspnetcore-2.1) and view the page source. You'll find the following `meta` tag: `<meta name="ms.assetid" content="Microsoft.AspNetCore.Mvc.FromFormAttribute" />`.

**Comment by Rick-Anderson** [comment]
@scottaddie  that's alot of work. Hopefully they'll get a tool like we had in DxStudio to supply the uid.

**Comment by scottaddie** [comment]
@Rick-Anderson It is a fair amount of work. I figure we'll just update the links as we encounter them. The existing links will continue to work.

**Comment by guardrex** [comment]
I hope this works out. **_API Link Hell_** is no place I'd like to return to.

**Comment by guardrex** [comment]
*Arrrrrrgh* ...

```
<meta name="ms.assetid" content="Microsoft.AspNetCore.WebHost.CreateDefaultBuilder*" />
```

... and ...

```
[WebHost.CreateDefaultBuilder](xref:Microsoft.AspNetCore.WebHost.CreateDefaultBuilder*)
```

... produces ...

capture

**Pull request merged**
