### PR TITLE
Azure App Service Authentication (Easy Auth) #4095

### PR DESCRIPTION
**Pull request by isaac2004**
Added Link to Core Authentication Index with link for Easy Auth steps per #4095

### CODE REVIEW

**Comment by isaac2004** [comment]
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@isaac2004  [review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/?branch=pr-en-us-4501) that link doesn't work. I didn't know we could use `~` relative links

**Comment by Rick-Anderson** [comment]
We're in a different repo so you need to use https://docs.microsoft.com/azure/app-service/app-service-authentication-overview

**Comment by isaac2004** [comment]
@Rick-Anderson sorry about that, fixed

**Comment by Rick-Anderson** [comment]
@isaac2004  Thanks!

**Pull request merged**
