### PR TITLE
Fix issue which rose when rendering index

### PR DESCRIPTION
**Pull request by ganesanarun**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@joeaudette  please review.

**Comment by joeaudette** [comment]
this looks ok to me but depends on intention of what we want to show. In a real app this change would be correct to hide the Edit link from users who cannot edit as has been done in this change. 

But in a tutorial app it might be nice to show the link and then when clicked get denied edit access, after all hiding a link is just cosmetic, by leaving the link we show that the user is not able to edit for real.

I'm ok with this change, but I did think of that when implementing it and had decided to leave the edit link visible for this reason. But I defer back to you @RickAndMSFT on a decision for it.

**Comment by Rick-Anderson** [comment]
@ganesanarun  can you comment out the auth check - something like:

```
    @* Uncomment to perform authorization check. A real app would hide the edit link from users
        uses who don't have edit access. A user without edit access can click the link but will get denied 
        access in the controller.
        @if (await AuthorizationService.AuthorizeAsync(User, Model, ContactOperations.Approve))
    {*@
``

**Comment by ganesanarun** [comment]
@Rick-Anderson @joeaudette Thank you both. I just commented out the cosmetic. But I still believe that it's not cosmetic as we should let user know as they should, though we have protection at API layer.

**Comment by Rick-Anderson** [comment]
@ganesanarun  thanks!

**Pull request merged**
