### PR TITLE
 Mock service injection for integration tests topic 

### LINKED ISSUE #7153: How to inject mock services during integration testing
I can't find where I read this, but I was under the impression that the new ASP.NET Core integration testing mechanism would facilitate injecting mock services by allowing one to replace or overwrite the service registrations in the startup class. Is something along these lines a supported scenario? I am unable to determine from the [integration tests docs](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests) whether something like this is somehow possible, whether by overriding ConfigureWebHost, or within WithWebHostBuilder. Honestly, not entirely clear what the benefits of using WebApplicationFactory over TestHost are? Plus, unable to locate the docs describing how to use TestHost for integration testing so... any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #7153 

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1&branch=pr-en-us-7511#inject-mock-services)

* Adds content to the topic to cover injection of mock services with `ConfigureTestServices`.
* Adds an example of injecting a simple mocked service into the sample app.

cc/ @lambdakris You won't be able to see the internally-built doc; but if you flip over to the diff, you'll see the enhancement. I think this would have been enough to show you the way to go, but let me know if not.

### CODE REVIEW

**Comment by scottaddie** [comment]
@guardrex The snippet displays correctly in the preview page. Try upgrading to the latest version of DocFX, if you haven't already.

**Comment by guardrex** [comment]
I did. No 🎲🎲.

**Comment by Rick-Anderson** [comment]
@javiercn  please review

**Comment by guardrex** [comment]
@javiercn If you're out/busy right now, can you suggest someone who can review?

**Comment by guardrex** [comment]
@Rick-Anderson I updated the versions. I reviewed the text updates ... look'in good :+1:, and I checked the sample again ...

```
Total tests: 14. Passed: 14. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 8.7050 Seconds
```

Shall we go ahead and merge?

**Pull request merged**
