### PR TITLE
Update Web API 2 migration doc to RC1

### PR DESCRIPTION
**Pull request by scottaddie**
This PR addresses issue https://github.com/aspnet/Docs/issues/922 by updating the doc and its sample project to RC1. I saw that the `project.lock.json` file was already checked in, so I continued down that path. Please let me know if you don't want this file checked in.

### CODE REVIEW

**Comment by danroth27** [comment]
@Rick-Anderson @Erikre @rachelappel Please review

**Comment by rachelappel** [comment]
::shipit::

**Comment by Rick-Anderson** [comment]
Looks good :shipit:  @rachelappel  can you merge?

**Comment by rachelappel** [comment]
Merged de407583f2f1a3b0172aeeddc6e6a184005ea50d

**Pull request merged**
