### PR TITLE
Update adding-model.rst

### PR DESCRIPTION
**Pull request by andrewplummerNZ**
Added full steps for adding movies.cs
Added build project shortcut key CTRL+SHIFT+B
Added note that describes what to do if dnu restore fails (I noticed in my environment dnu command wasn't recognized)
Fixed typo Views:: to Views:
Fixed typo MoviesController.c to MoviesController.cs
Added Note to explain if Post fails due to ModelState error. I noticed in my timezone the date used in example failed to post due to format, e.g. my timezone dd/mm/yyyy, example was in mm/dd/yyyy format. It seems by default the scaffolded view doesn't return any validation error for the ReleaseDate,

### CODE REVIEW

**Comment by danroth27** [comment]
@andrewplummerNZ Looks like you have a build issue:

```
/home/travis/build/aspnet/Docs/aspnet/tutorials/first-mvc-app/adding-model.rst:14: ERROR: Unexpected indentation. 
```

**Comment by danroth27** [comment]
@Rick-Anderson Please review

**Comment by andrewplummerNZ** [comment]
I cleaned up one obvious indenting mistake, not sure how to re-check the build though. Haven't used Git Hub before. Sorry for the hassle!

**Comment by Rick-Anderson** [comment]
@andrewplummerNZ  looks like the same problem on or near line 14
/home/travis/build/aspnet/Docs/aspnet/tutorials/first-mvc-app/adding-model.rst:14: ERROR: Unexpected indentation.

**Pull request closed without merging**
