### PR TITLE
Update 502.5 Common Errors and VC++ redist information

### LINKED ISSUE #2858: Call out local testing on 502.5 exceptions in IIS troubleshooting
Talking to @conkman on Slack ...

We speak to running an app locally in the lead-in to the *Common Errors* section; however, that can get lost in the mix when trying to tease out why a 502.5 is occurring on the server.

I'd like to add a bullet point to the 502.5 errors in the list that explicitly calls attention to checking the app locally (it should be the first bullet in each list imo). When it crashes locally, the dev should look within the app (at least initially) for their process crashing problem. It's when it runs locally but 502.5's on the server that they can consider the other errors we show as the possible culprit.

@Rick-Anderson @tdykstra Ok to put that PR this afternoon??? lol ... They told me not to do a damn thing until Monday. lol

Thanks to @conkman for flagging this problem.

### PR DESCRIPTION
**Pull request by GuardRex**
Fixes #2858 

Adds a blurb to 502.5 errors in the *Common Errors* section calling out first that the dev should run the app locally to make sure that the process failure in IIS isn't actually caused by a problem within the app itself.

Add a line to help ward off the missing VC++ redist for servers that are offline.

Also modifies the name from *Microsoft Visual C++ 2015 Redistributable (x64)* to *Microsoft Visual C++ 2015 Redistributable*.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@GuardRex  is this ready for review/merge?

**Comment by GuardRex** [comment]
@Rick-Anderson Yes, Sir. It's ready for a :eye: look see and "mergeola:tm:."

**Comment by Rick-Anderson** [comment]
@GuardRex  we're using xref:UID in lieu of relative links; looks good.

**Comment by GuardRex** [comment]
I know. This doc needs another one of my *treatments*. I only touched it for the one thing here. I'd like to come back later and do a number on it.

**Comment by GuardRex** [comment]
@Rick-Anderson I fixed the little merge conflict.

Is it ok if I come back to the doc in a few days and do *The Full Monty* on a new PR? I'll fix those `xref` probs and anything else I find.

**Comment by Rick-Anderson** [comment]
@GuardRex  no hurry.

**Comment by GuardRex** [comment]
@Rick-Anderson Ok, in that case, this one is ready for review/merge.

**Pull request merged**
