### PR TITLE
Tag helper built in examples proposal

### PR DESCRIPTION
**Pull request by pkellner**
Note To: @Rick-Anderson : I believe I've reverted correctly the update to _ViewsImportant.cshtml that includes the "It is important to.." comment.

This contains my proposed pull request for built in tag helpers.  I'm proposing it go to master I believe but I think it should go to a non-master branch if accepted so that when ready, that branch can be merged into master. Otherwise, I think I will be creating bigger and bigger pull requests which will be harder to manage.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/mvc/views/razor/_static/Thumbs.db](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/razor/_static/Thumbs.db) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllers.png](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllers.png) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllersArea.png](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllersArea.png) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/Thumbs.db](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/Thumbs.db) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/index.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C23%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611231945383821-2238%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by pkellner** [comment]
@Rick-Anderson I'm guessing the conflict has to do with my "It is important.." pull request. I don't know how to fix that. Please suggest.

Also, is there some way in the github dashboard view of my forked repo that I can bring my forked repo up to the current version of the main repo?  That is, now can I get https://github.com/pkellner/Docs  to be the same as https://github.com/aspnet/Docs .  If we do the feature branch for me for my built in tag helpers, will it be hard to keep that in sync with the rest of the docs?

**Comment by Rick-Anderson** [comment]
@pkellner  no, this looks better. The merge conflict is from a couple PR's we made (that touched every file) after you created your branch.  We can help with the merge conflict. Is this ready for me to review?

Take a look at the files changed link. You just need to remove aspnetcore/mvc/views/razor/_static/Thumbs.db from the PR. Delete that file and push another commit.

Looks like this PR is two MD files and associated images/TOC entries.

**Comment by pkellner** [comment]
closing and creating another without thumbs.db

**Comment by Rick-Anderson** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/mvc/views/razor/_static/Thumbs.db](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/razor/_static/Thumbs.db) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllers.png](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllers.png) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllersArea.png](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllersArea.png) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/Thumbs.db](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/Thumbs.db) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/index.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C23%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611232034151326-2238%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@pkellner  no need to close. Just delete the thumbs.md and push a commit. I can help if needed.

**Comment by Rick-Anderson** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/mvc/views/razor/_static/Thumbs.db](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/razor/_static/Thumbs.db) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllers.png](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllers.png) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllersArea.png](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/_static/ProjectControllersArea.png) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/builtin/resources/AnchorTagHelper.md) | :white_check_mark:Succeeded | |
[aspnetcore/mvc/views/tag-helpers/index.md](https://github.com/pkellner/Docs/blob/TagHelperBuiltInExamplesProposal/aspnetcore/mvc/views/tag-helpers/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C23%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611232034238128-2238%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@pkellner  I might be able to delete it from the browser.

**Comment by Rick-Anderson** [comment]
@pkellner don't worry about deleting thumbs.db - are you ready for me to review the PR?

**Comment by pkellner** [comment]
@Rick-Anderson I think where my problem is I'm doing my updates on my local branch TagHelperBuiltInExamplesProposal and did not revert the master branch. I'm looking into that now.

**Comment by Rick-Anderson** [comment]
@pkellner  send me an email Rick.Anderson[at]microsoft.com 

I'd fix it like this:

Create a new branch
Copy your changes to the new branch
PR

**Comment by pkellner** [comment]
@Rick-Anderson  A new branch beyone my TagHelperBuiltInExamplesProposal branch? I've got the "It's important to understand" no reverted from both my new TagHelperBuiltInExamplesProposal branch as well as my master branch.  It seems my only choice is to create a pull request against your master branch.  Is that what you want me to do? (sorry for all the confusion, I'll get better at this)

**Comment by Rick-Anderson** [comment]
@pkellner  this PR is fine, why don't we just work with this? We'll fix the merge conflict when we're ready to merge. Can I start reviewing these two articles?

**Comment by pkellner** [comment]
Yes, so you have everything you need then now?  I'm almost heading out on the road now.

**Comment by Rick-Anderson** [comment]
@pkellner  Yes, I'll start reviewing now but probably won't finish until next week. Have a great weekend.

**Comment by pkellner** [comment]
@Rick-Anderson No hurry. Please don't hold back on suggestions and criticisms.  I've got thick skin and want it to be as good as I can make it.  Happy turkey day and thanks for the help.

**Comment by pkellner** [comment]
Hi @Rick-Anderson , just checking to make sure you are not waiting for anything from me. I'm ready to start generating the other tac helper docs as soon as I can but want to get your feedback on the first one before doing the other ones.

**Pull request closed without merging**
