### PR TITLE
Updating Identity

### LINKED ISSUE #1472: "Introduction to Identity" security/authentication/identity
- [ ] Update for RTM 
- [ ] #1465
- [ ] #1462
- [ ] #1405

### PR DESCRIPTION
**Pull request by ardalis**
Fixes #1472 

and several related issues: 
1462, 1465

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@ardalis  red box around change auth in  aspnetcore/security/authentication/identity/_static/01-mvc.png

**Comment by Rick-Anderson** [comment]
At the right place add see account conf on how to config to prevent login at reg
https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?branch=pr-en-us-3652#prevent-login-at-registration

**Comment by Rick-Anderson** [comment]
@ardalis  It looks like it wasn't a fluke. Do you want to revert my commit or would it be easier to fix up what you have? BTW, when you're happy with my PR, feel free to merge.

**Comment by ardalis** [comment]
@Rick-Anderson I'll fix it.

**Comment by ardalis** [comment]
@Rick-Anderson should be good to go now

**Pull request merged**
