### PR TITLE
Add EF Core Migrations foreign keys configuration

### PR DESCRIPTION
**Pull request by scottaddie**
[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/migration/1x-to-2x/identity-2x?branch=pr-en-us-4068)

Add the missing foreign key configuration code to the 2.0 auth migration doc.

### CODE REVIEW

**Comment by scottaddie** [comment]
@HaoK The following 2 configurations for the `IdentityRole` class were intentionally excluded from this PR:

```csharp
builder.Entity<Role>()
    .HasMany(e => e.Claims)
    .WithOne()
    .HasForeignKey(e => e.RoleId)
    .IsRequired()
    .OnDelete(DeleteBehavior.Cascade);

builder.Entity<Role>()
    .HasMany(e => e.Users)
    .WithOne()
    .HasForeignKey(e => e.RoleId)
    .IsRequired()
    .OnDelete(DeleteBehavior.Cascade);
```

Should this doc mention adding the following navigation properties to the `IdentityRole` class? If so, then I think it makes sense to include the code above.

```csharp
public virtual ICollection<UserRole> Users { get; } = new List<UserRole>();
public virtual ICollection<RoleClaim> Claims { get; } = new List<RoleClaim>();
```

**Comment by HaoK** [comment]
@ajcvickers @bricelam @divega can you guys double check if this is the expected behavior:

So I simulated the addition of navigation properties in the following steps:

1. Start a new 2.0 app, delete the initial migration
2. I changed the default pocos that identity uses, to use a different base type:
`ApplicationUser` and `ApplicationRole` both derive from `IdentityUser/Role<int>` which changes the primary key from string to int.
3. I generated a new initial migration via powershell.
4. I ran the app, tried to login, it prompts to apply the new initial migration, I click the button, create a user, and login.
5. I add the navigation properties, and apply the Migrations in the doc:

```
    public class ApplicationUser : IdentityUser<int>
    {
        public virtual ICollection<IdentityUserRole<int>> Roles { get; set; }
        public virtual ICollection<IdentityUserClaim<int>> Claims { get; set; }
        public virtual ICollection<IdentityUserLogin<int>> Logins { get; set; }

    }

    public class ApplicationRole : IdentityRole<int>
    {
        public virtual ICollection<IdentityRoleClaim<int>> Claims { get; set; }
    }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);

            builder.Entity<ApplicationUser>()
                .HasMany(e => e.Claims)
                .WithOne()
                .HasForeignKey(e => e.UserId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Cascade);

            builder.Entity<ApplicationUser>()
                .HasMany(e => e.Logins)
                .WithOne()
                .HasForeignKey(e => e.UserId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Cascade);

            builder.Entity<ApplicationUser>()
                .HasMany(e => e.Roles)
                .WithOne()
                .HasForeignKey(e => e.UserId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Cascade);

            builder.Entity<ApplicationRole>()
                .HasMany(e => e.Claims)
                .WithOne()
                .HasForeignKey(e => e.RoleId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Cascade);

        }

```

6. I rerun Add-Migration addNav, this generates an empty migration...

Am I doing something wrong in the steps I did to simulate the migrations?

**Comment by ajcvickers** [comment]
@HaoK Based on those steps I would expect no schema changes, which would be why the second migration is empty.

**Comment by HaoK** [comment]
Okay, but we still need this added to the migration doc since this would be needed for existing 1.x database schemes?  I was just trying to verify that this fixes things (and failing it appears :/)

**Comment by HaoK** [comment]
@scottaddie I think we should update the docs to use concrete types like I did in my example, instead of TUser and User/Role...

Use a concrete example generic base types like `IdentityUserClaim<int>`, and ApplicationUser/ApplicationRole instead of TUserClaim/User/Role since these should more closely match what people might have.

**Comment by scottaddie** [comment]
@HaoK I've updated the types in the code snippets. Let me know when you get an answer from @ajcvickers as to whether this should be included in the doc.

**Comment by HaoK** [comment]
Looks good to me, @ajcvickers can you take a look as well?

**Pull request merged**
