### PR TITLE
2.0 updates to Policy Authorization doc

### LINKED ISSUE #4850: 2.0 updates to Policy Authorization doc
https://docs.microsoft.com/aspnet/core/security/authorization/policies

- [x] Address Livefyre comment from "Geoffrey_Braaf"
- [x] UE edit
- [x] Add sample app
- [x] Address "Content-Incomplete" verbatim
- [x] Clarify when to use `Task.FromResult(0)`

### PR DESCRIPTION
**Pull request by scottaddie**
Fixes #4850 

[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/security/authorization/policies?branch=pr-en-us-4849)

### CODE REVIEW

**Comment by scottaddie** [comment]
@HaoK Please review.

**Comment by Rick-Anderson** [comment]
@HaoK Please review.

**Comment by HaoK** [comment]
Sorry for the delay, was in oahu on vacation last week... I'll take a look now

**Comment by HaoK** [comment]
While we are making changes here, there's a line in this doc that is very wrong:

"Handlers inherit AuthorizationHandler<T>, where T is the requirement to be handled."

This should instead be something like "Handlers must implement IAuthorizationHandler, there are helper AuthenticationHandler<T> and <T, R> base classes where T is the requirement to be handled and R is the resource being authorized which might be helpful when you wish to only handle a specific requirement or resource type.  Implementing the interface explicitly is more appropriate when handling multiple requirements or resources."

**Comment by HaoK** [comment]
We should also mention a new flag to 2.0 called: InvokeHandlersAfterFailure which tweaks the behavior in the "What should a handler return?" section.

Namely this will short circuit handlers as soon as fail is called instead of invoking them all, giving apps who want this behavior to opt in.

**Comment by HaoK** [comment]
I think it might also be worth adding the following example we were discussing in an issue this week: https://github.com/aspnet/Security/issues/564#issuecomment-351500571

into the OR section as an example of when to implement the handler directly:

Pulling over the relevant info:

Lets say you have Read/Edit/Delete operations, and Owners can do everything, but sponsers can only read.
```
   ReadPermission : IAuthorizationRequirement
   EditPermission : IAuthorizationRequirement
   DeletePermission : IAuthorizationRequirement
```

You can have a single handler:
```C#
   public class PermissionHandler : IAuthorizationHandler {
      public Task HandleAsync(AuthorizationHandlerContext context) {
           foreach (var req in context.PendingRequirements) 
               if (req is ReadPermission)
                   if (IsOwner(context.User, context.Resource) || IsSponser(context.user. context.Resource) 
                      context.Succeed(req)
               else if (req is EditPermission || req is DeletePermission) 
                   if (IsOwner(context.User, context.Resource)) 
                      context.Succeed(req)
      }
   }
```

**Comment by HaoK** [comment]
@blowdart does that look reasonable to you (the new OR example with single handler/permissions etc)  we get asked this a lot, might as well put it in the docs so people can see how we expect them to do it

**Comment by blowdart** [comment]
LGTM

**Comment by scottaddie** [comment]
@HaoK Thanks for reviewing. I hope you enjoyed your vacation. I'll merge this as is and address your suggestions in a separate PR.

**Pull request merged**
