### PR TITLE
Update Startup.cs

### PR DESCRIPTION
**Pull request by phikret**
This works in Core 2.0. Consider changing the sample code accordingly since it is misleading and discouraging to follow the tutorial with non-working examples.

### CODE REVIEW

**Comment by scottaddie** [comment]
@HaoK Please review the proposed changes to the ASP.NET Core 2.0 sample app.

**Comment by HaoK** [comment]
Nope, if this is the identity sample the current code is correct, the changes would target the default cookie name and not the identity application cookie

**Comment by HaoK** [comment]
We shouldn't take this change.

**Comment by phikret** [comment]
Thank you for your time, but is anyone going to update the sample (in any other, right way), so that it can be used by people that follows the tutorial. The current sample (stressing this again), simply does not work. You can check.

**Comment by scottaddie** [comment]
@phikret I'll take a look at it.

**Pull request closed without merging**
