### PR TITLE
Update config Identity to 2.1

### LINKED ISSUE #6386: Update Configure ASP.NET Core Identity for 2.1
When you use VS 15.7.1 and create a new Web Application MVC project using Core 2.1, Individual User Accounts - Store account in-app it does not create the ApplicationUser.cs classs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3ac09f0-74ca-1a5d-4fec-695b84c1ac95
* Version Independent ID: cd2c1f5e-e4f0-d2c3-4737-8ff4f0c176c2
* Content: [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-configuration.md)
* Service: **asp.net-core**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #6386 
[Internal review url](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&branch=pr-en-us-8033&tabs=aspnetcore2x)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@HaoK  only major change here is in [Lockout](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x#lockout)

Can you compare  current doc [Lockout](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x#lockout) to the [updated lockout](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&branch=pr-en-us-8033&tabs=aspnetcore2x#lockout)

**Comment by Rick-Anderson** [comment]
@HaoK  I'm setting `options.LoginPath` **after** calling `AddDefaultIdentity` per https://github.com/aspnet/Identity/issues/1414 - but no matter what I set it to, it uses  `"/Identity/Account/Login"`

```
services.ConfigureApplicationCookie(options =>
{
    options.AccessDeniedPath = "/About";
    options.LoginPath = "/About";
});
```

**Comment by Rick-Anderson** [comment]
@HaoK  no need to review entire doc or all changes, just those called out in my comments above. Once you're finished I'll  have `@scottaddie`  review the PR.

**Comment by Rick-Anderson** [comment]
@HaoK  quick review please.

**Comment by HaoK** [comment]
Looks fine, @blowdart seem fine to you?  Note the UI flipped lockout to true by default, which maybe is not something we wanted to do...

**Comment by Rick-Anderson** [comment]
@HaoK  couple of questions
@HaoK  I'm setting `options.LoginPath` **after** calling `AddDefaultIdentity` per https://github.com/aspnet/Identity/issues/1414 - but no matter what I set it to, it uses  `"/Identity/Account/Login"`

```
services.ConfigureApplicationCookie(options =>
{
    options.AccessDeniedPath = "/About";
    options.LoginPath = "/About";
});
```
What's the right way to do that?

Also, per [this issue](https://github.com/aspnet/Identity/issues/1414#issuecomment-382718965) I added:

`IdentityOptions` must be set **after** calling `AddIdentity` or `AddDefaultIdentity`.

Is the preceding change correct?

**Comment by wutever0** [comment]
Hi.. I don't know if this is the write place to mention this but I am also having this issue of  

> no matter what I set it to, it uses "/Identity/Account/Login"

Talking here about ConfigureApplicationCookie(o => { o.LoginPath });
I have also placed it **after** calling AddDefaultIdentity and still no dice.

**Pull request merged**
