### PR TITLE
Update .openpublishing.publish.config.json

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Internal issue link](https://ceapex.visualstudio.com/Engineering/_workitems/edit/46881?src=WorkItemMention&src-action=artifact_link)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@cillroy please review addition of 
`"treat_warning_as_error": true,`

I want this as soon as it's available.
cc @tdykstra 	@scottaddie

**Comment by Rick-Anderson** [comment]
@cillroy 	this causes the following error:

image

**Comment by cillroy** [comment]
oh it is not published live yet - I just wanted to see your thoughts around the wording for feature

**Comment by Rick-Anderson** [comment]
@cillroy 	can't wait to get it. I like the wording.

**Pull request closed without merging**
