### PR TITLE
English to Korean translation draft

### PR DESCRIPTION
**Pull request by songgun**
English to Korean translation draft

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@songgun  Thanks for your effort. We're having all our docs machine translated. Once that happens you can submit a PR on the translated doc.

**Comment by Rick-Anderson** [comment]
@songgun  thanks again for your interest. Once we have localized content, you'll submit PRs to https://github.com/aspnet/docs.ko-kr, not the ENU repo. We hope to have the .ko-rk repo working in about a month.

**Comment by songgun** [comment]
@Rick-Anderson Thank you for your reply. I will wait.

**Comment by Rick-Anderson** [comment]
@songgun  subscribe to #3188 to get notified.

**Pull request closed without merging**
