### PR TITLE
Wrong task referenced in CopyAllFiles

### PR DESCRIPTION
**Pull request by Thieum**

### CODE REVIEW

**Comment by scottaddie** [comment]
@sayedihashimi Please review.

**Comment by sayedihashimi** [comment]
@vijayrkn this is a one line change, looks good to me. Just wanted to double check with you.

**Comment by vijayrkn** [comment]
looks good.

**Comment by scottaddie** [comment]
@Thieum Thank you for the fix, and congrats on your 1st docs contribution!

@sayedihashimi @vijayrkn Thank you for reviewing!

**Pull request merged**
