### PR TITLE
Corrected broken URLs to point to updated content.

### PR DESCRIPTION
**Pull request by ameyer117**
The "Start Free Trial" and "Subscribe Now" links pointed to a 404 page at Pluralsight. I have updated the URLs with destinations that make sense to the average user. The free trial URL remains focused on Scott Allen's ASP.NET MVC 5 course for promotional purposes.

**If Microsoft has updated affiliated links, that might be a better option for the future.**

### CODE REVIEW

**Comment by ameyer117** [comment]
The "free" part was there before I even started. :)  Maybe you would want to edit/remove the word "Free" 
As for the other link - I'm simply just linking them to their default pricing page as you suggested?

**Comment by guardrex** [comment]
> The "free" part was there before I even started. 

Yes, that's why I said "pre-existing" in my remarks.

*Yes!* on the link ... I agree with you that that's the best place to send cats.

The inclusion of pricing info and "free" language is an editorial decision for @Rick-Anderson and @scottaddie to work out. Our guidelines dissuade the practice. I'm just a little worker 🐝 around here, so I'm just making a passing suggestion on it. They'll let you know if they want to make changes to that content.

**Comment by ameyer117** [comment]
All good. Sorry missed the pre-existing part. Not a very good excuse on my part, but I was reading your reply on my phone while waiting for coffee! lol

**Comment by Rick-Anderson** [comment]
> I recommend just linking to 3rd party product/service description/pricing pages and allowing the 3rd party to handle their pitch and pricing descriptions. 

+99 - Lets do that.

**Comment by guardrex** [comment]
@ameyer117 I've moved on from morning ☕️ to an afternoon 🍺. I'm sure the quality of my next two PR's will **go UP!** :smile:

**Comment by guardrex** [comment]
Thanks @ameyer117 ... I'll get this in as soon as the build completes.

**Pull request merged**
