### PR TITLE
add Azure publishing to publishing list

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@rachelappel  @tdykstra please review

**Comment by Rick-Anderson** [comment]
fixes https://github.com/aspnet/Docs/issues/1349

**Comment by tdykstra** [comment]
Placed this way it has Azure VM between two Web app entries; I'd keep Web app with VS and web app with CI/CD next to each other.

**Comment by Rick-Anderson** [comment]
@tdykstra  can you give me a ":shipit:"

**Comment by tdykstra** [comment]
:shipit:

**Comment by rachelappel** [comment]
Merged 4743f28cea58e1ee0ecc8dcacfcce54d7a429cfe

**Pull request closed without merging**
