### PR TITLE
erikre - Updating ASPNET 5 - First app topic

### PR DESCRIPTION
**Pull request by Erikre**

### CODE REVIEW

**Comment by Erikre** [comment]
Need shipit. I made a few updates to clarify tutorial process. Please review @Rick-Anderson, @rachelappel , or @danroth27.

**Comment by Rick-Anderson** [comment]
:shipit:

**Comment by Rick-Anderson** [comment]
@shirhatti or @rachelappel  can you merge this?

**Comment by rachelappel** [comment]
Merged b553fc40b31b485c165b2d44bd1c703ea546d607

**Pull request closed without merging**
