### PR TITLE
Pass Additional ViewData to a Strongly-Typed Partial View

### PR DESCRIPTION
**Pull request by MaherJendoubi**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@MaherJendoubi the article that uses the code you changes is importing code with the range tag.  You can usually find these errors by looking for range=9 or range=7
DocFX is usually better at pin pointing the error. See the validation report for more info.

**Comment by MaherJendoubi** [comment]
@Rick-Anderson Would you review it for me? Thanks.

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  Yes, I'll do it today.

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  Looks great, thanks!

**Pull request merged**
