### PR TITLE
Changed Web Api Help Pages using Swagger, added sub pages for NSwag & Swashbuckle

### PR DESCRIPTION
**Pull request by RSuter**
Fixes https://github.com/aspnet/Docs/issues/4258

[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?branch=pr-en-us-5622#get-started)

### CODE REVIEW

**Comment by scottaddie** [comment]
@RSuter Thank you for submitting this PR! Can you also please address the conflicts?

**Comment by Rick-Anderson** [comment]
@RSuter It might be easier to create a new PR and copy your files/folder over.

**Comment by zuckerthoben** [comment]
@RSuter Go ahead and do a clean PR.

**Comment by scottaddie** [comment]
@RSuter The sample code is needed, since snippets of it are imported into the docs. This is actually our preferred way of including code.

**Comment by scottaddie** [comment]
This looks great to me! I'll handle wiring it up in the TOC in a separate PR. Thank you very much to @RSuter and @zuckerthoben for all of your efforts.

**Comment by zuckerthoben** [comment]
Looks great! Thanks for the support @RSuter, @scottaddie and @Rick-Anderson

**Pull request merged**
