### PR TITLE
fixed few typos

### PR DESCRIPTION
**Pull request by crowchirp**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@crowchirp  thanks. Can you sign the cla?

**Comment by Rick-Anderson** [comment]
@crowchirp  what was the change to   an-overview-of-project-katana.md

**Comment by crowchirp** [comment]
Signed the CLA

**Comment by crowchirp** [comment]
@Rick-Anderson, it was 'composabity' changed to 'composability'. Rich diff will reveal that.

Thanks

**Comment by Rick-Anderson** [comment]
@crowchirp  Thanks for the tip of rich diff, that worked. Nice fixes but it's still complaining about the CLA.

**Comment by crowchirp** [comment]
@Rick-Anderson, don't know why it's so, have already been through the process
image

**Comment by crowchirp** [comment]
@Rick-Anderson , don't know why it is so, have already gone through the process
some

**Comment by Rick-Anderson** [comment]
@danroth27  who can we get help with this CLA problem? cc @spboyer @mairaw @tdykstra

**Comment by mairaw** [comment]
I've seen this happening with @bleroy in our repo too. /cc @richlander

**Comment by danroth27** [comment]
@jongalloway can you help out with the CLA here?

**Comment by Rick-Anderson** [comment]
@danroth27  @jongalloway  would it be OK to merge this given:

- If this was 11 different PRs he wouldn't need to sign 
- He has signed.
- He's just fixed spelling, no significant content was added
- He showed me the Rich diff trick

**Comment by tdykstra** [comment]
What's the Rich diff trick?


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by Rick-Anderson** [comment]
@danroth27 @jongalloway  can I merge this? See my reasoning above.

**Comment by jongalloway** [comment]
@Rick-Anderson Okay to merge based on your reasons above. I'll dig into CLA issue, but no reason to hold these spelling corrections up. Sorry I missed the notifications here!

Thanks for the contributions, @crowchirp, sorry it took so long!

**Pull request merged**
