### PR TITLE
Update version of libuv from 1.4.2 to 1.8.0

### PR DESCRIPTION
**Pull request by thaiphan**

### CODE REVIEW

**Comment by danroth27** [comment]
@halter73 Which version of libuv did we ship with in rc1?

**Comment by halter73** [comment]
I modified version of 1.7.5. You can see the actual commit we built libuv from here: https://github.com/libuv/libuv/commit/dfdecf000622ea4dc9eec24be8f0cae99c0469cd

This commit is now in 1.8.0.

**Comment by danroth27** [comment]
:shipit:

**Comment by shirhatti** [comment]
Thanks for the PR! Merged in 803e1fb68d6306fbb254d877428c20564c41f13e

**Pull request closed without merging**
