### PR TITLE
replace default Identity

### LINKED ISSUE #6990: how to plug-in identity without relying on the scaffolder.
Copy from https://github.com/aspnet/Identity/issues/1825

These are the important bits to know if you have scaffolded the code into your app and don't want to use default identity ~at all~ **UI**.

Configure MVC to authorize the Identity pages that require authorization:

```
services.AddMvc()
   .AddRazorPages(options =>
       {
           options.AllowAreas = true;
           options.Conventions.AuthorizeAreaFolder("Identity", "/Account/Manage");
           options.Conventions.AuthorizeAreaPage("Identity", "/Account/Logout");
      });
```
Configure the cookie to point to the identity pages paths
```
services.ConfigureNamedOptions<CookieAuthenticationOptions>(options =>
{
    options.LoginPath = $"/Identity/Account/Login";
    options.LogoutPath = $"/Identity/Account/Logout";
    options.AccessDeniedPath = $"/Identity/Account/AccessDenied";
});
```
Regarding the fact that we rely on the scaffolder in our docs, its totally fine. The alternative is to tell you to copy paste a bunch of code in the docs into your project which is inevitably going to go out of sync. The scaffolder is the source of truth.

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #6990 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&branch=pr-en-us-7036&tabs=visual-studio)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@javiercn  once we agree to the doc changes I'll add links to this section in the migration docs and other identity docs.

**Comment by javiercn** [comment]
I think it looks good.

**Comment by Rick-Anderson** [comment]
@javiercn  Isn't there a more elegant way to fix - Navigating to the /Identity/Account/Manage generates the following exception: see [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&branch=pr-en-us-7036&tabs=visual-studio)

image

**Comment by javiercn** [comment]
@Rick-Anderson I would not phrase it like that, but just say that you need to register your own IEmailSender implementation. With respect to that statement about GDPR I'm not sure what to say about that. I'll let @blowdart chip in

**Comment by blowdart** [comment]
I don't see why GDPR is mentioned here at all?

**Pull request merged**
