### PR TITLE
DataProtection: AspNet -> AspNetCore update for package names

### PR DESCRIPTION
**Pull request by cwe1ss**
* AspNetCore instead of AspNet in package names
* The Interfaces-library was renamed to Abstractions
* minor ASP.NET Core fix in text

### CODE REVIEW

**Comment by cwe1ss** [comment]
I just noticed that the package names are wrong almost everywhere. Might be better to reject this PR and do a repository-wide search&replace.

**Comment by Rick-Anderson** [comment]
@cwe1ss does this PR correct the package names in aspnet/security/data-protection/introduction.rst ? If so I'll accept and merge.

**Comment by cwe1ss** [comment]
As I've said, this is wrong in many more places. Just search for "Microsoft.AspNet." - I noticed this after I've created this PR. 

If you want, I can create a separate PR for this - i just wasn't sure if you were already working on this in some other branch because this whole AspNet -> AspNetCore thing was a quite big and obvious change

**Comment by Rick-Anderson** [comment]
@cwe1ss That would be great, create a separate PR.

**Comment by Rick-Anderson** [comment]
@cwe1ss >do a repository-wide search&replace.
we like to avoid doing that. We'll start marching through the articles.

**Comment by Rick-Anderson** [comment]
@cwe1ss  thanks. Merged

**Pull request closed without merging**
