### PR TITLE
replace platform handler with asp.net core

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@shirhatti please review. Note I can't add ref to asp.net core handler until the other PR is merged. Once that;s done I'll add that link.

**Comment by shirhatti** [comment]
This article needs to be updated. The directory structure has changed from rc1 -> rc2

**Comment by Rick-Anderson** [comment]
@shirhatti what needs to change?

**Comment by Rick-Anderson** [comment]
@shirhatti closing this PR @GuardRex  will do the PR.
see issue https://github.com/aspnet/Docs/issues/1305

**Pull request closed without merging**
