### PR TITLE
Fix wide table

### PR DESCRIPTION
**Pull request by GuardRex**
@Rick-Anderson 

The grid table rendered correctly here in Preview before I sent in the last PR, but that wasn't the way to go ... it rendered wide with scrollbars.

I'm implementing the "Simple Table" approach now. http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#simple-tables

Sorry for the prob ... This *should* work now.

### CODE REVIEW

**Comment by GuardRex** [comment]
Hold on a sec ... I'll fix that.

**Comment by GuardRex** [comment]
Ok ... Mr. Travis seems to like that version.

**Comment by GuardRex** [comment]
Note tho that if this one doesn't render correctly, then I'll probably need help with this pesky (long) table.

**Comment by Rick-Anderson** [comment]
moved to #1522

**Pull request closed without merging**
