### PR TITLE
Fix broken Environment Tag Helper link

### PR DESCRIPTION
**Pull request by scottaddie**
The "Environment Tag Helper" link was broken in the "Working with Multiple Environments" doc's "Development, Staging, Production" section.

### CODE REVIEW

**Comment by shirhatti** [comment]
Can you please update the PR to use a sphinx-style relative link instead of hard linking?

**Comment by scottaddie** [comment]
@shirhatti Do you have an example of how to accomplish this? The other links I'm seeing to the MVC pages are hard linked in the same way (possibly because the "aspnet" and the "mvc" folder html is built separately?). For example, see the Fundamentals --> Logging page's " Building Your First Web API with MVC 6" link.

**Comment by shirhatti** [comment]
Look at this for an example https://github.com/aspnet/Docs/blame/master/aspnet/index.rst#L18


1. Create a label for where you want to link to
2. Build the project, which will create .inv file (in this case the MVC project)
3. Update the corresponding .inv file in the project you want to link from
4. Then add the link: :ref:`Environment Tag Helper <mvc:label-name>`

**Comment by scottaddie** [comment]
@shirhatti Looking for some more direction on step 3 in your instructions. How do I update/edit an .inv file?

**Comment by danroth27** [comment]
@scottaddie After you add the labels you want to link to in the MVC docs do a build of the MVC docs. In the html folder of the build output you should find an objects.inv file. Copy this file into the ASP.NET docs replacing the existing mvc.inv file. You can add a link like this: ``:ref:`Friendly Name <mvc:label-name>` ``

**Comment by scottaddie** [comment]
Thank you to @danroth27 and @shirhatti for the detailed instructions. I learn something new every day. How does everything look now?

**Comment by shirhatti** [comment]
Thanks for the PR! Merged in b5525268ba34ad4abd090657043d129b567fde43

**Pull request closed without merging**
