### PR TITLE
Author updates

### PR DESCRIPTION
**Pull request by ardalis**
Fixing authornames on docs I've written.

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/bootstrap.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/client-side/bootstrap.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/bootstrap.md)
[aspnetcore/client-side/knockout.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/client-side/knockout.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/knockout.md)
[aspnetcore/client-side/less-sass-fa.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/client-side/less-sass-fa.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/less-sass-fa.md)
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/yeoman.md)
[aspnetcore/fundamentals/configuration.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/configuration.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/configuration.md)
[aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/dependency-injection.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/dependency-injection.md)
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/environments.md)
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/error-handling.md)
[aspnetcore/fundamentals/file-providers.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/file-providers.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/file-providers.md)
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/hosting.md)
[aspnetcore/fundamentals/logging.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/logging.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/logging.md)
[aspnetcore/fundamentals/middleware.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/middleware.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/middleware.md)
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/owin.md)
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/request-features.md)
[aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/routing.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/routing.md)
[aspnetcore/fundamentals/servers.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/fundamentals/servers.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/fundamentals/servers.md)
[aspnetcore/migration/configuration.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/migration/configuration.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/migration/configuration.md)
[aspnetcore/migration/identity.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/migration/identity.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/migration/identity.md)
[aspnetcore/migration/mvc.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/migration/mvc.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/migration/mvc.md)
[aspnetcore/migration/webapi.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/migration/webapi.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/migration/webapi.md)
[aspnetcore/mobile/native-mobile-backend.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mobile/native-mobile-backend.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mobile/native-mobile-backend.md)
[aspnetcore/mvc/controllers/actions.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/controllers/actions.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/controllers/actions.md)
[aspnetcore/mvc/controllers/application-model.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/controllers/application-model.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/controllers/application-model.md)
[aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/controllers/dependency-injection.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/controllers/dependency-injection.md)
[aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/controllers/filters.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/controllers/filters.md)
[aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/controllers/testing.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/controllers/testing.md)
[aspnetcore/mvc/models/formatting.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/models/formatting.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/models/formatting.md)
[aspnetcore/mvc/overview.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/overview.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/overview.md)
[aspnetcore/mvc/views/dependency-injection.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/views/dependency-injection.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/views/dependency-injection.md)
[aspnetcore/mvc/views/layout.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/views/layout.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/views/layout.md)
[aspnetcore/mvc/views/overview.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/views/overview.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/views/overview.md)
[aspnetcore/mvc/views/partial.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/mvc/views/partial.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/mvc/views/partial.md)
[aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/performance/caching/distributed.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/performance/caching/distributed.md)
[aspnetcore/performance/caching/index.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/performance/caching/index.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/performance/caching/index.md)
[aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/performance/caching/memory.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/performance/caching/memory.md)
[aspnetcore/performance/caching/response.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/performance/caching/response.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/performance/caching/response.md)
[aspnetcore/performance/index.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/performance/index.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/performance/index.md)
[aspnetcore/testing/index.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/testing/index.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/testing/index.md)
[aspnetcore/testing/integration-testing.md](https://github.com/aspnet/Docs/blob/ardalis/fix-authornames/aspnetcore/testing/integration-testing.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/testing/integration-testing.md)








































For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611101839051180-2144%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ardalis** [comment]
@Rick-Anderson merge?

**Comment by ardalis** [comment]
Merged to avoid future conflicts since it's hitting so many files.

**Comment by Rick-Anderson** [comment]
@ardalis  NP 
We're not requiring review for typo's and simple stuff like this - at least right now.

**Pull request merged**
