### PR TITLE
Update identity.md

### LINKED ISSUE #9372: Need for the scaffold process is not explained.
The 'Scaffold Register, Login, and LogOut' section is as very confusing. It says to follow the instructions in 'Scaffold identity into a Razor project with authorization' and that then 'When a user clicks the Register link, the RegisterModel.OnPostAsync action is invoked'.

But the 'Register', Login and Log Out buttons are already wired up and functional even _before_  following the scaffold process. Which begs two obvious but unanswered questions.
1) What is providing the implementation of the existing /Identity/Account/Register endpoint that the Register button loads.
2) What is the nature of that existing implementation and why do we need to scaffold a replacement implementation. Is the existing implementation broken or deficient in some way, in which case why provide it in the first place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #9372

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Neutrino-Sunset please review

**Comment by Neutrino-Sunset** [comment]
The change is an improvement but some context would provide a bit more clarity. I was thinking of something along the lines of

"The Authentication middleware provides a default implementation of various endpoints which support the authentication process. You can examine and/or override this default implementation through a process called 'scaffolding' by which the source code of selected aspects of this default implementation are injected into your project where it can be modified to suit your requirements."

**Comment by Rick-Anderson** [comment]
That's not correct. Read the first paragraph which explains what's going on.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio

**Comment by Neutrino-Sunset** [comment]
Sorry but I'm still a little confused.

The scaffolding description you linked says/implies that for projects which use authentication (which the identity tutorial does) it's the Identity Razor Class Library that provides the default implementation, which can be overridden by using scaffolding, _or_ for projects which didn't use opt to include authentication when created scaffolding can be used to selectively add it.

If that's the case then I don't get what's incorrect in my last post, if that's not the case then I must be misunderstanding the scaffolding description, although it seems clear enough on face value.

**Pull request merged**
