### PR TITLE
Move and rename IHostingStartup topic

### LINKED ISSUE #6228: Move and rename IHostingStartup topic with cross-link enhancements
* Rename topic to *Enhance an app from an external assembly in ASP.NET Core with IHostingStartup*
* Move topic from *Host and deploy* to *Fundamentals/Configuration*
* Cross-link the topic from *Configuration* index and *Application startup*

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #6228

### CODE REVIEW

**Comment by guardrex** [comment]
> rename the file/folder

How do you mean? ... the UID?

**Comment by Rick-Anderson** [comment]
If you rename the title, you don't need to rename the folder. Now you have redirection and the PR has a bunch of renames. None of that is necessary - just rename the title.

**Comment by Rick-Anderson** [comment]
And never change the UID, that's a convention.

**Comment by guardrex** [comment]
Let's discuss offline. I'll send an email.

**Comment by Rick-Anderson** [comment]
@guardrex  Is this ready to merge?

**Comment by guardrex** [comment]
It is ... just didn't know if you wanted to revert the physical location/UID updates. You got my "BOOK" 📖 on the subject. lol ... but yeah ... It's all good. This keeps things nice and neat.

**Pull request merged**
