### PR TITLE
Servers

### PR DESCRIPTION
**Pull request by ardalis**
Ready for review

### CODE REVIEW

**Comment by Eilon** [comment]
Something looks wrong in this... 80,000 lines changed in 100 files and 14 commits?

**Comment by ardalis** [comment]
I'm assuming it's due to merging master into it so that it could pull in all of the directory changes that were made in June.

**Comment by Eilon** [comment]
Hmm I concede I'm not sure what this PR is meant for... is it a new doc, or is it just branch maintenance?

**Comment by ardalis** [comment]
Servers.rst
And associated samples in /servers

Probably I should have rebased instead of merging?

Steve Smith

**Comment by Eilon** [comment]
Not sure. But if you look at the PR here it says 0 added lines and 79,179 deleted lines. This usually means something is messed up in your branch. But yes in general you should rebase instead of directly merging.

**Comment by ardalis** [comment]
Created new PR; closing this one.

**Pull request closed without merging**
