### PR TITLE
Update UserManager docs for spelling/clarity

### PR DESCRIPTION
**Pull request by devhammer**
Updated several method definitions for spelling/clarity

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@devhammer  these changes look great. Can you close this PR and make the changes at https://github.com/Microsoft/Docs-1 ?

**Comment by devhammer** [comment]
@Rick-Anderson Would love to do so, but I'm having trouble finding the relevant section in that repo. Can you help me locate the relevant files there?

**Comment by Rick-Anderson** [comment]
Sorry, this is API and not on the new repro. @danroth27  @bradygaster  how do we get API changes in the new repo?

**Comment by bradygaster** [comment]
@Rick-Anderson @danroth27 you would get API changes via the other repo, which contains the API YAML for the publishing system.

**Comment by danroth27** [comment]
I believe this PR should actually be done directly against the triple slash doc comments in https://github.com/aspnet/identity

**Comment by devhammer** [comment]
PR here:

https://github.com/aspnet/Identity/pull/1003

**Comment by Rick-Anderson** [comment]
Leave a comment

**Comment by devhammer** [comment]
Thanks, all, for helping me get the edits to the right place!

**Pull request closed without merging**
