### PR TITLE
security/data-protection/configuration updates

### LINKED ISSUE #3273: Update Key Management Documentation
The Key Management documentation at ( https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings#data-protection-default-settings)  does not account for all scenarios.  The four scenarios listed do not account for applications that are load balanced outside of the Azure Web Sites offering. 

I think the documentation should be updated with the following information.

5. For load balanced scenarios, not on Azure Web Sites, a Key Management repository that will store keys out of process is required. The http://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/ package provides Key Management repositories using AzureBlob, Azure Key Management, and Redis.

Also update the paragraph below the four listed options as " The first three options above should good defaults " is a typo I believe.

Below this, the documentation should provide code samples for configuration for the Startup.cs. The current samples are inside the DataProtection samples folder which is not linked and makes it tougher to find. 

I think I can try to write this up and PR this if everyone agrees this is an issue.

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #3777 
Addresses #4534
Addresses https://github.com/aspnet/DataProtection/issues/185
Fixes #3273

### Internal Review Topics
[index.md](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/index?branch=pr-en-us-4549)
[overview.md](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?branch=pr-en-us-4549)
[default-settings.md](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?branch=pr-en-us-4549)
[machine-wide-policy.md](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/machine-wide-policy?branch=pr-en-us-4549)
[non-di-scenarios.md](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/non-di-scenarios?branch=pr-en-us-4549)

**Note**: As usual, API links don't work on the review site. Remove the "review" portion of the domain from the address that comes up in the address bar to see where it goes.

### Notes:
* The 2.0 bits were handled back in July
* Mostly a UE/guidelines-adherence pass on this group of topics
  * Dropping anchor links in favor of section headings
  * Links to API topics
  * Conversion to xref links
  * Metadata updates, including title, description, and keyword updates
  * Tables look a lot better (imho) than lists for some of the content
  * Added descriptions on the index page for this group of topics
* Small code updates for the non-DI topic
* Squeeze in a note on addressing Docker ephemeral keys, but I don't think it surfaces well buried in the Key Management topic, so I also add a little blurb at the bottom of the overview topic.
* Did a little more work for #3273 surfacing the key extensibility topic and key management for web farm scenarios with share access `PersistKeysToFileSystem` and without share access (use an external provider).

cc/ @ajaybhargavb @blowdart

### CODE REVIEW

**Comment by guardrex** [comment]
@scottaddie Can u roll that back? ... this PR removes those anchors in favor of section headings.

**Comment by Rick-Anderson** [comment]
@ajaybhargavb are you the right person to review this? If so, can you give me an ETA? If not, who?

**Comment by Rick-Anderson** [comment]
@guardrex  is there anyway to delete some of the *wwwroot/* files in this PR to make it more manageable?
Can you point to the top places that need security/technical review?

**Comment by guardrex** [comment]
@Rick-Anderson The 2.0 bits were already done (particularly the overview topic), but this batch was on my *To Do* list, so I assumed u wanted the UE addressed. The only update for 2.0 on this pass were two minor items ...

* Squeeze in a note on addressing Docker ephemeral keys, but I don't think it surfaces well buried in the Key Management topic, so I also add a little blurb at the bottom of the overview topic.
* I threw in some light coverage to fix https://github.com/aspnet/Docs/issues/3273, which just resulted in adding a line that external providers are useful in web farm scenarios that also surfaces `PersistKeysToFileSystem`.

These were the only issues that I found in the DP issues and release notes that weren't covered in the topics here for 2.0.

**Comment by guardrex** [comment]
I think those particular changes are in ...

default-settings.md Line 36
overview.md Lines 290-295

**Comment by guardrex** [comment]
"Normalization of file reference in ..." :point_left: doesn't mean much to me. Many of those errors pertain to files that aren't part of this PR. I think the best approach is to re-constitute the PR. Stand-by ... I'll fix it.

**Comment by guardrex** [comment]
@Rick-Anderson [Re-constituted PR](https://github.com/aspnet/Docs/pull/4587) with identical updates based on the current master branch failed with the same exceptions.

**Comment by Rick-Anderson** [comment]
@Eilon  can you recommend someone to review these changes while @ajaybhargavb  is OOF?

**Comment by Eilon** [comment]
Adding @Tratcher / @natemcmaster / @blowdart .

**Comment by guardrex** [comment]
@Tratcher Thanks ... change made.

**Pull request merged**
