### PR TITLE
Neudesic updates

### PR DESCRIPTION
**Pull request by neusamir**
Fixing a few things manually that were missed during automated runs

### CODE REVIEW

**Comment by neusamir** [comment]
@Rick-Anderson I think these are broken on the aspnetcore side. Can you track down why they are missing?

**Comment by Rick-Anderson** [comment]
@neusamir  yes, those are all aspnetcore errors. I just built the latest master with no errors. @tdykstra  do you know what could be causing these errors?

**Comment by tdykstra** [comment]
There are some bogus aspnetcore changes in this PR.

**Comment by Rick-Anderson** [comment]
>There are some bogus aspnetcore changes in this PR.

@tdykstra  I looked for that and couldn't find them.

I pulled this down to my local machine and it builds without error. Can we merge - then revert if the problem persists?

**Comment by Rick-Anderson** [comment]
@neusamir @tdykstra  Tom is right
It builds fine in the aspnet dir but I get the same errors in the aspnetcore directory
Somehow that code got deleted.

@neusamir  I would create a new PR:

- Copy over your changes from aspnet directory

then you'll get a clean build

**Comment by neusamir** [comment]
@Rick-Anderson @tdykstra Good idea, I created a new PR with a new branch with the updates.

**Pull request closed without merging**
