### PR TITLE
Path missing "Shared" folder

### PR DESCRIPTION
**Pull request by juricav**
The tutorial page has a typo in the path.

### CODE REVIEW

**Comment by scottaddie** [comment]
The ASP.NET Core 2.0 project template didn't use a *Pages/Shared* folder. The *_Layout.cshtml* file lived in the root of *Pages*. I do, however, see what would've led the reader to believe otherwise. I'll keep this issue open to address that problem.

**Comment by Rick-Anderson** [comment]
@scottaddie  you need to select 2.1 to see the 2.1 layout. What's the problem? This PR has the layout file in Shared, which is wrong for 2.0

**Comment by scottaddie** [comment]
@Rick-Anderson Please see the linked PR. Looks like the 2.1 include was being used when 2.0 was selected.

**Comment by juricav** [comment]
I may have taken the wrong file.
But the 2.1 layout is selected and there's not Shared folder.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1#update-the-layout

**Pull request closed without merging**
