### PR TITLE
mark change after RST->MD

### PR DESCRIPTION
**Pull request by Rick-Anderson**
We need a mechanism to mark docs that have changes after the snapshot port from RST -> MD

I propose we add a comment at the top of the file for all commits after the snapshot. Folks working on the conversion should check to make sure the topic has not been updated. Skip docs that have been updated and we will fix them in the next round when the tool is run again.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@danroth27 @spboyer @tdykstra 
I propose we use this mechanism to mark updated topics.

**Comment by danroth27** [comment]
Could we just query for PRs after a certain date and then see what files they touch?

**Comment by Rick-Anderson** [comment]
what's the query for all updates after 9/14?

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20merged%3A%3E2016-09-15%20

Daniel Roth

**Pull request closed without merging**
