### PR TITLE
swagger github url corrected

### PR DESCRIPTION
**Pull request by aftab10662**
Github Link Corrected for Swagger.
It was taking to the wrong  url **_https://docs.asp.net/en/latest/tutorials/ahref=%22https://github.com/swagger-api/swagger-ui%22_**

### CODE REVIEW

**Comment by aftab10662** [comment]
@danroth27 Request you to review the PR.

**Comment by aftab10662** [comment]
@Rick-Anderson Request you to review PR.

**Comment by Rick-Anderson** [comment]
@aftab10662  Thanks!

**Comment by Rick-Anderson** [comment]
@aftab10662 "This branch has conflicts that must be resolved"  Could you copy/paste the changes into a new PR?

**Comment by spboyer** [comment]
Closing PR as this is an immediate issue. Fixed in #1803

**Pull request closed without merging**
