### PR TITLE
Revert some RP tutorial updates

### PR DESCRIPTION
**Pull request by guardrex**
@Rick-Anderson U sure about this? ... It's going to show the reader *bad practices* due to the [scaffolding bug](https://github.com/aspnet/Scaffolding/issues/633). If you prefer, I can leave the (correct) sample alone and take the scaffolding bits out (i.e., rewrite them out) of the tutorial.

It's prob not necessary to have these recorded, since the PR can be rolled back later, but just in case:

*includes/RP/model2.md*
Use code (but double-check the ranges here; look wrong):
> \[!code-csharp\[Main](../../tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieContext.cs?range=1-12,14-17,19-21)]

Add to Line 14:
> The `DbSet` property name is `Movies`. Since the database uses singular names, the sample overrides `OnModelCreating` to use the singular form (`Movie`) for the table name.

*Models/MovieContext.cs* Line 12
```csharp
public DbSet<Movie> Movies { get; set; }
public DbSet<Schedule> Schedules { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Movie>().ToTable("Movie");
    modelBuilder.Entity<Schedule>().ToTable("Schedule");
}
```

*Models\SeedData.cs*, Line 20, 25
```csharp
if (context.Movies.Any())
...
context.Movies.AddRange(
```

*Models\SeedDataRating.cs*, Line 20, 26
```csharp
if (context.Movies.Any())
...
context.Movies.AddRange(
```

*Pages/Movies/Create.cshtml.cs* Line 44
```csharp
_context.Movies.Add(Movie);
```

*Pages/Movies/Delete.cshtml.cs* Line 31, 47, 51
```csharp
Movie = await _context.Movies.SingleOrDefaultAsync(m => m.ID == id);
...
Movie = await _context.Movies.FindAsync(id);
...
_context.Movies.Remove(Movie);
```

*Pages/Movies/Details.cshtml.cs* Line 30
```csharp
Movie = await _context.Movies.SingleOrDefaultAsync(m => m.ID == id);
```

*Pages/Movies/Edit.cshtml.cs* Line 32, 56
```csharp
Movie = await _context.Movies.SingleOrDefaultAsync(m => m.ID == id);
...
if (!_context.Movies.Any(e => e.ID == Movie.ID))
```

*Pages/Movies/Index.cshtml* Line 41
```cshtml
@foreach (var item in Model.Movies) {
```

Lines 29, 32, 35, 38, 41: Convert to `model.Movies[0]`

*Pages/Movies/Index.cshtml.cs* Line 26, 35, 45, 57, 62, 77
```csharp
public List<Movie> Movies;
...
var movies = from m in _context.Movies
...
...
Movie = await movies.ToListAsync();
...
IQueryable<string> genreQuery = from m in _context.Movies
...
var movies = from m in _context.Movies
...
Movies = await movies.ToListAsync();
```

*Pages/Movies/Index2.cshtml* Line 41
```cshtml
@foreach (var item in Model.Movies) {
```

Lines 26, 29, 32, 35: Convert to `model.Movies[0]`

*Pages/Movies/IndexFormGenreNoRating.cshtml* Line 44
```cshtml
@foreach (var item in Model.Movies) {
```

Lines 29, 32, 35, 38: Convert to `model.Movies[0]`

*Pages/Schedules/Delete.cshtml.cs* Line 31, 47, 51
```csharp
Schedule = await _context.Schedules.SingleOrDefaultAsync(m => m.ID == id);
...
Schedule = await _context.Schedules.FindAsync(id);
...
_context.Schedules.Remove(Schedule);
```

*Pages/Schedules/Index.cshtml* Line 55
```cshtml
@foreach (var item in Model.Schedules) {
```

Lines 41, 44, 47, 50: Convert to `model.Schedules[0]`

*Pages/Schedules/Index.cshtml.cs* Line 24, 28, 37, 51, 65

```csharp
public IList<Schedule> Schedules { get; private set; }
...
Schedules = await _context.Schedules.AsNoTracking().ToListAsync();
...
Schedules = await _context.Schedules.AsNoTracking().ToListAsync();
...
Schedules = await _context.Schedules.AsNoTracking().ToListAsync();
...
_context.Schedules.Add(schedule);
```

*aspnetcore/tutorials/razor-pages/page.md*
Line 42: Use `model.Movies[0]`
Line 45: Use `model.Movies`, or `model.Movies[0]`

*aspnetcore/tutorials/razor-pages/uploading-files.md*
Line 93: `Schedules` is rebuilt
Change Line 40 to:
> Specify a `DbSet` in the `MovieContext` (*Models/MovieContext.cs*) for the schedules and add a line to the `OnModelCreating` method that sets a singular database table name (`Schedule`) for the `DbSet` property:

Add a Line at 44:
> Note: If you don't override `OnModelCreating` to use singular table names, Entity Framework assumes that you're using plural database table names (for example, `Movies` and `Schedules`). Developers disagree about whether table names should be pluralized or not. Configure the `MovieContext` and the database the same way. Either use singular or pluralized database table names in both places.

*aspnetcore/tutorials/razor-pages/search.md*
Line 27: `_context.Movies`

*razor-pages-start/snapshot_sample/RazorPagesMovie/Pages/Movies/Create.cshtml.cs*
Line 36: Use `_context.Movies.Add(Movie);`

*razor-pages-start/snapshot_sample/RazorPagesMovie/Pages/Movies/Edit.cshtml.cs* Line 33, 58
```csharp
Movie = await _context.Movies.SingleOrDefaultAsync(m => m.ID == id);
...
if (!_context.Movies.Any(e => e.ID == Movie.ID))
```

*razor-pages-start/snapshot_sample/RazorPagesMovie/Pages/Movies/Index.cshtml*
Lines 17, 20, 23, 36: Use `model.Movies[0]`
Line 32:
```cshtml
@foreach (var item in Model.Movies) {
```

*razor-pages-start/snapshot_sample/RazorPagesMovie/Pages/Movies/Index.cshtml.cs* Line 19, 23
```csharp
public IList<Movie> Movies { get;set; }
...
Movies = await _context.Movies.ToListAsync();
```

*aspnetcore/tutorials/razor-pages.sql.md* Line 58
```csharp
if (context.Movies.Any())
```

*aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample/RazorPagesMovie/Pages/Scedules/Delete.cshtml.cs* Line 31, 48, 52
```csharp
Schedule = await _context.Schedules.SingleOrDefaultAsync(m => m.ID == id);
...
Schedule = await _context.Schedules.FindAsync(id);
...
_context.Schedules.Remove(Schedule);
```

*aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample/RazorPagesMovie/Pages/Scedules/Index.cshtml.cs* Line 27, 33, 44, 58, 72
```csharp
public IList<Schedule> Schedules { get; private set; }
...
Schedules = await _context.Schedules.AsNoTracking().ToListAsync();
...
Schedules = await _context.Schedules.AsNoTracking().ToListAsync();
...
Schedules = await _context.Schedules.AsNoTracking().ToListAsync();
...
_context.Schedules.Add(schedule);
```

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
It's not a bad practice altho it's hotly debated.
Can you fix the validation problems?

**Comment by guardrex** [comment]
A stronger case might be made for calling it *bad* since it doesn't match [what the EF topics show](https://docs.microsoft.com/ef/core/#the-model). Plural over there; singular here.

The semantics are yucky: `IList<Customer> Customer` and then all of these strange wordings, such as `_context.Customer.Add(Customer)`, `model.Customer[0].Property`, `foreach (var customer in Model.Customer)`. 🙈 lol

I (think 😅) I fixed the validation issues. I'm going to build this locally and do another pass shortly. I'm marking WIP for just a sec.

**Comment by Rick-Anderson** [comment]
From the EF series
When the database is created, EF creates tables that have names the same as the `DbSet` property names. Property names for collections are typically plural (Students rather than Student). Developers disagree about whether table names should be pluralized or not. For these tutorials you override the default behavior by specifying singular table names in the DbContext. To specify singular table names, add the following highlighted code.

**Comment by guardrex** [comment]
Table names in the dB, *yes*; collection names in the app, *not so much* (i.e., their remark, "Property names for collections are typically plural"). I overrode `OnModelCreating`, so I didn't change the table names in the dB with my updates. I only changed the collection names. That's the only thing scaring me about it. Hopefully, they'll have the scaffolding fixed for 2.1.

**Comment by Rick-Anderson** [comment]
@guardrex  is this ready?

**Comment by guardrex** [comment]
In 5 minutes :watch:

**Comment by guardrex** [comment]
kk -- that should get it.

**Pull request merged**
