### PR TITLE
fix: MD038/no-space-in-code

### PR DESCRIPTION
**Pull request by nschonni**
- Replace ` with %60 in xref links
- Remove spaces inside code span elements

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@scottaddie  @tdykstra @guardrex  do we want to replace Replace ` with %60 in xref links

**Comment by guardrex** [comment]
@nschonni I see that this PR produced no build warnings/errors, so it should be ok, but ...

The build system is rendering good API links with backticks, which are probably in the `ms.asset` values.

What's the problem with backticks?
.

**Comment by tdykstra** [comment]
> do we want to replace Replace ` with %60 in xref links

>What's the problem with backticks?

If %60 works I'd say it's preferable, since backticks get confused with inline code format backticks.

**Comment by guardrex** [comment]
If u go that way, I'll get the XREF Gen app updated this weekend.

**Comment by scottaddie** [comment]
%60 appears to work. I'm in favor of this change.

**Comment by scottaddie** [comment]
@guardrex Go ahead with updating your app.

**Pull request merged**
