### PR TITLE
Fixing Bugs and Reuse Default Implementation.

### PR DESCRIPTION
**Pull request by granthoff1107**
Reusing BackgroundService abstract class,  Removes redundant call Task.Run 

When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @granthoff1107 ... thanks for submitting this.

@Tratcher Are you good with using `BackgroundService` for the 2.1 approach/example?

**Comment by granthoff1107** [comment]
Yeah,  I'm not sure what I'm missing from the Microsoft coding conventions,  I'm guessing it's because I removed the line breaks.   I'll make another another commit.

**Comment by guardrex** [comment]
Hold off on that for a sec @granthoff1107. We won't be able to accept this PR in its current form for a number of reasons. Once we hear back from `@Tratcher`, I can advise you on how to set up the PR, which will require a snapshot of the current code for 2.0 and changes to the document's text (... or if you don't want to deal with all of that, I'll take care of it). However, we should take this over to an issue for discussion first. Stand-by ... `@Tratcher` will get back to us soon. I just want to clear the overall approach with him first before we proceed.

**Comment by granthoff1107** [comment]
@guardrex,  I'll take care of it. I'd like to contribute.   I was using the wrong token source, in the example.  If  for some reason this PR get reject.  I'll create a new one which just adds in the Disposable Pattern

**Comment by granthoff1107** [comment]
@guardrex any updates on this?

**Comment by guardrex** [comment]
I think `@Tratcher` is out of the office for a short time. When he returns, he'll take a look at this and decide if the topic+sample should go in this direction.

**Comment by Tratcher** [comment]
Using BackgroundService is fine.

**Comment by guardrex** [comment]
We won't be able to use this as it is given that the topic requires commensurate changes and `BackgroundService` is 2.1. We'll need to separate the examples for 2.0 and 2.1.

@granthoff1107, I'll need to give you a list of things to do to put the PR together. I recommend that you open an issue first for discussion, then I can provide instructions there. After that, I recommend setting up a branch for the work and creating a new PR based on the new issue.

**Comment by guardrex** [comment]
We'll do the work off of https://github.com/aspnet/Docs/issues/7638.

@granthoff1107 If you want to do the work, I'll provide additional instructions over on #7638; otherwise, I'll take care of it. Either way, thanks for providing this.

**Pull request closed without merging**
