### PR TITLE
Registering Custom IXmlRepository For 2.0

### PR DESCRIPTION
**Pull request by anonymousgituser**
[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/security/data-protection/extensibility/key-management?branch=pr-en-us-4831&tabs=aspnetcore2x#ixmlrepository)

# Registering Custom IXmlRepository For 2.0

* Summary

  Updated how to register custom IXmlRepository instance for ASP.NET Core 2.0.

* Suggest reviewers

  Current authors: @Rick-Anderson, @scottaddie, @guardrex, @isaac2004, and @ajaybhargavb.

### CODE REVIEW

**Comment by scottaddie** [comment]
@Tratcher @HaoK Can one you please review this change?

**Comment by Tratcher** [comment]
I'm not familiar with this. Is there an issue or change you're getting this from?

**Comment by scottaddie** [comment]
@Tratcher I'm unaware of any associated issue.

**Comment by Tratcher** [comment]
Then why the change?

**Comment by scottaddie** [comment]
@anonymousgituser Is there something in particular that wasn't working for you in 2.x when using the following code?

```csharp
services.AddSingleton<IXmlRepository>(new MyCustomXmlRepository());
```

**Comment by guardrex** [comment]
In discussions with @blowdart a while back, the point was made that the docs shouldn't show too much in the way of replacing parts of the DP stack because it's very unsafe and not to be encouraged. imo this PR kind'a falls under that umbrella.

**Comment by ajaybhargavb** [comment]
We changed the way custom IXmlEncryptor and IXmlRepository needs to registered in 2.0. https://github.com/aspnet/DataProtection/issues/226#issuecomment-342310171.

**Comment by Rick-Anderson** [comment]
@ajaybhargavb Can you review this PR?

**Comment by Rick-Anderson** [comment]
@anonymousgituser  Awesome update. Thanks!

**Comment by anonymousgituser** [comment]
@Rick-Anderson Glad to help!

@ajaybhargavb I would be happy to help with documenting this, but, admittedly, a dedicated team member at Microsoft would likely tackle this one faster than I would.

**Comment by scottaddie** [comment]
@anonymousgituser No problem. I'll take care of it.

**Pull request merged**
