### PR TITLE
Grunt/Gulp Article

### PR DESCRIPTION
**Pull request by ardalis**
Ready for Review - related to #22

Accidentally included previous PR changes in this one, too... Should only be grunt-gulp.rst for review.

### CODE REVIEW

**Comment by danroth27** [comment]
@madskristensen @DamianEdwards Could you guys please review this article on grunt/gulp?

**Comment by madskristensen** [comment]
For Grunt/Gulp documentation, here's a few corrections:

1. Grunt and Gulp are equally supported. The project template uses Gulp, but it doesn't mean Grunt isn't equally supported.
2. Saving package.json/bower.json will automatically restore the package

**Comment by ardalis** [comment]
Good to go, now?

**Comment by ardalis** [comment]
@madskristensen The changes you requested have been committed; can you confirm and if all is good add a `:shipit:` comment? Thanks!

**Comment by madskristensen** [comment]
:shipit:

**Pull request merged**
