### PR TITLE
Fix misplaced section

### LINKED ISSUE #9207: Register database context section misplaced
It should be grouped with the code sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by daveabrock**
Fixes #9207 

**Internal Review Pages**
* [VS Code tutorial](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1&branch=pr-en-us-9209#add-a-database-connection-string)
* [VS for Mac tutorial](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/model?view=aspnetcore-2.1&branch=pr-en-us-9209#add-a-database-connection-string)

### CODE REVIEW

**Comment by daveabrock** [comment]
@scottaddie - I removed the whitespace. Assuming you are referring to [this document](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/model?view=aspnetcore-2.1), that is correct and I found no issues.

**Comment by scottaddie** [comment]
@daveabrock Yes, that's the doc. Here's what I see with your changes:

image

Here's what that section looks like in production:

image

The production version of the doc is what we'd want.

**Comment by daveabrock** [comment]
@scottaddie I am confused. In both documents, in production, the content is correct. Can you review again and let me know if I am missing anything?

**Comment by scottaddie** [comment]
@daveabrock Please resolve the merge conflict, and then I'll take another look at this.

**Comment by daveabrock** [comment]
@scottaddie I resolved the conflict. Let me know what you think when you get a moment.

**Comment by daveabrock** [comment]
Closing as this is now covered under PR #9266.

**Pull request closed without merging**
