### PR TITLE
pass viewData with model to partial view:

### LINKED ISSUE #2118: views/partial.md "Partial Views"
- [x] Update to RTM
- [x] UE review
- [x] DISQUS 
- [ ] Show how to [Pass Additional ViewData to a Strongly-Typed Partial View](http://stackoverflow.com/questions/1169170) fixed in #2984

### PR DESCRIPTION
**Pull request by Rick-Anderson**
fixes #2118 
@MaherJendoub please review

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  need to use the ViewData we're passing. How do you access the ViewData? I want something like
```
@using PartialViewsSample.ViewModels
@model ArticleSection

<h3>@Model.Title by @ViewData["Article.Author"]</h3>
<div>
    @Model.Content
</div>
```

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  I was thinking the following was simpler - but it's not working:

```
@using Microsoft.AspNetCore.Mvc.ViewFeatures
@using PartialViewsSample.ViewModels
@model Article

<h2>@Model.Title</h2>
@*Pass the authors name to Views\Shared\AuthorPartial.cshtml*@
@Html.Partial("AuthorPartial", Model.AuthorName)
@Model.PublicationDate

@*Loop over the Sections and pass in a section and additional ViewData
    to the strongly typed Views\Articles\ArticleSection.cshtml partial view.*@
@{ var index = 0;
    @foreach (var section in Model.Sections)
    {
        @Html.Partial("ArticleSection", section,
                    new ViewDataDictionary(this.ViewData) { { "index", index } })
        index++;
    }
}
 ```

And the ArticleSection.cshtml

```
@model ArticleSection

<h3>@Model.Title  Index: @ViewData["index"]  </h3>
<div>
    @Model.Content
</div>
```

**Comment by MaherJendoubi** [comment]
@Rick-Anderson Do you have this result?
image

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  that's exactly what I was expecting but not what I'm getting. Can you pull down this PR and see what's wrong with my code? Do you think this is a better sample or do you want to display something from the viewData you're passing?

**Comment by MaherJendoubi** [comment]
@Rick-Anderson Please review https://github.com/aspnet/Docs/pull/3024

**Comment by MaherJendoubi** [comment]
@Rick-Anderson Your code is missing a using statement @using PartialViewsSample.ViewModels in ArticleSection.cshtml.

**Pull request closed without merging**
