### PR TITLE
Update screenshots containing console logger output.

### PR DESCRIPTION
**Pull request by cesarbs**
Only the log level is colored now.

Also making all of them the same size, for consistency.

cc @danroth27

### CODE REVIEW

**Comment by cesarbs** [comment]
Just noticed there's another screenshot that needs to be updated (the one with TraceSource output).

**Comment by cesarbs** [comment]
Updated.

**Comment by BrennanConroy** [comment]
All the labels are supposed to have the background color set to a whiteish color

**Comment by cesarbs** [comment]
@BrennanConroy As we've just found out, no they're not :)

**Comment by Rick-Anderson** [comment]
:shipit:

**Pull request merged**
