### PR TITLE
Corrections to accconfirm.rst

### PR DESCRIPTION
**Pull request by glen-84**
See also: https://github.com/aspnet/Docs/issues/298

### CODE REVIEW

**Comment by danroth27** [comment]
Looks good to me :shipit:.

@rustd @MikeWasson @Rick-Anderson Could you guys please take a look as well?

**Comment by Rick-Anderson** [comment]
@danroth27 @rustd @MikeWasson - Looks great! Next time I can do this sort of clean up and we can leave the complicated programming to @glen-84

**Comment by glen-84** [comment]
I think I'm better at this than programming. :grin:

... but I'll stop now, as @rustd is probably starting to hate me.

**Comment by danroth27** [comment]
Thanks for the edits!

**Comment by rustd** [comment]
:shipit: Thank you for making these changes @glen-84

**Pull request merged**
