### PR TITLE
add redirect info

### PR DESCRIPTION
**Pull request by tdykstra**
@Rick-Anderson please review

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/aspnet/Docs/blob/tdykstra-patch-1/CONTRIBUTING.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C9%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612091849213224-2361%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
This is critical info we need but I'd rather put it someplace else to keep the contrib guide short. Customers will rarely need this. I'm not sure else to keep it so it may need to go in here. If we keep it here, maybe move it to the very end.  cc @danroth27 @spboyer

**Comment by tdykstra** [comment]
@Rick-Anderson Agreed, moved to end until we find a better place.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[CONTRIBUTING.md](https://github.com/aspnet/Docs/blob/tdykstra-patch-1/CONTRIBUTING.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C9%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612091921228808-2361%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
