### PR TITLE
Migrate Authoring Tag Helpers sample code to CSPROJ

### PR DESCRIPTION
**Pull request by scottaddie**
Update the [Authoring Tag Helpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring) sample code to VS 2017, .NET Core 1.1, and CSPROJ. Used the `dotnet migrate` CLI command to accomplish this, and also updating project files to more closely match the StarterWeb template used for ASP.NET Core 1.1 (e.g., replaced npm & Gulp with BundlerMinifier).

### CODE REVIEW

**Comment by GuardRex** [comment]
Couple of notes/questions here:
* `M.N.Sdk.Web` should be taking care of `wwwroot`, views, `appsettings.json`, and `web.config`.
* `AssemblyName` and `PackageId` are coming out of `dotnet migrate`, but they aren't in the templates. I thought we weren't going to include props unless they're in the templates. (?)
* `OutputType` is another one that was there in the templates for a while and it seems to have :sparkles: disappeared :sparkles: (?)
* I don't think `RuntimeFrameworkVersion` is required for a flat (not starred) 1.1 app.
* They're including the `RuntimeIdentifier` in the templates, but that should go away soon-ish: https://github.com/dotnet/sdk/issues/396

**Comment by Rick-Anderson** [comment]
@scottaddie  Thanks!

**Comment by spboyer** [comment]
@Rick-Anderson this was a merge to master for CSPROJ content. Are we just going straight there now?

**Comment by Rick-Anderson** [comment]
@spboyer  we only use the CSPROJ branch when the document contains msbuild/csproj instructions. We've been making code migrations into master. cc @tdykstra

**Pull request merged**
