### PR TITLE
A Bug in the Install instructions CentOS

### PR DESCRIPTION
**Pull request by paule96**
Insert the install instruction for the issue #641.

### CODE REVIEW

**Comment by Eilon** [comment]
@moozzyk @BrennanConroy can you review the technical accuracy of this?

**Comment by BrennanConroy** [comment]
I'm leaning towards no, this is for fixing a beta7 issue

**Comment by moozzyk** [comment]
Shouldn't this then be rebased on top of master/beta8/rc1 (not sure what's the latest) because libcurl, libssl and libicu (and maybe more - not sure about libunwind) need to be installed on the box to run CoreClr.

**Comment by paule96** [comment]
@BrennanConroy  but what do the coreclr use in the rtm (unstable) Version. I think the same Problem is there. In beta8 I have no way found to run coreclr on centos7/RHEL7. The only alternativ to run coreclr on Centos ore rhel is to install beta7 today.

does any body know where the libssl for centos can be found? ore isn't this exist?

**Comment by danroth27** [comment]
.NET Core on CentOs is unfortunately not supported in beta8. We are working on adding this support and it should be available in a future release.

**Comment by moozzyk** [comment]
@paule96 - Now I remembered that there was no CoreClr for beta8. CoreClr is compiled against libcrypto 1.0.0 and the only I was able to find for CentOs was libcrypto 1.0.1. Linking 1.0.1 as 1.0.1 did not work - 
The failure was:
`/lib64/libcrypto.so.1.0.0: error: version lookup error: version 'OPENSSL_1.0.0' not found (required by /home/asplab/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin/System.Security.Cryptography.Native.so) (fatal)
`
but when reading Elf all the options entries show EC_PRIVATEKEY_new@@**OPENSSL_1.0.1_EC**
So I don't (notice `OPENSSL_1.0.0` vs. `OPENSSL_1.0.1_EC`)
Because this is a binary compatibility issue there is not really a good way to make the scenario work without fixing CoreClr

**Comment by paule96** [comment]
@danroth27 Yes that is what I sad too. Beta8 doesn't Support this. but the issues for the docs is for beta7 or lower because that is to day the only way you can run vnext with RHEL7. The docs are wrong without this hint and that for all versions of the vnext stuff. 

@moozzyk  Oh thx. that sounds bat. 


What is with the RTM version. If I look to the roadmap I see no support for RHEL7. Is there any plans to bring it after beta7 again to RHEL?

**Comment by danroth27** [comment]
We actually recently [announced](http://blogs.microsoft.com/blog/2015/11/04/microsoft-and-red-hat-partner-to-deliver-more-flexibility-and-choice/) a strategic partnership between Microsoft and RedHat and we are hard at work on enabling support for .NET Core in RHEL. Stay tuned!

**Comment by garora** [comment]
Guys - is there any workaround. We are planning to deploy our app on RHEL ?

**Pull request closed without merging**
