### PR TITLE
Policy sample upgrades

### LINKED ISSUE #10932: Upgrade policy sample from 1.1 to 2.2
Upgrade policy sample from 1.1 to 2.2

Changed `GetExternalAuthenticationSchemes` to `GetExternalAuthenticationSchemesAsync`
but `Where` needs work.

```
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
                                               BuildingEntryRequirement requirement)
{
    if (context.User.HasClaim(c => c.Type == ClaimTypes.BadgeId &&
                                   c.Issuer == "http://microsoftsecurity"))
    {
        context.Succeed(requirement);
    }

    //TODO: Use the following if targeting a version of
    //.NET Framework older than 4.6:
    //      return Task.FromResult(0);
    return Task.CompletedTask;
}
```
 
`ClaimTypes` does not contain a definition for `TemporaryBadgeId`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #10932.

[**INTERNAL REVIEW URL**](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2&branch=pr-en-us-11317)

I've updated the existing `PoliciesAuthApp1` project to 2.2 and added a new 2.2 RP-based `PoliciesAuthApp2` project. I've updated the source-code links in `policies.md` to point to the relevant sections of `PoliciesAuthApp1`.

I still need to reference `PoliciesAuthApp2` in `policies.md`, but I'd like input on how to do this. Would it be OK to include tabs with one for MVC and one for RP? This would apply only to the second code snippet that shows use of the `Authorize` attribute. Otherwise, I'm open to suggestions here.

### CODE REVIEW

**Comment by serpent5** [comment]
@Rick-Anderson Can you advise on whether or not the tabs option I suggested above is OK here? I don't think tabs has been used for MVC vs RP before so I don't want to just go ahead and do it. If it's not appropriate here, could you suggest how you would include both the RP and MVC version of the code? I'm having trouble with the idea of having one example after the other as the concept being demonstrated is applying the `[Authorize]` attribute which is the same for both. I hope you don't mind me mentioning you directly here - I'm not sure what else to do in terms of contacting you guys directly otherwise. :smile:

**Comment by Rick-Anderson** [comment]
No don't use tabs. Take a look at [Areas](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.2)

image

**Comment by serpent5** [comment]
I’m unable to mark this as ready for review. I’ve messaged the GitHub support team to see if they can help.

**Comment by serpent5** [comment]
@Rick-Anderson Is there anything I can do to make reviewing this one easier? I appreciate that it's a pretty huge changeset...

**Comment by Rick-Anderson** [comment]
@serpent5 me bad. @blowdart  please review.

**Comment by serpent5** [comment]
@blowdart I hope you don't mind me asking, but do you have a rough idea of when you might be able to look at this?

**Comment by blowdart** [comment]
You were right to bug me :) 

Only real feedback I have is I think Applying policies should be Applying policies to MVC controllers, to match the wording of the next heading.

**Comment by serpent5** [comment]
Thanks @blowdart for the feedback and @Rick-Anderson for the commit + merge. :tada:

**Pull request merged**
