### PR TITLE
Update SpaServicesSampleApp with current generated files

### PR DESCRIPTION
**Pull request by Asesjix**
This PR replace SpaServicesSampleApp with current generated files from "dotnet new angular" (v2.1.403)
Issue reference #8596

### CODE REVIEW

**Comment by scottaddie** [comment]
@Asesjix There are several build warnings that will need to be addressed in this PR. They're related to files being referenced in the associated doc (spa-services.md) that no longer exist. I suspect parts of the doc will require rewriting as a result. Is this something you're willing to take on?

**Comment by Asesjix** [comment]
@scottaddie I'll take a look at it ;-)

**Comment by scottaddie** [comment]
Any updates to provide on this, @Asesjix?

**Comment by Asesjix** [comment]
Sorry, I have not found any time yet :(

**Comment by scottaddie** [comment]
Closing for now. When you have time to look at this again, either reopen this PR or create a new PR.

**Pull request closed without merging**
