### PR TITLE
JSNLog url changed to github link

### PR DESCRIPTION
**Pull request by reyou**
While other 3rd party providers supplied with their github source, to keep it consistent, I suggest to change JSNLog ones as well.

When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

### CODE REVIEW

**Comment by guardrex** [comment]
We could show both tho. That would be my preference. @scottaddie Thoughts?

**Comment by scottaddie** [comment]
@guardrex Let's stick with just the link to the GitHub repo. The official website of any reputable provider can always be found in the README of the repo.

**Comment by reyou** [comment]
@guardrex I agree with their concerns, however, an official and open-source documentation should not be a place there marketing goals to be a concern. Maybe keeping both links is a better idea, but I am more towards to choose github link, rather than organization website if we have a single choice.

**Comment by scottaddie** [comment]
I understand the marketing concern, but most devs don't want to see marketing material. Devs are the intended audience for the doc.

**Comment by scottaddie** [comment]
@guardrex I'm not opposed to having both, if you have the time.

**Comment by guardrex** [comment]
@reyou Can you review the CLA and sign it if agreeable?

**Comment by reyou** [comment]
@guardrex done. Thanks!

**Pull request merged**
