### PR TITLE
Package does not install without valid culture

### PR DESCRIPTION
**Pull request by ncthbrt**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@shirhatti  please review

**Comment by shirhatti** [comment]
Looks like `Install-NanoServerPackage` is broken right now for `Microsoft-NanoServer-IIS-Package`
https://github.com/OneGet/NanoServerPackage/issues/2

Two possible workarounds:
1) Install another package that requires a reboot
````
Install-NanoServerPackage -Name Microsoft-NanoServer-Storage-Package 
Install-NanoServerPackage -Name Microsoft-NanoServer-IIS-Package
````

2) Use `dism.exe` instead.
Download `https://az880830.vo.msecnd.net/nanoservercontainer/Microsoft-NanoServer-IIS-Package_base_10-0-14300-1000.cab` and `https://az880830.vo.msecnd.net/nanoservercontainer/Microsoft-NanoServer-IIS-Package_English_10-0-14300-1000.cab`
Then run 
````
dism.exe /online /add-package /packagepath:c:\sources\Microsoft-NanoServer-IIS-Package_base_10-0-14300-1000.cab & \
dism.exe /online /add-package /packagepath:c:\sources\Microsoft-NanoServer-IIS-Package_English_10-0-14300-1000.cab & \
dism.exe /online /add-package /packagepath:c:\sources\Microsoft-NanoServer-IIS-Package_base_10-0-14300-1000.cab
````

**Comment by shirhatti** [comment]
Back to the PR, just adding a valid culture doesn't allow the installation to succeed. We'll have to update the article to use one of the two approaches I've outlined.

**Comment by Rick-Anderson** [comment]
@ncthbrt  thanks for bringing this to our attention.

**Comment by ncthbrt** [comment]
Sure. Thanks for the work around

**Pull request closed without merging**
