### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by shirhatti**
Addresses #1046

### CODE REVIEW

**Comment by danroth27** [comment]
Hmm, this looks like a bit of a hack. The license isn't part of the copyright.

**Comment by danroth27** [comment]
I think the "right" way to do this is to specify a custom jinja template for the footer that overrides the footer block from the basic sphinx theme: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/layout.html#L185

**Comment by danroth27** [comment]
Or we could just do the hack :smile:. :shipit:

**Comment by shirhatti** [comment]
I'm updated the PR to do it the "right" way

**Comment by danroth27** [comment]
Cool :shipit:

**Pull request merged**
