### PR TITLE
Razor Pages tutorial File Uploads topic

### LINKED ISSUE #4188: Razor Pages tutorials section in need of its own File Uploads topic
## General

I just did a dance here for the past few hours wrestling with a small issue implementing file upload for Razor Pages. My bug-a-boo was a small thing that was easy to fix. However in the pursuit of fixing that little devil, I came to compare [File uploads in ASP.NET Core (with its sample)](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads) and the [Entropy Mvc.FileUpload sample](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.FileUpload/Controllers) to the code that I implemented, and the Razor Pages implementation is a bit different (and simpler :smile:) than what's in the docs now.

## Issues with Existing Topics/Samples

* Missing a comprehensive basic example [e.g., annotation for `Display(Name=)` with \<label>, validation message, get the file contents as text (`string`), delete *tmp* file]
* Missing a key feature of Razor Pages (*free* view model prop binding)
* Practices not applicable to Razor Pages (e.g., `IFormFile` parameter in post method sig, form routing with controller specified)

## Requests for new Topics

1. Write a **short** paragraph describing what the topic will cover.

   **Title**: *File uploads with ASP.NET Core Razor Pages*
   **TOC Title**: *File uploads*
   **Content**: Show a simple file upload scenario with Razor Pages *free* view model property binding, display name annotation, and validation [with validation message (server-side only)]. Provide a Razor Pages sample, and the sample should read the text of the file and shoot it back into the page (use EF with the in-memory dB). I recommend a pair of file upload \<input> elements and a textbox, but set them up for single file uploads. Refer to the existing *File uploads in ASP.NET Core* topic to cover the advanced scenarios: multiple files, streaming large files, IIS limit, etc.

2. Write an outline of the proposed topic contents.

   TBD

3. Where would you put the topic in the Table of Contents.

   **Docs / ASP.NET / ASP.NET Core / MVC / Tutorials / Create a Razor Pages web app /**

   *Docs/aspnetcore/tutorials/razor-pages/*

4. Who?

   *ME*, if you approve. I can knock this out PDQ after I get #1950 done.

5. Notes

   ```csharp
   public class FileUpload
   {
       [Required]
       public string Title { get; set; }

       [Required, Display(Name="Markup File")]
       public IFormFile UploadMarkupFile { get; set; }

       [Required, Display(Name="Text File")]
       public IFormFile UploadTextFile { get; set; }
   }
   ```
   ```css
   .danger {
       color: red
   }
   ```
   ```html
   <form method="post" enctype="multipart/form-data">
       <label asp-for="FileUpload.Title"></label>
       <input asp-for="FileUpload.Title" type="text">
       <span asp-validation-for="FileUpload.Title" class="danger"></span><br>

       <label asp-for="FileUpload.UploadMarkupFile"></label>
       <input asp-for="FileUpload.UploadMarkupFile" type="file">
       <span asp-validation-for="FileUpload.UploadMarkupFile" class="danger"></span><br>

       <label asp-for="FileUpload.UploadTextFile"></label>
       <input asp-for="FileUpload.UploadTextFile" type="file">
       <span asp-validation-for="FileUpload.UploadTextFile" class="danger"></span><br>

       <button type="submit">Upload</button>
   </form>
   ```
   ```csharp
   [BindProperty]
   public FileUpload FileUpload { get; set; }
   ```
   ```csharp
   public async Task<IActionResult> OnPostAsync()
   {
       if (!ModelState.IsValid)
       {
           return Page();
       }

       var documentData = await ProcessDocument(FileUpload.UploadMarkupFile);
       var markupFileText = documentData.HtmlEncodedText;

       documentData = await ProcessDocument(FileUpload.UploadTextFile);
       var textFileText = documentData.HtmlEncodedText;

       // Save the data into the in-memory dB so that it can be persisted and shot 
       // into the page.

       // Note: Don't trust FileUpload.UploadMarkupFile.FileName or 
       // FileUpload.UploadTextFile.FileName.

       return RedirectToPage("./Index");
   }
   ```
   ```csharp
   private static async Task<(long Size, string RawText, string HtmlEncodedText)> ProcessDocument(IFormFile documentFormFile)
   {
       var documentData = (Size: new long(), RawText: string.Empty, HtmlEncodedText: string.Empty);
        
       documentData.Size = documentFormFile.Length;

       var fullFilePath = Path.GetTempFileName();

       if (documentFormFile.Length > 0)
       {
           using (var stream = new FileStream(fullFilePath, FileMode.Create))
           {
               await documentFormFile.CopyToAsync(stream);
               stream.Position = 0;
               using (var reader = new StreamReader(stream))
               {
                   documentData.RawText = await reader.ReadToEndAsync();
                   documentData.HtmlEncodedText = WebUtility.HtmlEncode(documentData.RawText);
               }
           }
       }

       File.Delete(fullFilePath);

       return documentData;
   }
   ```

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #4188

[Review site link](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/uploading-files?branch=pr-en-us-4265)

Notes:
* There were a number of tiny changes to the current tutorial, but there was one significant change: I'm of the philosophy that lists of objects should be plural (but I left the dB table names singular), so I refactored the current sample a bit to accommodate that approach. It's a bit more satisfying to have: 
  * `_context.Movies.Add(Movie);` instead of `_context.Movie.Add(Movie);`
  * `_context.Movies.SingleOrDefaultAsync(...)` instead of `_context.Movie.SingleOrDefaultAsync(...)`
  * `@foreach (var item in Model.Movies)` instead of `@foreach (var item in Model.Movie)`
* I also moved the `RazorPagesMovie.cli.csproj` file out into a "snapshot" folder. When the sample has two project files, Bower is a big 'ole :bomb:. We can't assume a dev will download and necessarily know that they should kill that second project file before attempting to run the sample. btw-- I added the Bower and BundlerMinifer bits to make them work. I'm still a bit concerned about having such in samples, but the sample is complete and functional with them wired up to work.
* AFAIK the EF migrations work. I didn't run the entire tutorial from Step 1 (don't have VS installed here; I'm on VSC); however, the migrations did work locally with CLI `dotnet ef xxxx` commands. I assume the PS versions of the commands will be fine with PMC.

cc/ @danroth27 @DamianEdwards

### Outline
* Introduction
  * Purpose
  * Sample app (note file streaming for large files with a link)
  * Spec (two file uploads on the same POST; easy enough to downgrade to one, and this covers a common scenario with forms where a single multiple-file upload isn't appropriate)
* Add static helper method to handle the upload bits
* Add `Schedule` class to hold the movie schedule title and files' content
* Update the `MovieContext`
* Add `Schedule` table to the database with an EF migration
* Add a `FileUpload` class to bind to the view
* Add the file upload Razor Page
* Add the file upload code-behind
* Link the file upload Razor Page to the app's navigation
* Add a confirm delete page with code-behind
* Show the working file upload page with images
* Additional resources (include `IFormFile` interface)

### CODE REVIEW

**Comment by scottaddie** [comment]
@rynowak Please review

**Comment by scottaddie** [comment]
@guardrex Here's some feedback from @rynowak:
Two comments:

The code in FileHelpers should be dramatically simplified. IFormFile already has a length, and already does buffering to disk. This will just look like:

```csharp
using (var reader = new StreamReader(file.CreateReadStream(), Encoding.UTF8))
{
    return reader.ReadToEndAsync();
}
```

The scary warning about “don’t do this for real” in FileHelpers is not helpful for anyone. We should show customers code they can use. 

We already have limits in place about the size of uploads and form posts. We should show the code that validates the content type is expected and that the file encoding / file name is appropriate.

**Comment by guardrex** [comment]
@scottaddie I'll make another pass on it tomorrow afternoon.

**Comment by guardrex** [comment]
@scottaddie @rynowak PTAL Let's see if this is headed in the right direction.

* It became simpler with the updated `StreamReader` setup. It became more complex moving it to more of a real world example (i.e., file validations).
* In `ProcessSchedule`, I pass in the model state to generate an error on-the-fly if a check fails.
* Therefore, I perform two model state checks in `OnPostAsync`: The first check is to catch any quick attribute-based failures. If that's all good, I go on to processing the files looking for any other file-based violations. Coming back from `ProcessSchedule`, I perform a second `ModelState` check.
* In `ProcessSchedule`, I use a little reflection there with `MemberInfo` to grab the display name of the model property for the error messages so that magic strings aren't required.
* I cleanse the `FileName` property just a hair by encoding it so that it can become part of error messages. The user would still need to add additional checks if they have other requirements (e.g., store it in a dB, use it in other ways). However if you'd like to see more checks done/shown with `FileName`, let me know.

**Comment by guardrex** [comment]
@scottaddie Idk whaz up with that `adding-model.md` metadata violation. This PR doesn't touch that file AFAIK.

*aspnetcore/tutorials/first-mvc-app-mac/adding-model.md*

> unexpected type String for metadata helpviewer_keywords, the expected type is string[]

**Comment by blowdart** [comment]
```c#
typeof(FileUpload).GetProperty(scheduleFormFile.Name.Substring(scheduleFormFile.Name.IndexOf(".") + 1));
```

Oh no no get the file name by calling System.IO.Path.GetFileName rather than using substrings. I know the file name doesn't get used to persist to disk anywhere, but this, at least, shows people the right way to go about it should they ever want to.

**Comment by guardrex** [comment]
@blowdart I see that the `Name` prop is provided by the `Content-Disposition` header:
```
"form-data; name=\"FileUpload.UploadPublicSchedule\"; filename=\"ANSI.txt\""
```
The substring is there to split that, since I just want the property name. I do see how fragile this is, except that if `GetProperty` can't be passed anything that would :boom: it would null out and no-op (i.e., if the `Content-Disposition` header was missing, malformed, or hacked). You still want me to run it through `System.IO.Path.GetFileName` anyway? I still need to split it ... I guess `GetFileName` is still going to return `FileUpload.UploadPublicSchedule`.

Regarding the `FileName` prop, is this of concern? ...
```csharp
var fileName = WebUtility.HtmlEncode(scheduleFormFile.FileName);
```
Do you want me to do a `System.IO.Path.GetFileName` there on the `scheduleFormFile.FileName` before encoding it for the error message strings?

**Comment by guardrex** [comment]
I passed it something nonsensical to see what it would do, and this approach seems to trap anything that would go wrong (`property` nulls out) ...
```csharp
MemberInfo property = typeof(FileUpload).GetProperty("Geebers McScreebers!");

if (property != null)
{
    var dd = property.GetCustomAttribute(typeof(DisplayAttribute)) as DisplayAttribute;

    if (dd != null)
    {
        fieldDisplayName = $"{dd.Name} ";
    }
}
```
Therefore if the `Content-Disposition` header is missing, malformed, or hacked, shouldn't this be ok?
```csharp
MemberInfo property = typeof(FileUpload).GetProperty(scheduleFormFile.Name.Substring(scheduleFormFile.Name.IndexOf(".") + 1));
```

**Comment by blowdart** [comment]
If content-disposition is missing it's a bad file upload surely?

**Comment by blowdart** [comment]
I see what you're trying to do, it's just odd :)

Yea, put it in 

```
var fileName = WebUtility.HtmlEncode(System.IO.Path.GetFileName(scheduleFormFile.FileName));
```

And add a comment saying this will strip any path information passed as part of the filename?

**Comment by guardrex** [comment]
> If content-disposition is missing it's a bad file upload surely?

True, but even the MVC topic, [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads), doesn't get into the weeds. I guess the idea when that topic was written is that if the file upload fails internally (inside of the implementation behind `IFormFile`) that it will error out just like anything else.

I am concerned about any way possible that a hacker could break this code. I *think* the latest commit with the `GetProperty` won't break, but I'd like some dev team backup on that notion.

> And add a comment saying this will strip any path information passed as part of the filename?

I did add the `System.IO.Path.GetFileName` on the last commit. I'll add a note next.

**Comment by guardrex** [comment]
> it's just odd

:grinning: ... you would prefer a magic string passed in to get the field name for the error message???

**Comment by Rick-Anderson** [comment]
@guardrex  @scottaddie  what's left to get this published?

**Comment by guardrex** [comment]
AFAIK it just needs a final review+sign-off.

There was just some minor concerns earlier about exactly what to show, since these also become recommendations on how to do things.

I favor passing in the model state now and faulting it in the file upload processor method that I built. I also try to avoid a magic string for the faulting control with a smidgen of `MemberInfo`.

I'm free over the next few days, so just let me know if anything needs to change, and I'll jump right on it.

**Comment by Rick-Anderson** [comment]
@scottaddie  looks like this is ready to merge?

**Comment by scottaddie** [comment]
@blowdart Anything else you'd like addressed in this PR?

**Comment by blowdart** [comment]
Nope

**Pull request merged**
