### PR TITLE
Deleted some weird anchor tags in the Configuration topic

### PR DESCRIPTION
**Pull request by Rabadash8820**
I found four weird <a> tags floating around on the Configuration topic.  These were probably supposed to serve some purpose, so deleting them may not be the appropriate fix, but I just wanted to call attention to them.

Suggested Reviewers:
- @Rick-Anderson
- @ardalis
- @danroth27
- @guardrex

### CODE REVIEW

**Comment by guardrex** [comment]
@Rabadash8820 Removing them may (probably) break anchor links to these parts of the topic. The build report might* indicate if removing them breaks anything.

might* = there is an issue under investigation on faulty CI reporting on bookmark links.

**Comment by Rabadash8820** [comment]
@guardrex  There were indeed a whopping 79 warnings about "Illegal links" in the build report.  I don't really understand how the `<a name="something"></a>` pattern is supposed to work; why does it stay visible on the published topic page?

**Comment by guardrex** [comment]
@Rabadash8820 Correct, those anchors are not supposed to be visible. They're just showing up right now  because the CI is acting up a bit. Those will become hidden again after they fix the build. There's an internal issue tracking the work. Shouldn't take them long to fix it ... maybe even this evening.

**Comment by Rabadash8820** [comment]
@guardrex  Ah, gotcha.  Well I guess I'll close this issue then.

**Pull request closed without merging**
