### PR TITLE
Update sample to work with RTM

### PR DESCRIPTION
**Pull request by pranavkm**
Modify sample for dependency-injection

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @danroth27 \ @Rick-Anderson

**Comment by danroth27** [comment]
@pranavkm Thanks for updating the sample! Did you also take a look at the .rst file? Do any of the literalincludes need to be updated? Does the prose correctly reflect the sample and the 1.0.0 bits?

**Comment by pranavkm** [comment]
Yup, fixed the line numbers.

**Comment by Rick-Anderson** [comment]
:shipit:

**Pull request merged**
