### PR TITLE
C47295: Deleting extra tabs

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @tfitzmac,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description of the source issue: Extra tabs causing content to be untranslated.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by tfitzmac** [comment]
@v-makoud - it looks fine to me but I am not able to merge it. I have not worked on these articles for years.

@Rick-Anderson - do you know who can merge this?

**Comment by Rick-Anderson** [comment]
@tfitzmac 	I'll do a PR and replace all of

```
author: tfitzmac
ms.author: riande
```

with

```
author: Rick-Anderson 
ms.author: riande
```

**Comment by Rick-Anderson** [comment]
@v-makoud 	Thanks for the PR.

**Comment by tfitzmac** [comment]
@Rick-Anderson - thanks!

**Pull request merged**
