### PR TITLE
Fixes - Custom Provider in Localization doc doesn't provide sufficient information

### PR DESCRIPTION
**Pull request by siddharthashw**
Fixes - #3280 

File Change : 
1. localization.md - updated the point of custom provider

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@siddharthashw  can you propose this change at https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Startup.cs#L70

We copy their code.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can you suggest a way to update the text to get this point across. It looks like his code notes are not complete.

**Comment by siddharthashw** [comment]
If current culture of my application is en-US and and I want to configure my application for 'fr' and 'en-US'. Then I don't need to add 

    new CultureInfo("en-US")
    new CultureInfo("fr")

As if, I do so, my application will not be able to recognize the .resx of fr. It will always read .resx of en-US. My application was not able to get value from Controllers.HomeController.fr.resx for `IStringLocalizer<HomeController>`

You can have look on my code snippet of #3280

**Comment by siddharthashw** [comment]
@Rick-Anderson , I have updated the README.md file. In hope that now it will be clear for you.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  please review change.

**Comment by ryanbrandenburg** [comment]
I'm still unclear what exactly this PR is meant to fix. It reads to me like the issue you linked said that the problem was that that snipped lead to not actually being able to get `fr` as a culture (I assume because it always selected `en`). I haven't actually tried it but I doubt adding `fr` twice would fix that problem.

Further, we don't want to tell people to not include their "current culture" in SupportedCultures, because in general that's not a safe assumption. For example, imagine you were working with someone who primarily speaks spanish and they try to run your code, now "en-US" isn't a supported culture and they're likely to run into problems.

Perhaps I'm misunderstanding the intent/ask here?

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  I'm not clear either but I did figure out this seems to be a special case of the  custom provider sample code - not the code used in the article.  Does that help?

**Comment by siddharthashw** [comment]
@ryanbrandenburg 
>I haven't actually tried it but I doubt adding fr twice would fix that problem.

Why I should do this twice. This is not fruitful way for solution

>For example, imagine you were working with someone who primarily speaks spanish and they try to run your code, now "en-US" isn't a supported culture and they're likely to run into problems.

If someone is primarily using spanish for there application as current-culture then they try to run your code, now "en-US", so for that they have to register en-US for there application but they don't need to register spanish for there application. This is what I am trying to explain.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg can you respond?

**Comment by ryanbrandenburg** [comment]
I'm not suggesting that you add the french culture twice, I'm pointing out that what your PR currently does is add it twice, and that's not something we want to tell people to do.

I am saying that the guidance we want to give people is to include in supportedCultures ANY culture that they want to support. We don't want people relying on the application culture or local culture of the machine or anything like that because it leads to unexpected behavior when switching machines..

**Comment by siddharthashw** [comment]
The only thing that I would like to suggest is that you don't need add pre-supported culture. whether it is ANY culture.

>We don't want people relying on the application culture or local culture of the machine or anything like that because it leads to unexpected behavior when switching machines

@ryanbrandenburg - You don't want it but unfortunately, the application takes the application or local culture as default. And I work and behave like - #3280 

So its guideline for user not to add their application culture. Look there are may be two options
1. >I haven't actually tried it but I doubt adding fr twice would fix that problem.
as you stated
or 
2. >As my PR is instructing.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg I've cleaned up the comments. I think @siddharthashw  is right, you don't need to add your culture. Can you take a look at the changes?

**Comment by siddharthashw** [comment]
@Rick-Anderson , I hope now you get my point.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can you look at my latest changes? Is this useful or should I close the PR?

**Comment by dougbu** [comment]
@siddharthashw @Rick-Anderson we have seen problems and received bug reports when users follow this new recommendation. If for example developers move from a machine with one default locale to another, the deployed site will start failing for the previous default locale.

So, why recommend a pit of failure? Being explicit about _all_ supported cultures does not cause problems and avoids these potential failures.

**Pull request closed without merging**
