### PR TITLE
Adding ASP.NET 5 Documentation survey.

### PR DESCRIPTION
**Pull request by Erikre**

### CODE REVIEW

**Comment by Erikre** [comment]
Please review @Rick-Anderson, @TomArcher, @danroth27.

**Comment by Rick-Anderson** [comment]
Looks good to me.

**Comment by Erikre** [comment]
@danroth27 please confirm this PR. Thanks

**Comment by Erikre** [comment]
@danroth27 please confirm this PR. Thanks

**Comment by danroth27** [comment]
a14467740077572575d8031948060eb9636e3b55

**Pull request closed without merging**
