### PR TITLE
Fix links and anchors

### LINKED ISSUE #2633: Find and fix broken links in docs
Originally created to report search engine results containing an old URL for the Custom Formatters stub topic, the issue has been repurposed as a general find-and-fix issue for broken links in articles.

### PR DESCRIPTION
**Pull request by GuardRex**
Fixes #2633

I can't fix these two:

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro
The BenMcClintock circle image link in Contributors: It should go from `https://github.com/DunNZ` to `https://github.com/BenMcClintock`.

capture

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api
The Adham circle image link in Contributors: I think it should go from `https://github.com/Qudware` to `https://github.com/Biarity`.

capture1

Also, I was able to see the 301/302 report that Xenu produced. It's ..... uh .... um .... uh ...... let's talk about *something else*. :grin:

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@GuardRex  which section is correct?
image

**Comment by GuardRex** [comment]
@Rick-Anderson The problem (I think) was just that the Azure link in that section had an "en-us" in it that I removed.

**Comment by GuardRex** [comment]
That's been moved to the last line under *Publishing and deployment*, where you can see the "en-us" in the link.

**Comment by Rick-Anderson** [comment]
Can't I just delete
image
and leave the remaining?

**Comment by Rick-Anderson** [comment]
@tdykstra  please advise

**Comment by GuardRex** [comment]
Let me try to revert my change and see if that breaks the conflict. brb

**Comment by GuardRex** [comment]
Looks like that worked. It wasn't "en-us" ... it was a stray ".md" on the end. Since he changed that link completely, that prob went away.

**Comment by Rick-Anderson** [comment]
@GuardRex  I'll merge this after are aspnet migration to prevent merge issues.
cc @tdykstra

**Comment by Rick-Anderson** [comment]
@GuardRex  if you can revert the commit that is causing the merge conflict, I can merge this.

**Comment by GuardRex** [comment]
@Rick-Anderson I did (not the commit but the change, which should have had the same effect). It's showing "All checks passed here" ... is there still a merge conflict?

**Comment by GuardRex** [comment]
Oh, wait. I see another problem ... a warning. Let me fix that. brb

**Comment by GuardRex** [comment]
Ok, I think we're good now. I need to re-train my brain that "All checks have passed" really means "All checks MAY have passed ... you better look at the build report (you **GooberRex:tm:** :grin:)

**Pull request merged**
