### PR TITLE
Update create-an-aspnet-mvc-5-web-app-with-email-confirmation-and-pas…

### LINKED ISSUE #6268: Sendgrid section is outdated in email confirmation for MVC 5 app
## Sendgrid section not updated with the V3 API code 

In the below article the "Hook Up Sendgrid" section is not updated yet,it's still following the old V2 API code. Currently Sendgrid uses API_KEY which is also not mentioned in the document. Please see the link below.
[Outdated section](https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-web-app-with-email-confirmation-and-password-reset#hook-up-sendgrid)

I have updated a similar document for .NET Core like below before -
https://docs.microsoft.com/en-us/azure/sendgrid-dotnet-how-to-send-email 

let me know if I can submit a PR for this.

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #6268 
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-web-app-with-email-confirmation-and-password-reset?branch=pr-en-us-9235#hook-up-sendgrid)

### CODE REVIEW

**Comment by Niladri24dutta** [comment]
@Rick-Anderson Sorry I completely forgot about this , I was planning to raise this PR as part of Hacktoberfest this year, but anyway I have posted a stackoverflow answer for this code. Let me know if it can be included here.  
https://stackoverflow.com/questions/52804597/mvc-azure-sendgrid/52805745#52805745

**Comment by Niladri24dutta** [comment]
@Rick-Anderson However there is a small change in the ClickTracking code of this .net core sample . https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=visual-studio#configure-email-provider . Currently it's recommended to use  `SetClickTracking` method to set the preference instead directly accessing the property to enable it.

**Comment by Rick-Anderson** [comment]
> Should I update it?

Yes, thanks.

**Comment by Niladri24dutta** [comment]
@Rick-Anderson updated the code in PR #9325

**Pull request merged**
