### PR TITLE
Update validation.md

### PR DESCRIPTION
**Pull request by yimogit**
Added description of default model validation
by https://github.com/aspnet/AspNetCore/issues/3485

@Rick-Anderson 	edit: 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-1.0&branch=pr-en-us-9262#handling-model-state-errors)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@dougbu please review aspnet/AspNetCore#3485. The snippet is not in the right place and the wording isn't correct. Please suggest proper wording.

**Comment by dougbu** [comment]
@Rick-Anderson I'm not sure of the proper way to word this. But, I agree the current wording is misleading.

Custom validations are still supported -- no change in 2.1. Further, the `SuppressModelStateInvalidFilter` setting has no effect on validations. Instead, it ensures requests which contain invalid data (i.e. `ModelState.IsValid` is false) automatically result in a 400 response and never reach your action.

The other important point here is that the filter doing this work isn't applied unless `[ApiController]` is associated with the controller containing the action.

**Comment by Rick-Anderson** [comment]
@dougbu is there anything that needs to be documented on this?

**Comment by dougbu** [comment]
> is there anything that needs to be documented on this?

Yes, should document the *actual* case where `SuppressModelStateInvalidFilter` makes sense and the tie between that property and `[ApiController]`. Suppressing this filter is useful if your action can recover from a model state error or wishes to customize its response. (Again, custom validators are identical to other validators for these scenarios.)

**Pull request closed without merging**
