### PR TITLE
Update UseIdentity with UseAuthentication

### PR DESCRIPTION
**Pull request by isaac2004**
Fix for #4472 

- Application Startup in ASP.NET Core

Update Sample to update UseIdentity() call to UseAuthentication()

### CODE REVIEW

**Comment by isaac2004** [comment]
@Rick-Anderson this is small fix for one task in #4472

**Comment by Rick-Anderson** [comment]
@scottaddie  please review

**Comment by scottaddie** [comment]
@isaac2004 We still need to show the 1.x samples in the docs. Because of that, I recommend making these changes in a new sample app.

**Comment by isaac2004** [comment]
closing per conversation with @scottaddie

**Pull request closed without merging**
