### PR TITLE
Using services to configure options

### LINKED ISSUE #10553: Add a doc on how to use services from DI when configuring options
The current [Options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options) topic is mostly of reference of everything you can do with options. We need a doc that is more task oriented that helps users figure out how to access DI services when configuring options for various components.

@Rick-Anderson  edit:
27 K PV, 50% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by rynowak**
Improves the exising docs for this area and changes the title so it's
easier to find.

### CODE REVIEW

**Comment by guardrex** [comment]
@rynowak Does this also resolve https://github.com/aspnet/Docs/issues/10392?

Also, just to confirm it from the title: Does this fully resolve #10553? It seems like the ask goes a bit further to reorganize/refocus the whole topic.

**Comment by rynowak** [comment]
#10392 seems to recommend that you write a class to configure options. I don't think we'd recommend that over the simpler options.  If you think it's really important to have an example, I can add one since I already have a few. 

#10553  says

> We need a doc that is more task oriented that **helps users figure out how to access DI services when configuring options for various components.**

I think it does this now.

Rewriting this doc is out of scope for what I'm prepared to do. I'd be happy to see this merged and leave the work item open if that what you'd prefer.

**Comment by guardrex** [comment]
>  If you think it's really important to have an example

Let's ask @HaoK ... Should we keep (and work) #10392 separately, take @rynowak up on his offer of an example (probably as a new section in the topic), or close that issue?

> if that what you'd prefer

I think that I agree ... in a biased kind of way given that I wrote it under @HaoK's :eye:. I just want to make sure that @danroth27 is 😀. If @danroth27 is calling for a different organization/approach/examples, then I'd like to take a stab at resolving his concerns separately from this PR. Let's merge, and I'll follow-up with further work on #10553 later.

**Comment by HaoK** [comment]
This looks fine, the class was needed before 2.1 when we added the Configure overloads that take up to 5 services

**Comment by guardrex** [comment]
Cool ...

> was needed before

I'm working to 🏃 catch-up 🏃 on older-ish issues before 3.0 hits. Sorry for any delays on our side. 😅

For now, let's leave this as ...

Addresses #10553 

If he doesn't respond here, I'll take up #10553 with @danroth27 shortly.

Stand-by ... I'll UE and *grammarize*:tm: this now and get it in.

**Comment by guardrex** [comment]
@rynowak I re-organized a bit placing the reasoning for going with the first approach in a new paragraph. See if I botched anything on the update.

**Pull request merged**
