### PR TITLE
Enhance Configuration topic DI and startup remarks

### LINKED ISSUE #11265: Config retrieval examples
From the GetValue section and onward, the examples use a "config" object. However, there is no guidance or examples on how to actually get a config object. It would be helpful to show a complete example.

It is not clear if configs are available in the ConfigureServices() context when is called after CreateDefaultBuilder(). 
Or if it is necessary to wait for Startup to access the IConfiguration object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#configureappconfiguration)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #11265 

Thanks @gaziqbal.

### CODE REVIEW

**Comment by guardrex** [comment]
Yeah, I agree with you @gaziqbal ... stand-by ... I'll repeat that. It takes *a long time* to read past all of the config providers. The reader may lose track of how to get the values out by the time they get to `GetValue`. The first example there can repeat it. Commit on the way ..........

**Comment by guardrex** [comment]
@gaziqbal It's a repeat, but it isn't an exact repeat given that this time it stores the value in a page model property. It's a reminder after reading a 🚢 *sea of text* 🚢 on providers how the DI works. I think after this point, the reader should be ok with the rest of the examples. Do you concur?

**Comment by guardrex** [comment]
I don't repeat anything from providers. The reader was just exposed to all of them, and there are plenty of examples in those sections. I'm more concerned about them getting lost on getting the values out.

**Comment by gaziqbal** [comment]
Thank you!

**Pull request merged**
