### PR TITLE
Remove redunant "dotnet restore"

### PR DESCRIPTION
**Pull request by mikeharder**
"dotnet new" automatically runs "dotnet restore" unless the "--no-restore" option is passed: 

```
> dotnet new web
Getting ready...
The template "ASP.NET Core Empty" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/template-3pn for details.

Processing post-creation actions...
Running 'dotnet restore' on C:\Temp\aspnetcoreapp\aspnetcoreapp.csproj...
  Restoring packages for C:\Temp\aspnetcoreapp\aspnetcoreapp.csproj...
  Generating MSBuild file C:\Temp\aspnetcoreapp\obj\aspnetcoreapp.csproj.nuget.g.props.
  Generating MSBuild file C:\Temp\aspnetcoreapp\obj\aspnetcoreapp.csproj.nuget.g.targets.
  Restore completed in 7.22 sec for C:\Temp\aspnetcoreapp\aspnetcoreapp.csproj.
```

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@mikeharder  Do you want me to add `ASP.NET Core 1.x` and `ASP.NET Core 2.x` tabs. You still need restore for 1.x - right? See [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?tabs=aspnet1x#add-support-for-entity-framework-core) doc

image

**Comment by mikeharder** [comment]
The extra `dotnet restore` doesn't hurt anything on 2.0, but it's also not necessary.  So the question is whether it's better to simplify the 2.X instructions at the expense of needing different instructions for 1.X, or just use a single set of instructions which contain a redundant step on 2.X.

I would lean towards keeping a single set of instructions, since learning about `dotnet restore` may be useful for other scenarios, even if it's not needed after `dotnet new` on 2.X.  Another option would be to add a note to the `dotnet restore` step that it's not required on 2.X.

But I defer to your judgement on which is better overall.  I don't want to over-complicate the "Getting Started" page, but someone using the current docs on 2.X may question why they are told to restore twice.

**Comment by Rick-Anderson** [comment]
@mikeharder  created #3793  - I think a bigger problem for windows is it sends you to the VS 2017 installer, not the CLI installer.

**Comment by Rick-Anderson** [comment]
@mikeharder  also note on this page I had to add the following because of folks running older versions and following this tutorial:

 Notes: 
    - Previous versions of .NET Core required a `t` parameter, that is   `dotnet new -t web`. If you get an error running `dotnet new web`, install the latest [.NET Core](https://microsoft.com/net/core).  `dotnet` (with no parameters)  will display the .NET Core version.

**Pull request closed without merging**
