### PR TITLE
Updated to clarify the instructions about how to start the app

### PR DESCRIPTION
**Pull request by christianhxc**
Documentation it's unclear about how to run the app (Copy over your app), I also have uploaded a sample app on Github with some instructions (simple TODO Api), here's the repo: https://github.com/christianhxc/dotnetcore-todoapi

### CODE REVIEW

**Comment by christianhxc** [comment]
I will also include some instructions on how to clean up everything to remove the source code from the server.

**Comment by danroth27** [comment]
Using `dotnet restore` and `dotnet run` from source is how you would typically run your app during development, but for deployment to a production server the recommendation is to run `dotnet publish`, which will collect all of the runtime artifacts needed by your app into a single folder. This folder can then be copied to the production server.

**Comment by christianhxc** [comment]
@danroth27 thanks for the clarification, I did tried that but couldn't figure out how to start the app, I tried to do it with `dotnet run` but I was getting an error, might be because I was not in the correct folder. Could you clarify that part or give me a link for reference? Thanks!

**Comment by GuardRex** [comment]
It's in the opening of https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/index

**Comment by christianhxc** [comment]
@GuardRex thanks! but unfortunately I still don't get how to start up the application to run in port 5000 (default). Previous version of this documentation was referring to a communication between sockets, not about starting the app as self hosted, which is better @danroth27?

**Comment by christianhxc** [comment]
I think this might be the answer to my question http://stackoverflow.com/questions/37376880/net-cli-how-to-run-app-after-publish-on-linux

**Comment by christianhxc** [comment]
I guess the only thing I was doing wrong is that instead of `dotnet run` I just need to do `dotnet projectname.dll` in the root folder of the files that the publish command generated.

**Comment by danroth27** [comment]
To run a published app you simple run `dotnet <path-to-assembly>`. You can see this done in the [Configuring Supervisor](https://docs.asp.net/en/latest/publishing/linuxproduction.html#configuring-supervisor) section:

```bash
command=bash /usr/bin/dotnet /var/aspnetcore/HelloMVC/HelloMVC.dll
```

**Comment by davidfowl** [comment]
why is bash there?

**Comment by danroth27** [comment]
Not sure - maybe it isn't needed? @shirhatti ?

**Comment by shirhatti** [comment]
Oops! That's an artifact of the old document that executed a shell script. @davidfowl is right, it needn't be there.

**Comment by danroth27** [comment]
@Rick-Anderson 

@shirhatti Could you please open a doc issue with the change that we should make? Do we just need to remove "bash"? Or you could just PR the change yourself :smile:

**Comment by danroth27** [comment]
Looks like an external contributor has already fixed this for us: https://github.com/aspnet/Docs/pull/1646

**Pull request closed without merging**
