### PR TITLE
add a note about UseIdentity() being first in order

### PR DESCRIPTION
**Pull request by Vaiune**
Social Logins page should have a note about calling order according to https://github.com/aspnet/Identity/issues/1036
@Rick-Anderson

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/security/authentication/sociallogins.md](https://github.com/Vaiune/Docs/blob/master/aspnetcore/security/authentication/sociallogins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C29%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611290108303948-2264%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@halter73 please review related to https://github.com/aspnet/Identity/issues/1036

**Comment by halter73** [comment]
LGTM.

**Comment by Rick-Anderson** [comment]
@Vaiune Thanks!

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/security/authentication/sociallogins.md](https://github.com/Vaiune/Docs/blob/master/aspnetcore/security/authentication/sociallogins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C30%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611300000096476-2264%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/security/authentication/sociallogins.md](https://github.com/Vaiune/Docs/blob/master/aspnetcore/security/authentication/sociallogins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C30%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611300001004766-2264%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
