### PR TITLE
Metadata updates for the Razor Pages docs

### PR DESCRIPTION
**Pull request by scottaddie**
Addresses #6541 

Moves the *razor-pages* folder out of the *mvc* folder and into the root level. This simplifies the glob pattern in *docfx.json* which is used for the metadata updates. Also had to modify the uid value in each Razor Pages doc to get the build working properly. Redirects were added to support the uid changes.

### CODE REVIEW

**Comment by guardrex** [comment]
Revised metadata?

```
 ---
 title: xxxxx
 author: xxxxx
 description: xxxxx
 monikerRange: '>= aspnetcore-X.Y'
 ms.author: xxxxx
 ms.date: 00/00/0000
 uid: xxxxx
 ---
```
No `ms.custom: mvc`?

**Comment by scottaddie** [comment]
@guardrex This PR is part of a larger, APEX-wide metadata cleanup initiative. The metadata values I've removed from the individual files are now found in *docfx.json*.

**Comment by guardrex** [comment]
I don't think https://github.com/aspnet/Docs/pull/7123 will break what you're doing here. If you prefer I hold off, I can rebuild that PR easily enough after you merge this one. If we go the other way tho ... :boom:.

**Comment by guardrex** [comment]
I owe u a bottle for that one. :beer: :smile:

**Comment by scottaddie** [comment]
@guardrex No worries. Thanks for all your great work.

**Comment by scottaddie** [comment]
@Rick-Anderson Ready for your review. Had to rebase a few times.

**Pull request merged**
