### PR TITLE
.csproj

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Andrew-MSFT @balachir please review new .csproj language

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/using-gulp.md](https://github.com/aspnet/Docs/blob/Rick-Anderson-patch-3/aspnetcore/client-side/using-gulp.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/using-gulp.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611160255287277-2180%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/using-gulp.md](https://github.com/aspnet/Docs/blob/Rick-Anderson-patch-3/aspnetcore/client-side/using-gulp.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/using-gulp.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611160255569715-2180%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
per danroth, not adding new .csproj lang until next year

**Pull request closed without merging**
