### PR TITLE
"fix" code sample

### PR DESCRIPTION
**Pull request by TheBeardedLlama**
code fix

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@blowdart  this looks right, can you or @HaoK approve?

**Comment by HaoK** [comment]
This is correct for 2.0, do we need to have the 1.x vs 2.0 tab for this example to account for the breaking change in 2.0?

**Comment by Rick-Anderson** [comment]
@HaoK  added tabs. cc/ @scottaddie

**Comment by Rick-Anderson** [comment]
@TheBeardedLlama Thanks!

**Pull request merged**
