### PR TITLE
Corrections to sociallogins.rst

### PR DESCRIPTION
**Pull request by glen-84**
Other notes:

1. There is a mix of "Create" and "Creating" (+ "Running" etc.) for the section titles, which could maybe be made more consistent.
2. "Add your Site URL" is mentioned twice. The second time "Add" is also incorrectly capitalized.
3. You might want to mention hitting "Save Changes" on FB.
4. "Set the Facebook AppSecret" shows using the AppId again – maybe use placeholder text like YOUR_APP_SECRET_HERE.

### CODE REVIEW

**Comment by danroth27** [comment]
@rustd

**Comment by rustd** [comment]
:shipit:

**Comment by danroth27** [comment]
Thanks!

**Comment by glen-84** [comment]
@danroth27 The items listed in my initial comment are not included in the PR, as they would require input from yourself (or others on the team). I understand if you're not ready to make such changes, I just wanted to clarify in case you missed the feedback. :-)

**Comment by danroth27** [comment]
Ah, thanks for pointing that out! Opened https://github.com/aspnet/Docs/issues/287 to track this additional feedback and assigned to @rustd to take a look.

**Comment by glen-84** [comment]
Perfect, thanks Dan.

**Pull request merged**
