### PR TITLE
Web API refactor and remove repository

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api-mac?branch=ra-webAPI-ez)
Intro lists all 3 versions so it's easy to pop around. Just needs a quick reality check. Easiest approach is to compare review URL of each version to the live version.  

- Removed repository.
- Refactored.
- Removed Key and other EF artifacts.

### CODE REVIEW

**Comment by tdykstra** [comment]
When I started to look at this I realized there are a number of TOC issues, but I think it may make sense to address them in a separate issue and PR.  Created #3407

**Comment by Rick-Anderson** [comment]
@tdykstra  I did a careful comparison. OK to merge?

**Comment by tdykstra** [comment]
@Rick-Anderson Yes, and I'll do a review after the fact when I have time.  When you have a chance, take a look at the TOC issue, as this is going to create some confusion it would be nice to clear up soon.

**Comment by Rick-Anderson** [comment]
@tdykstra  I'll fix the TOC issue today.

**Pull request merged**
