### PR TITLE
Review Request

### PR DESCRIPTION
**Pull request by ardalis**

### CODE REVIEW

**Comment by danroth27** [comment]
Is this just a whitespace change?

**Comment by ardalis** [comment]
The whole article needs reviewed - I made the change so I could issue the PR.

**Comment by danroth27** [comment]
This PR doesn't have the diff for me to review. Let's just close this one and I will review the content in the closed PR: https://github.com/aspnet/Docs/pull/5

**Comment by ardalis** [comment]
Sounds good.

**Pull request closed without merging**
