### PR TITLE
Emphasize on related article

### PR DESCRIPTION
**Pull request by sebastienros**
Based on comments, make it clear that this article does not cover basic example of routing, which the commentators where looking for.

Fixing #2429

### CODE REVIEW

**Comment by tdykstra** [comment]
@sebastienros Making this more prominent makes sense, but "warning" sounds too strong  - what do you think of making it a "note" instead?

**Comment by sebastienros** [comment]
I was expecting this comment. I can change it to the way you want. Is that what you want, a note? Or any other style?

**Comment by tdykstra** [comment]
[!NOTE] would work, or if you want to make it a bit stronger, [!IMPORTANT].

**Comment by sebastienros** [comment]
updataed

**Pull request merged**
