### PR TITLE
Update windows-service.md

### PR DESCRIPTION
**Pull request by eyal7773**
I offer to insert an instruction to validate the the AspNetCore project is configured as "Windows Application", becuase if it configured as "Console Application" - so when the developer will try to start service with "sc start....", he will got an error : "the service did not respond to the start or control request in a timely fashion "

 Fixes #1386

Thanks
Eyal

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@eyal7773  do you know the related issue, 1386 is not correct.

**Comment by guardrex** [comment]
Thanks @eyal7773 ... I'll take a look at this by the end of the day.

**Comment by guardrex** [comment]
Sorry @eyal7773 ... I didn't get to this yesterday. I'll try again today. 🏃😅

**Comment by guardrex** [comment]
Hello @eyal7773 ... I finally just got free to take a look. I think the problem is that you either aren't publishing in VS or you aren't using the published output from a VS folder publish.

Leave the output type set to "Console Application" for your test here:

1. Select **Build** > **Publish &lt;YourAppName&gt;**.
1. Select the **FolderProfile**.
1. Select the **Publish** button.

It will publish and output the path ...

```
Web App was published successfully
file:///C:/_apps/WindowsServiceSample/bin/Release/netcoreapp2.1/win7-x64/publish/
```

Use that path for your `sc create` and `sc start` commands. It should work. Let me know how it goes.

For the topic, I think where it says ...

> 1. Publish the app. Use \[dotnet publish](/dotnet/articles/core/tools/dotnet-publish) or a \[Visual Studio publish profile](xref:host-and-deploy/visual-studio-publish-profiles).

... we should make it say ...

> 1. Publish the app. Use \[dotnet publish](/dotnet/articles/core/tools/dotnet-publish) or a \[Visual Studio publish profile](xref:host-and-deploy/visual-studio-publish-profiles). When using a Visual Studio, select the \*\*FolderProfile\*\*.

That's :point_up: a cut-and-paste for the line if you'd like to swap the change you made earlier for this one, then I can merge your PR.

After that, it should all :sparkles: **_Just Work_**:tm: :sparkles:. A few steps later, the reader will see that the path is to the *publish* folder ... same situation as when not using VS (e.g., VSC or command-line).

**Comment by guardrex** [comment]
That's interesting, because when you set that in the property page in VS (before you published from a command prompt) what it's doing is setting the `OutputType` to `WinExe` in the project file ...

```xml
<OutputType>WinExe</OutputType>
```

... and that's not the Windows Service configuration guidance that we received from the engineer.

You're sure you're using the path to the *publish* folder when you create the service? It really should work with an `OutputType` of `Exe`, which is what's used when `OutputType` isn't specified in the project file. There might be something else going on that makes it work in your case, but we'll need to check with the engineer to explore that further.

First, set the `OutputType` to `Exe` (if present in the project file; if not present, you don't need to set it), then publish (`dotnet publish -c Release`), then create the service (confirm ur using the path that includes the *publish* directory), and try to start it again.

```console
sc create MyService binPath= "c:\my_services\AspNetCoreService\bin\Release\netcoreapp2.1\win7-x64\publish\AspNetCoreService.exe"
```

... and I need to make one more change. The RID is missing from the line in the topic, so I'll add that at the same time as making the update above.

**Comment by guardrex** [comment]
@eyal7773 Would you mind reviewing and signing the CLA :point_up: if you agree with terms. We can't accept the PR until the CLA is signed.

**Comment by guardrex** [comment]
Moved to #7863

**Pull request closed without merging**
