### PR TITLE
Migrate Bower article

### PR DESCRIPTION
**Pull request by MikeWasson**

### CODE REVIEW

**Comment by danroth27** [comment]
@madskristensen @DamianEdwards Please review.

**Comment by madskristensen** [comment]
Minor correction: Bower packages are installed when bower.json is saved. No need to right-click in solution explorer.

**Comment by MikeWasson** [comment]
In the first walk-through, shouldn't we modify index.cshtml instead of adding a static index.html, since this built on the Starter Web project?

**Comment by MikeWasson** [comment]
Also - In "Exploring the Client Build Process", I'd like to see more explanation for what's happening. Why do we need NPM, what is the bower grunt task for, why are we copying files from bower_components to wwwroot?

I can add some of that after we accept this PR.

**Comment by ardalis** [comment]
I think the version of VS used when these were written (CTP 6, I believe) may have had some problems auto-reloading dependencies on save. It's worth noting somewhere that the user can force a package install from solution explorer, but agreed these steps can be omitted.

**Comment by ardalis** [comment]
@MikeWasson I think a new file was used to eliminate the need to work with razor or views, reducing the concept count for the article.

**Comment by ardalis** [comment]
@MikeWasson since this is your PR, can you make the updates you and Mads noted here and commit them, so that we can accept the PR? We can note any other changes that are necessary as issues afterward. Thanks.

**Pull request merged**
