### PR TITLE
Fix title case.

### PR DESCRIPTION
**Pull request by cesarbs**
cc @danroth27

### CODE REVIEW

**Comment by danroth27** [comment]
@Rick-Anderson What is the official word on where we are using title casing in the docs? Should we be using title casing for titles and sentence casing for sections?

**Comment by Rick-Anderson** [comment]
@cesarbs MS modern style is to use sentence casing for titles.

**Comment by cesarbs** [comment]
Then we need to fix all other titles :grin:

**Comment by danroth27** [comment]
Yup :-) And we need to update our style guide.

**Comment by Rick-Anderson** [comment]
I'll create a P9 issue.

**Pull request closed without merging**
