### PR TITLE
Fix typo & snippet

### PR DESCRIPTION
**Pull request by charliethinker**
add the escape character.

before:

after:

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/charliethinker/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C24%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611240326495338-2242%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/charliethinker/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md) | :white_check_mark:Succeeded | |
[aspnetcore/tutorials/first-mvc-app/start-mvc/sample2/src/MvcMovie/Controllers/MoviesController.cs](https://github.com/charliethinker/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc/sample2/src/MvcMovie/Controllers/MoviesController.cs) | :white_check_mark:Succeeded | |
[aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/charliethinker/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C26%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611260516587546-2242%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charliethinker** [comment]
Fix snippet.

BEFORE:
-


AFTER:
-

**Comment by Rick-Anderson** [comment]
@charliethinker  can you fix the merge conflict?

**Comment by charliethinker** [comment]
I have resubmitted the PR.

**Pull request closed without merging**
