### PR TITLE
Update sociallogins.rst

### PR DESCRIPTION
**Pull request by leastprivilege**
add important background info

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@leastprivilege  if you can come up with a paragraph I'll update the article - something like
FB OAuth implement a form of OpenID Connect id tokens.
Google implements OpenID Connect 
Twitter ..
LinkedIn
Microsoft ..

@MikeWasson @rustd  - Also, how would you rewrite how to build an ASP.NET 5 Web application that enables users to log in using OAuth 2.0 with credentials from an external authentication provider, such as FB, Goog, etc

**Comment by PinpointTownes** [comment]
Much trolling here :trollface: 

On a more serious note, it might be a good idea to mention that additional providers for OAuth2/OpenID2 can be found on aspnet-contrib: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers and https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers

**Comment by Rick-Anderson** [comment]
added #566

**Comment by leastprivilege** [comment]
My point is - none of these providers really use OAuth for login, because OAuth does not have that feature. Some use openid connect, some proprietary. Just use the term "external authentication providers".

**Comment by Rick-Anderson** [comment]
@leastprivilege Thanks.

**Pull request closed without merging**
