### PR TITLE
WIP: updated nanoserver download

### PR DESCRIPTION
**Pull request by rs38**
since RTM version nano server powershell 5.1 should behave like all other Windows Versions in terms of download and extraction.

### CODE REVIEW

**Comment by rs38** [comment]
DNFBOT, you're welcome!
 :)

**Comment by danroth27** [comment]
@HaoK @blowdart Can you guys take a look?

**Comment by Rick-Anderson** [comment]
@shirhatti  please rev iew

**Comment by shirhatti** [comment]
Given that the [dotnet-install.ps1](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.ps1) script in the CLI repo now works on Nano (thanks to them adding back `Invoke-WebRequest` 😄), I'd prefer using that script with the right parameters as opposed our own franken script which we have to keep up-to-date.

Also, given the rest of the article still talks about TP5, taking this change would leave the article in an inconsistent state. I'd hold back on merging till we've updated the entire article.
If @rs38 wants to give it a crack, I'd be super stoked. If not, I'm still happy letting this PR sit around if someone wants to continue working off of this as a starting point.

**Comment by rs38** [comment]
"franken script"  😄
I'll give it a try to update the whole article, if lending some snippets from the Microsoft/Virtualization-Documentation repo is allowed.

**Comment by Rick-Anderson** [comment]
> if lending some snippets from the Microsoft/Virtualization-Documentation repo is allowed.
That's fine

**Comment by rs38** [comment]
is there a certain trick to get the markdown docs in Visual Studio 2015 for editing, versioning and previewing?
I already created a custom docFx solution (empty asp.net plus docFX Nuget) but that looked not like expected.

**Comment by Rick-Anderson** [comment]
DocFX is broken, we hope to have it fixed soon.

**Comment by rs38** [comment]
this PR can be closed now

**Pull request closed without merging**
