### PR TITLE
EF MVC tutorial series

### PR DESCRIPTION
**Pull request by tdykstra**
@divega @rowanmiller can one of you approve this?

cc @Rick-Anderson

### CODE REVIEW

**Comment by tdykstra** [comment]
@danroth27 -- I put code and images in separate PRs and merged them, so this is now 12 .rst files.  Still big but seems to work in browser for review. If I break it down more it won't build because all tutorials reference the same project for snippets and all are linked in the same toc file.
cc @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@danroth27  review works great on this one.

**Comment by rowanmiller** [comment]
@tdykstra is this the same content that we reviewed yesterday? If so, then I'm happy to sign off based on yesterday's review.

**Comment by tdykstra** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Pull request merged**
