### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by pakrym**
This should do it for https://github.com/aspnet/Docs/issues/9774

`CreateDefaultWebHostBuilder` will call `UseContentRoot(Directory.GetCurrentDirectory())` and pick up the change.

### CODE REVIEW

**Comment by guardrex** [comment]
We can't only make changes to the sample ... the topic explains how these bits work, so there are textual changes needed, too.

**Comment by guardrex** [comment]
If you want, we can merge this with my performing a quick patch for the topic to immediately follow. Sound good?

**Comment by pakrym** [comment]
Sounds good.

**Comment by sertunc** [comment]
Hello; when i change logic like that. service broken ? can you help me ?

if (isService)
            {
                var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
                var pathToContentRoot = Path.GetDirectoryName(pathToExe);
                Directory.SetCurrentDirectory(pathToContentRoot);

                host.RunAsService();
            }
            else
            {
                host.Run();
            }

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

@sertunc Calling SetCurrentDirectory after CreateWebHostBuilder is too late, the application has already read the current directory.

**Pull request merged**
