### PR TITLE
Use EF Core consistently

### PR DESCRIPTION
**Pull request by danroth27**
@Rick-Anderson @rachelappel @ardalis Please review

### CODE REVIEW

**Comment by ardalis** [comment]
Understood. I shortened it in a recent article using "Entity Framework Core (EF)" and then later "EF". Are we good with that?

**Comment by danroth27** [comment]
We chatted with @rowanmiller about that and his guidance was to use "Entity Framework Core" and shorten to "EF Core".

**Comment by Rick-Anderson** [comment]
> "Entity Framework Core" and shorten to "EF Core".
and in many cases shorten to EF. We don't need EF Core throughout the doc. We don't always use ASP.NET Core

**Comment by danroth27** [comment]
> We don't always use ASP.NET Core

@rowanmiller We probably should use ASP.NET Core consistently. I don't want folks getting confused about whether content is for ASP.NET or ASP.NET Core. Your call on EF vs EF Core.

**Comment by Rick-Anderson** [comment]
>I don't want folks getting confused about whether content is for ASP.NET or ASP.NET Core. 

Use EF Core on 2nd occurrence but for the 3rd - 99th on the same article I think we can drop Core. It's probably fine to use Core on the first few, but at some point it gets tedious and is doing nothing to disambiguate versions.

Longer articles that refer to ASP.NET or EF really don't need every occurrence to have Core.

**Comment by Rick-Anderson** [comment]
:shipit:

**Comment by rowanmiller** [comment]
I think it's a bit of a judgement call. My general approach has been to use EF Core consistently in the overview/intro articles to drive home the distinction to EF6.x (though I have definitely not been consistent with that). But once you get beyond that I do tend to just use EF. I don't think we need to be too legalistic about it. We have a site-wide header on the EF docs that points folks to the EF6.x docs.

**Pull request merged**
