### PR TITLE
Create fundamentals overview

### LINKED ISSUE #2343: New Fundamentals Overview topic
One thing we don’t have for Fundamentals is an overview topic.  We do have the overview content, but it’s in the Introduction where it’s more detail than is needed for an Intro.  We could reorganize this content by taking sections like “Application Anatomy” out of Introduction and creating a Fundamentals overview article out of them. 

Fundamentals overview would have:
* Application anatomy
* Startup
* Services
* Middleware
* Servers
* Content root
* Web root
* Configuration
* Environments
* Next steps

Introduction would have:
* What is ASP.NET Core?
* Why build ASP.NET Core?
* Build web UI and web APIs using ASP.NET Core MVC
* Client-side development
* Next steps

At the same time we could implement the .NET Core TOC pattern for Fundamentals where the group node goes to index.md rather than just opening and closing the group.

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #2343 

This also fixes the Fundamentals/Servers submenu so it follows the .NET Core TOC pattern.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/overview.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/overview.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |
[aspnetcore/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/toc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612092354373950-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/overview.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/overview.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |
[aspnetcore/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/toc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100004040428-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/overview.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/overview.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |
[aspnetcore/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/toc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100037126991-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100113539204-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100127233844-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100127340134-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |
[aspnetcore/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/toc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100137173224-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/overview.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/overview.md) | :white_check_mark:Succeeded | |
[aspnetcore/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |
[aspnetcore/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/toc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100147232412-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/yeoman.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/client-side/yeoman.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/environments.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/error-handling.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/hosting.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/hosting.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/owin.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/owin.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/request-features.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/request-features.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/overview.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/overview.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/servers/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/servers/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/fundamentals/toc.md) | :white_check_mark:Succeeded | |
[aspnetcore/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/intro/index.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/intro/index.md) | :white_check_mark:Succeeded | |
[aspnetcore/migration/rc1-to-rtm.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/migration/rc1-to-rtm.md) | :white_check_mark:Succeeded | |
[aspnetcore/toc.md](https://github.com/aspnet/Docs/blob/fundamentals/aspnetcore/toc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612100156248210-2364%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tdykstra** [comment]
@Rick-Anderson Please review - when testing note that TOC changes are sometimes not rendered due to caching, you may have to hard refresh several times.

**Pull request merged**
