### PR TITLE
AuthorizationHandler<T>.Handle -> HandleRequirementAsync

### PR DESCRIPTION
**Pull request by antonGritsenko**
Change from `AuthorizationHandler<T>.Handle` to `HandleRequirementAsync`
https://github.com/aspnet/Security/blob/34ee0212d0c6de76a40609b70df77545dbdde3bf/src/Microsoft.AspNetCore.Authorization/AuthorizationHandler.cs

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@blowdart  approve, deny or comment.

**Comment by Rick-Anderson** [comment]
@HaoK  please review

**Comment by HaoK** [comment]
:shipit:

**Comment by Rick-Anderson** [comment]
@antonGritsenko  Thanks!

**Pull request merged**
