### PR TITLE
AuthorizationContext => AuthorizationHandlerContext

### PR DESCRIPTION
**Pull request by jerriep**
`AuthorizationContext` in the code sample should be `AuthorizationHandlerContext`

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@blowdart  please review.

**Comment by blowdart** [comment]
Oops, I missed one? Sorry. LGTM

**Comment by Rick-Anderson** [comment]
@jerriep  Thanks!

**Comment by jerriep** [comment]
@RickAndMSFT and @blowdart You may just want to review the "Accessing MVC Request Context In Handlers" section at the bottom of the document. 

There is also a mix of `AuthorizationFilterContext` and `AuthorizationContext` being used in that section. I did not bother to figure out what the correct usage should be in that case.

**Pull request merged**
