### PR TITLE
Add missing `-t` in command for creating a new web project

### PR DESCRIPTION
**Pull request by hanstdam**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Invalid input switch:
  -t

**Comment by hanstdam** [comment]
Hi @Rick-Anderson, you are correct - on windows. I just tested it myself on both windows and ubuntu 16.04 LTE. Ubuntu requires the `-t` argument, whereas windows don't understand it.
I agree do not add this as default, as my initial proposal had, but would you be okay with adding a kind of "note" saying something like "if you are on linux, the command is..."?
I'll run some tests on various versions of linux before updating this PR.

**Comment by Rick-Anderson** [comment]
@hanstdam  thanks for reporting this and getting to the bottom. @danroth27 @tdykstra @spboyer  looks like a note is the best option. Why isn't this consistent?

**Comment by spboyer** [comment]
This depends on the version of the dotnet CLI SDK you are running.  

If you are running `.NET Core 1.0.0 SDK – Preview 2-003156` or earlier then the `-t` option is needed in order to define the template.

i.e : `dotnet new -t web`, `dotnet new -t console` or `dotnet new` (creates console app)

However for `.NET Core SDK 1.0.0 - RC4 (build 004771)` or later the new template system is introduced where the `-t` option is not needed and `dotnet new [templatename]` is the syntax.

i.e.: `dotnet new web`, `dotnet new mvc`, `dotnet new classlib` or a more complex option:

```
dotnet new mvc -au none -o myapp -n webapp 
```

**Comment by Rick-Anderson** [comment]
We should add:

Note: This command requires `.NET Core SDK 1.0.0 - RC4` or higher.

**Comment by tdykstra** [comment]
~~or higher~~ or later

**Comment by hanstdam** [comment]
Thanks for all your suggestions and comments. I've updated the change to be a note as suggested by @Rick-Anderson and @tdykstra.

The reason for my confusion was originally that the guide to install .Net Core on Ubuntu suggests `sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177` which requires the `-t` argument.

**Comment by Rick-Anderson** [comment]
>The reason for my confusion was originally that the guide to install .Net Core on Ubuntu suggests {edit} and old version

@tdykstra  @spboyer  we need to minimize the version problem.

**Comment by Rick-Anderson** [comment]
@hanstdam  thanks again. And double thanks for explaining how you hit this problem.

**Pull request merged**
