### PR TITLE
remove UseRuntimeInfoPage from fundamentals/diagnostics

### PR DESCRIPTION
**Pull request by Rick-Anderson**
It no longer provides any useful information.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@ardalis @danroth27  please review

**Comment by danroth27** [comment]
:shipit:

**Comment by ardalis** [comment]
:shipit:

**Comment by rachelappel** [comment]
Merged 23e3f2200bef5ef2eb60665b8109903e71e5a620

**Pull request closed without merging**
