### PR TITLE
Razor Pages initial draft

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/razor-pages/?branch=pr-en-us-3335)

Review questions embedded in the doc:

- ``
- 
``

For the examples on this page, the `DbContext` is initialized in the *Startup.cs** file.

- `<!-- REVIEW What is DSL? -->`
- `<!-- REVIEW What is PRG -->`

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  don't worry about review except for significant problems, I'm going to rewrite this with snippets soon. Can you add the TOC?

@rynowak  [Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/razorpages/intro_to_razor_pages?branch=pr-en-us-3335) and see the REVIEW questions.

**Comment by rynowak** [comment]
> Review: Can I add: The name *Page* for the folder is arbitray but used by convention.

Incorrect in this case, we look in the `Pages` folder for pages (by default).

> REVIEW Original: For these examples the model class, and a database/DbContextis set up. 

Looks fine. 

> 

Post, Redirect, Get https://en.wikipedia.org/wiki/Post/Redirect/Get

> 

Domain specific language. You can probably omit this whole `Our philosophy for Razor Pages` section from the official docs. It made sense in an announcement post, it makes less sense in documentation

Thanks for getting though this in a hurry 👍

**Comment by DamianEdwards** [comment]
Thanks for this @Rick-Anderson. Are we merging this in this morning?

**Comment by Rick-Anderson** [comment]
>Are we merging this in this morning?

@DamianEdwards  Yes. It will go live noon Seattle time.
@tdykstra  do you want to take one quick scan before we merge?

**Comment by tdykstra** [comment]
Will do

**Pull request merged**
