### PR TITLE
B8 common WebApp1 changes

### PR DESCRIPTION
**Pull request by Rick-Anderson**
@danroth27 This is all the Beta8 changes for RST that use common/samples/WebApplication1

### CODE REVIEW

**Comment by danroth27** [comment]
Looks like you added a bunch of stuff under wwwroot/lib that should all be removed.

**Comment by danroth27** [comment]
:watch:

**Comment by Rick-Anderson** [comment]
@danroth27 can you help me get this resolved? With #525  this won't be a manual step going forward (correct)?

**Comment by danroth27** [comment]
:shipit:

**Pull request merged**
