### PR TITLE
Update app-secrets.md

### PR DESCRIPTION
**Pull request by mikelunn**
Sentence was hard to understand. Made it a little more clear and concise.

### CODE REVIEW

**Comment by spboyer** [comment]
@Rick-Anderson to review

**Comment by Rick-Anderson** [comment]
@mikelunn  your rewrite presents it as an alternative approach. I'd like to keep the word "avoid" to let folks know they shouldn't be storing secrets in code/config.

**Comment by mikelunn** [comment]
@Rick-Anderson Just to make sure I understand. The intention of the section "Environment Variables" is to encourage developers to use environment variables instead of code/config. Is that correct. The new Docs are great by the way!

**Comment by Rick-Anderson** [comment]
@mikelunn correct.

**Pull request closed without merging**
