### PR TITLE
Windows Service topic enhancements

### LINKED ISSUE #10836: Windows Service topic enhancements
Thanks @pherbel for remarking on how `sc create` **_does NOT_** set the local security policy for the user to log on as a service. I'll update for that and a few other items here.

* Call out executing `net user` commands from an admin command shell.
* Call out default password expiry of six weeks.
* Possibly call out (or just link) `wmic UserAccount where Name='username' set PasswordExpires=False` to set the password expiry to `never`.
* Use Local Security Policy console to grant the user the `Log on as a service` privilege. Turns out that `sc create` doesn't do it, and I'm not sure how my test account gained the privilege earlier.
* Cross-links:
  * Net user: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/cc771865(v=ws.11)
  * Log on as a service: https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/log-on-as-a-service
  * User Rights Assignment: https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/user-rights-assignment
  * Configure security policy settings: https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #10836

* Call out use of admin command shell when running commands.
* Explicitly grant `Log on as a service` privilege to the user account.
* Call out MSA as an alternative approach with AD. Confirm that I chose a good link for that scenario.
* Call out default password expiry of six weeks.

### CODE REVIEW

**Comment by guardrex** [comment]
> I'd call using an MSA as the recommended way

It never came up before for this topic. If that's what we're going to do, then I'll open a new issue. Since this PR fixes a known 🐞 WRT `Log on as a service`, I recommend we go ahead and get this in now.

Who will make the call on this going with an MSA-based approach?

If we do, my *very brief look* seemed to indicate that Win10 needs some kind of install (MMC bits?) or something ... is that correct? If so, the push-back would be that the topic should maintain its current approach for Win10 and add a whole section for MSA. However if Win10 is good-to-go with MSA OOB, then sure, we could drop the current approach in favor of MSA. Either way tho, engineering should make the call on exactly what to cover ... *not a small green dinosaur*. :smile:

**Comment by shirhatti** [comment]
Agreed. Let's get this in first.

I'm ambivalent on the MSA issue and willing to let that slide as it's not that important.

**Comment by guardrex** [comment]
@blowdart

**Comment by guardrex** [comment]
@blowdart Yes, that was the original ask on https://github.com/aspnet/Docs/issues/10833. I'll re-open that, but I can't do it in the near future. I have 3.0 breath'in down my neck.

### 😨 🔥 🐲

**Comment by guardrex** [comment]
@Rick-Anderson

**Pull request merged**
