### PR TITLE
Change Razor Pages cshtml snippets to devlang cshtml

### PR DESCRIPTION
**Pull request by scottaddie**
Change Razor view code snippets from a dev lang of html to cshtml.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@scottaddie  per http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#code-snippet
<language> can be made up of any number of character and '-'. However, the recommended value should follow Highlight.js language names and aliases.
that doesn't list cshtml

**Comment by Rick-Anderson** [comment]
@tdykstra  don't we use `html` lang for razor files?

**Comment by tdykstra** [comment]
Yes.  I don't see cshtml in the list of supported languages at http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases

**Comment by scottaddie** [comment]
@Rick-Anderson @tdykstra Here's where I found it listed:
https://github.com/dotnet/docfx/releases/tag/v2.19

See item 3 in that release's list. DocFX doesn't complain about it when I use it.

**Comment by tdykstra** [comment]
It works in staging, so the documentation that omits cshtml is out of date.

**Pull request merged**
