### PR TITLE
Adding analytics

### PR DESCRIPTION
**Pull request by danroth27**

### CODE REVIEW

**Comment by danroth27** [comment]
@ericholscher Eric, do you have any concerns with this approach for enabling our analytic scripts and infrastructure?

**Comment by ericholscher** [comment]
Hmm, not sure you even need the prolog part. I believe we'll include it automatically when it's put in with add_javascript. That looks like a solid way to do it though, if you need the custom in the page too.

**Comment by danroth27** [comment]
@ericholscher
> Hmm, not sure you even need the prolog part. I believe we'll include it automatically when it's put in with add_javascript

Not sure what you mean by "include it automatically". As far as I can tell add_javascript adds a script tag at the end of the body with the src set to the included file. The prolog I added is for adding a noscript tag to the HTML body. I don't see how the noscript tag could get included by adding a JavaScript file using add_javascript. Is there some magic here that I am not aware of? On a whim I tried adding the noscript tag to the JavaScript file, but that just results in invalid JavaScript :smile:.

**Comment by ericholscher** [comment]
Ha yea, that was just me being silly. Sorry!

On Wed, May 13, 2015 at 4:42 PM, Daniel Roth <notifications@github.com>
wrote:

> @ericholscher <https://github.com/ericholscher>
>
> Hmm, not sure you even need the prolog part. I believe we'll include it
> automatically when it's put in with add_javascript
>
> Not sure what you mean by "include it automatically". As far as I can tell
> add_javascript adds a script tag at the end of the body with the src set to
> the included file. The prolog I added is for adding a noscript tag to the
> HTML body. I don't see how the noscript tag could get included by adding a
> JavaScript file using add_javascript. Is there some magic here that I am
> not aware of? On a whim I tried adding the noscript tag to the JavaScript
> file, but that just results in invalid JavaScript [image: :smile:].
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/Docs/pull/220#issuecomment-101850168>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by danroth27** [comment]
da305044a182cc279e4f841f9cd0642a63faf895

**Pull request closed without merging**
