### PR TITLE
Updates binding options to configuration for RC2

### PR DESCRIPTION
**Pull request by tyrrell**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@ardalis please review

**Comment by danroth27** [comment]
@tyrrell Can you clarify what this PR is trying to address? Why does this code need to change?

**Comment by Rick-Anderson** [comment]
@tyrrell can you respond?

**Comment by Rick-Anderson** [comment]
@divega  is this change needed?

**Comment by divega** [comment]
No actually. I don't think we should do it. The two versions of the code should have the same effect but the original code is more terse. I imagine one possible motivation for the change could be that @tyrrell didn't have a dependency on `Microsoft.Extensions.Options.ConfigurationExtensions` originally and hence he wasn't getting the extension method that takes `IConfiguration` but I can see the dependency in https://github.com/tyrrell/Docs/blob/8e8d21b5bc00982cb71d72aea57ab08af6885ebd/aspnet/fundamentals/configuration/sample/src/UsingOptions/project.json#L24

**Pull request closed without merging**
