### PR TITLE
Displaying HTML code for <

### PR DESCRIPTION
**Pull request by JonJam**

### CODE REVIEW

**Comment by GuardRex** [comment]
Since that isn't code, would it be preferable here to use ...
```
&amp;lt;
```

**Comment by JonJam** [comment]
@GuardRex Cool thanks for the feedback. I have just committed that change.

**Comment by GuardRex** [comment]
One other little thingy that I didn't notice on first pass. DocFX seems to prefer angle brackets escaped ...
```
\<
```

**Comment by JonJam** [comment]
@GuardRex Escaped those angular brackets. Where is the DocFX reference? Just so I know for any future changes.

**Comment by GuardRex** [comment]
Some of it is here: http://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html

**Comment by GuardRex** [comment]
Forgive me @JonJam ... I made a mistake there. Use ...
```
&lt;

&gt;
```
... in-text for < and >, and the ...
```
&amp;lt;
```
... looks good. :+1:

I seem to have recalled that there was a case in code where `<` must be escaped, but that's not correct. When in a codeblock (backticks), the `<` is fine, and I see a spot in one of my docs that I need to update to fix. The `<` you have is in-text, so it would be welcome as `&lt;` (as text, no backticks).

RE: The contribution guidelines and DocFX styles, I was thinking that a detailed doc would be great. I was about to volunteer to @tdykstra to work on that, but they may have something else in mind for me to do.

**Comment by JonJam** [comment]
@GuardRex I agree a detailed doc would be good.

**Comment by GuardRex** [comment]
Yeah .... *I do!* :cry: It's easy to forget one of the 50 things I have to keep in mind. Tomorrow, I'll float an issue and list the style guidelines that aren't listed at DocFX. We'll see if they want me to forward them into the contribution doc or not.

**Comment by JonJam** [comment]
@GuardRex Well now its 49 as I will remember this one.

**Comment by spboyer** [comment]
@RickAndMSFT the metadata on this doc is not rendering correctly. Needs repaired, can you address?

**Comment by Rick-Anderson** [comment]
LOL, I was going to say I prefer `<` because it's a distinctive style font that stands out better.  I think either approach is OK. `<` is easier to read in MD format and sands out better in the rendered article. @tdykstra  is better at this sort of opinion - but either is fine by me.

@spboyer  @tdykstra  that funny character was the first char in the article. I think it happens anytime someone does a browser edit. I removed it and looks like the meta-data is rendering correctly now.

**Comment by tdykstra** [comment]
I also prefer `<`  for the same reason and agree that either way is fine.

**Comment by GuardRex** [comment]
> either way is fine

... but isn't it rendered as `<` (3C) when it appears in MD as `<`? I ask because that would be an HTML5 violation not to escape it in markup.

**Pull request merged**
