### PR TITLE
rm bad link

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@GuardRex  fixes bad link, you'll probably want a in page anchor 
@tdykstra  how did this slip past validation?

**Comment by GuardRex** [comment]
Yes, mostly my fault. I didn't actually search for links to the doc outside of where I knew they would exist (index and TOC). My bad.

**Comment by GuardRex** [comment]
@Rick-Anderson I'll add a page anchor. btw-- You're using anchors and not anchoring to headings. Is that correct?
```html
<a name="apppools"></a>
```

**Comment by tdykstra** [comment]
H2 headings are automatically made into anchors and you can link to that or you can put in your own.  The advantage of adding your own is links don't break when heading wording changes.

I haven't tried xref to an anchor, don't know if it works.

**Comment by tdykstra** [comment]
> [@]tdykstra how did this slip past validation?
It didn't -- the build reported a warning for it in #2556

**Comment by GuardRex** [comment]
> The advantage of adding your own is links don't break when heading wording changes

:heart: it. Side Note: It would be cool if one day the contrib guidelines could contain all of the preferred 'how to' and 'we want' instructions.

I'll do a test on the `xref` anchor concept with DocFX local and see how it behaves.

RE: The link. I didn't know I could look at the build report by clicking on the checkmark. I'm not sure why GH thinks that a green checkmark should be obviously clickable. Anywho ... now I know. I'll check those every time now.

capture

**Comment by GuardRex** [comment]
:tada: :balloon: **Success!** :balloon: :tada: I put an anchor in Publishing to IIS:
```html
<a name="troubleshooting"></a>
```
... and I put a link in the Directory Structure doc to get there:
```html
[IIS Troubleshooting](xref:publishing/iis#troubleshooting)
```
... and it worked just fine. It rendered as ...
```html
<a class="xref" href="../publishing/iis.html#troubleshooting">IIS Troubleshooting</a>
```
... and took me right there on a click. :+1:

**Comment by Rick-Anderson** [comment]
@GuardRex  you don't need to search for links, DocFX local build will report bad links and when you check in you'll also get  a report.

>I'll add a page anchor. btw-- You're using anchors and not anchoring to headings. Is that correct?
`<a name="apppools"></a>`

No, using anchor-headings-is-better

**Pull request merged**
