### PR TITLE
Update dependency-injection.md

### PR DESCRIPTION
**Pull request by harmoniemand**
dependency injection documentation updated with a small warning on scoped dependencies

### CODE REVIEW

**Comment by guardrex** [comment]
Quick grammatical observation ...

> it forces the service to behave like a singleton

It's importance implies that it's an essential clause. I recommend promoting it in the sentence. Just a suggestion ...

> Don't inject via constructor injection because it forces the service to behave like a singleton.

Also tiny nit ... it's missing a space after the angle bracket:

```
> [!WARNING]
```

**Comment by pranavkm** [comment]
@pakrym could you have a look?

**Comment by pakrym** [comment]
LGTM

**Comment by scottaddie** [comment]
@harmoniemand Thank you very much for adding this warning!

**Pull request merged**
