### PR TITLE
social logins to RC2

### PR DESCRIPTION
**Pull request by Rick-Anderson**
@rustd please review

### CODE REVIEW

**Comment by rustd** [comment]
@blowdart should review this.

**Comment by Rick-Anderson** [comment]
@rustd  @blowdart  reviewed the original I wrote for legacy ASP.NET 5. You took that version and made this ASP.NET 5 version. This PR is just the delta's from ASP.NET 5 RC 1 to ASP.NET Core RC2.

**Comment by blowdart** [comment]
Fine by me

**Comment by Rick-Anderson** [comment]
@blowdart  said "Fine by me"  - can you give me a squirrel?

**Comment by blowdart** [comment]
:shipit: 

I hate this squirrel.

**Pull request merged**
