### PR TITLE
include component and component router in Angular 1.5

### PR DESCRIPTION
**Pull request by aftab10662**
Angular 1 team has introduced 2 new family members one is Component and another is Component Router.
Both are very powerful and vital and moving forward in ng1 both are highly recommended.

We should have a small and brief description of "Component" with small bit of code snippet, similar to controller, template and directive.
In couple of days i am planning to submit on PR for that.
You input please!

### CODE REVIEW

**Comment by danroth27** [comment]
Could you please add the content to this PR so that we can review it all together?

**Comment by aftab10662** [comment]
@danroth27 Sure, i will add content and submit PR.

**Comment by Rick-Anderson** [comment]
@aftab10662 is this a dup of #1694

**Comment by aftab10662** [comment]
@Rick-Anderson  yes, it is dup.
this PR can be closed.

**Pull request closed without merging**
