### PR TITLE
Dev2/key management.md

### PR DESCRIPTION
**Pull request by spottedmahn**
Fixes 1 issue in #4651 

>aspnetcore/security/data-protection/extensibility/core-crypto.md	Illegal link: [automatic key rolling](../implementation/key-management.md#data-protection-implementation-key-management) -- missing bookmark. The file security/data-protection/implementation/key-management.md doesn't contain a bookmark named data-protection-implementation-key-management. Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark	160	10/13/2017 12:54:43

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@spottedmahn  can you complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

**Comment by spottedmahn** [comment]
Hi @Rick-Anderson I did 😄 

image

**Comment by dnfgituser** [comment]
Hi, I am closing and re-opening this PR to bump the CLA service. Sorry for the inconvenience!

**Comment by Rick-Anderson** [comment]
@spottedmahn  Nice work. You're all set up now.

**Pull request merged**
