### PR TITLE
Bower article update

### PR DESCRIPTION
**Pull request by scottaddie**
Updated the Bower article to reflect Beta 8 changes.

### CODE REVIEW

**Comment by danroth27** [comment]
@madskristensen Please review

**Comment by danroth27** [comment]
Thank you! e48e260e19800cac5fc22a34bdde43580a6bae0c

**Comment by scottaddie** [comment]
@danroth27 I see some of the text updates are live [here](https://docs.asp.net/en/latest/client-side/bower.html); however, the images are still the old ones. Anything you need me to do, or will those be merged in?

**Comment by danroth27** [comment]
@scottaddie I checked the site and it looks like the new images are there. Are you still seeing the old ones?

**Comment by scottaddie** [comment]
@danroth27 Now I see them there. Must have been a browser cache issue.

**Pull request closed without merging**
