### PR TITLE
Fix a PS command argument

### PR DESCRIPTION
**Pull request by guardrex**
I think it still works on `-PermissionsToKeys` (that's likely what I ran at the time), but I agree with the comment on the topic that it should be `-PermissionsToSecrets`. @anurse Can you review/confirm?

Thanks to @Olav_Tollefsen1 for point this out.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@anurse  quickie review please.

**Comment by guardrex** [comment]
@anurse IIRC it worked as "Keys" and not "Secrets" when we did this topic. AFAICT the commenter is correct ... it should be "Secrets."

@Rick-Anderson I'd feel more comfortable with this if we could get an Azure person who knows Key Vault inside-and-out to TAL. Any chance of that?

**Comment by Rick-Anderson** [comment]
@SyntaxC4 can you recommend someone to review a one line change to Azure key vault?

**Comment by guardrex** [comment]
@anurse Checkout your bullet 4 sub-bullet: https://github.com/aspnet/Docs/issues/1993#issue-184308289

The strange thing is that I when I ran the setup myself I very likely used `-PermissionsToKeys list,get`. I didn't have problems. Whatever I did, it did :sparkles: *Just Work* :sparkles:. However, you put "Secrets" in bold as though you found out that if you don't use `-PermissionsToSecrets` it will :boom:.

@Rick-Anderson @SyntaxC4 I think it's best that I re-run the topic and confirm that it must be "Secrets" there. I'll check it out next week and see what's what and report back. In the meantime, I'll mark this **WIP**.

**Comment by guardrex** [comment]
@Rick-Anderson Sorry for the delay here. I'll take care of this as soon as `IStartupFilter` merges and `IHostingStartup` goes into review. Should be soon.

**Comment by guardrex** [comment]
@Rick-Anderson Tested and confirmed ... `-PermissionsToSecrets` :+1: ... u can merge this.

**Pull request merged**
