### PR TITLE
Fixes #3862 Support SDK 1.0 in 2.0 topics (revert and fix)

### LINKED ISSUE #3862: aspnet/core/security/authentication/social/ for 2.0
@01binary - this from @timheuer

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins 
i'm following this doc and after adding the middleware package, the api AddGoogleAuthentication (and the Microsoft one) are not available
I think it should be app.Use* 

MSA auth would fails
-- end of Tim --

Can we mark off the steps that require ASP.NET Core 2.0? Did we lose the steps for 1.x?

I think Tim has Google working but not MSA. Any trouble shooting tips?

### PR DESCRIPTION
**Pull request by 01binary**
Changes based on @scottaddie review of #3870 pull request.

**Do not merge**

Before merging, we need to address an issue with ASP.NET Core 2.x snippets. I tested with the following on `Visual Studio 2017 preview, .NET Core 2.0 preview 2` and it works:

```csharp
services.AddFacebookAuthentication(facebookOptions =>
{
    facebookOptions.AppId = Configuration["Authentication:Facebook:AppId"];
    facebookOptions.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
});
```

@scottaddie suggests changing to:

```csharp
services.AddAuthentication().AddFacebook(o => {
    o.AppId = Configuration["Authentication:Facebook:AppId"];
    o.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
});
```
Is this the difference between SDK 2.0 and SDK 2.0 preview 2? When my Surface is charged I will double-check to make sure that's actually what I used.

### CODE REVIEW

**Comment by scottaddie** [comment]
@01binary Going from Preview 2 to RTM bits, there's a breaking change. You'll need to invoke `services.AddAuthentication().AddFacebook` with the RTM bits. In fact, all of the authentication scheme methods now hang off of `AddAuthentication`. See the *identity-2x.md* file in PR https://github.com/aspnet/Docs/pull/3768 for examples of this.

**Comment by 01binary** [comment]
I asked @RickAndMSFT if he wanted me to use **Preview 2** to update the social provider documentation and I think he used thumbs-up emoji so I went with Preview 2.

Your official statement regarding documentation is that you want everyone writing docs now to use **ASP.NET Core 2.0 RTM**, is that correct? Did I miss this context because it was on a front page somewhere but I want to edit social topics directly?

**Comment by scottaddie** [comment]
@01binary I've confirmed with Rick that we should document RTM bits instead of Preview 2. This evening is fine.

Thank you again for all of your hard work on this one. It's appreciated both by us and the community.

**Comment by Rick-Anderson** [comment]
@01binary  Install latest .NET Core 2.0 SDK from https://github.com/dotnet/cli/tree/release/2.0.0

**Comment by 01binary** [comment]
I verified Facebook and Microsoft Account auth on 2.0 RTM (thanks for the install link), going to assume the rest work given very similar API changes. If you go to verify yourself with a new project, don't forget to update redirect URIs for respective providers, that's the primary cause of cryptic errors.

@scottaddie ready for QA pass.

**Comment by scottaddie** [comment]
@01binary Great work on the changes! They will go live in the next day or so.

**Pull request merged**
