### PR TITLE
Update Publish to IIS doc

### PR DESCRIPTION
**Pull request by GuardRex**
Addresses https://github.com/aspnet/Docs/issues/1359

- [x] Short description of the `web.config` file but that primarily relies upon a link to [ASP.NET Core Module Configuration Reference](https://docs.asp.net/en/latest/hosting/aspnet-core-module.html) to explain the details of configuration.
- [X] Short description of the `publish-iis` tool and `project.json` setup for it.
- [X] Brief description of how to use `app_offline.htm`.
- [ ] Remark that Azure Apps have their own doc and link to it early in this doc.
- [X] Add IIS options settings and what they do: `services.Configure<IISOptions>(options => { ... });`
- Additional troubleshooting tips at the top of the Common errors section:
  - [X] Running the app directly to narrow down IIS-module problem versus app problem.
- Additional Common errors to test and list along with the rest
  - [X] dotnet.exe is not on the PATH
  - [X] Confirm that having %LAUNCHER_PATH%/%LAUNCHER_ARGS% placeholders match the currently listed behaviors for bad processPath/arguments, respectfully.
  - [X] [MIA .NET Framework on the server (Docs/#1354)](https://github.com/aspnet/Docs/issues/1354)
- [x] Swap image showing how to reach Basic Settings of the AppPool

I skipped "Remark that Azure Apps have their own doc and link to it early in this doc." It's plainly evident that this doc exists in the `Publishing and Deployment` section, so I don't think it bears mentioning.

### CODE REVIEW

**Comment by GuardRex** [comment]
@Rick-Anderson Ok, I think we have ourselves a draft here.

**Comment by PureKrome** [comment]
Squish commits, @GuardRex :sunglasses:

**Comment by GuardRex** [comment]
@PureKrome I wait until after we go through drafts and I get a little squirrel.

**Comment by PinpointTownes** [comment]
> Squish commits, @GuardRex :sunglasses:

You probably mean "squash"? :trollface:

**Comment by Rick-Anderson** [comment]
:shipit:

**Comment by GuardRex** [comment]
@Rick-Anderson I can rebase if you like. No worries either way. :smile:

**Comment by Rick-Anderson** [comment]
I used the magic green button with "Squash and merge" that seems to have worked. Thanks for the update.

**Comment by GuardRex** [comment]
@Rick-Anderson Oh, ok, cool. I like :sparkles: magical buttons :sparkles:.

**Pull request merged**
