### PR TITLE
Resource-based authorization: code formatting

### PR DESCRIPTION
**Pull request by AlphaGit**
Performed some format cleaning on the code samples for the resource-based authorization documentation. No code or text changes done.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  @scottaddie  this looks like an improvement and I don't see any changes other than white space - recommend we merge it.

**Comment by scottaddie** [comment]
@Rick-Anderson Looks good to me. :shipit:

**Comment by tdykstra** [comment]
Looks OK to me, aside from the fact that it's all inline code which we would ideally eliminate in favor of snippets.

**Comment by AlphaGit** [comment]
Thanks a lot! @Rick-Anderson @scottaddie @tdykstra

**Pull request merged**
