### PR TITLE
Change folder and description of the anchor.

### PR DESCRIPTION
**Pull request by fesnarriaga**
I am proposing this change because the document below references this document.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page
If another tutorial makes an Schedule Page and points to this page, please do not approve this change.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@guardrex  we shouldn't mix up schedules in the main RP code - should we? Will this break your add on tutorial?

Upload files should be a standalone tutorial. It's OK that it builds on the Movies tutorial. This is a long term fix, not to worry about now.

**Comment by guardrex** [comment]
The downloadable sample is the *completely functioning* sample that has all of the steps in the tutorial applied; it's the final finished app. Therefore, I thought the internal links link everywhere they would link in the final app. It's true that we don't instruct in the File Uploads step to add this link (perhaps we should), but it makes it convenient to reach the page when the sample is downloaded.

As for this specific change, I'd need to take a closer look. I can look in 20 minutes ... I'm knee-deep in another thing at the moment. 😅

**Comment by guardrex** [comment]
Ok ... I had a peek. I think the fix is to add this link in the steps of the File Uploads tutorial step and leave the link as it is in this layout page (given that this sample is the final, built sample app).

Perhaps, the Movie page step should also have an instruction to tell the reader to add a link to Movies (if it doesn't do so already). IIRC, the **RpMovie** links to the Movie page, so it might not be necessary. It might be necessary tho to tell the reader to put the **RpMovie** link into the app as they're building it.

I opened #5931 to address this.

Thanks @fesnarriaga for pointing this out. I recommend closing here, and I'll fix it on #5931.

**Comment by fesnarriaga** [comment]
@guardrex, glad I could help.

**Pull request closed without merging**
