### PR TITLE
add theme change how-to

### PR DESCRIPTION
**Pull request by tdykstra**
cc @spboyer

### CODE REVIEW

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/bootstrap.md](https://github.com/aspnet/Docs/blob/tdykstra-patch-2-1/aspnetcore/client-side/bootstrap.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/bootstrap.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C10%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611101659232759-2141%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
Leave a comment

**Comment by bradygaster** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/client-side/bootstrap.md](https://github.com/aspnet/Docs/blob/tdykstra-patch-2-1/aspnetcore/client-side/bootstrap.md) | :white_check_mark:Succeeded | | [Details](#user-content-aspnetcore/client-side/bootstrap.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C11%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201611111821056360-2141%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@spboyer  please review

**Pull request merged**
