### PR TITLE
azure and redis key providers

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@pakrym @pranavkm  need better comments on 
```
 // Connect
    var redis = ConnectionMultiplexer.Connect("<URI to ??>");
```

**Comment by Rick-Anderson** [comment]
Fixes #2309

**Comment by Rick-Anderson** [comment]
Use [this branch ](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?branch=ra%2FPerstKeysToAzureBlobStor)to review built doc.

**Comment by pakrym** [comment]
@Rick-Anderson 
```
// Connect to Redis database
var redis = ConnectionMultiplexer.Connect("<configuration string>");
```
[Redis doc](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Basics.md) that talks about using `ConnectionMultiplexer.Connect`

[Azure doc](https://docs.microsoft.com/en-us/azure/redis-cache/cache-dotnet-how-to-use-azure-redis-cache#connect-to-the-cache) is a doc that talks about connecting to Redis, only difference is that ours should not be Azure specific. 

We might want to add a link to that page as it has Azure Redis setup instructions which might be useful.

**Comment by Rick-Anderson** [comment]
@pakrym made requested changes. Ready to merge?

**Comment by pakrym** [comment]
:shipit:

**Pull request merged**
