### PR TITLE
Fixes #3753 update aspnet/core/security/authentication/social/ for 2.0

### LINKED ISSUE #3753: 2.0 update aspnet/core/security/authentication/social/ for 2.0
15:55 into 7-17 recording.

- [ ] [Enabling authentication using Facebook, Google and other external providers]( https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/)
- [ ] [Google ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins) Do the next quick update after this.
- [ ] [Combine social and local login accounts](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm#combine-social-and-local-login-accounts) (only the last section) 
- [ ] [Facebook ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins)
- [ ] [Twitter ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins)
- [ ] [Microsoft ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins) 
- [ ] #3796

### PR DESCRIPTION
**Pull request by 01binary**
Fixes #3753 update aspnet/core/security/authentication/social/ for 2.0.

- Update provider steps
- Update ASP.NET Core code snippets
- Replace complex inline sections with references to separately maintained topics that would do a better job
- Update screenshots (shadows replaced with borders to handle light/dark theme switch)
- Expect QA/wording/markdown pass from @RickAndMSFT
- All steps verified as actually working but could use a light QA pass from someone intimately familiar with social provider configuration in places where technical details are described

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@01binary  looks fantastic. Can you take a quick look at my commits to make sure I didn't break anything?

**Comment by 01binary** [comment]
I think I missed something in the markdown:

> html.ValidateBookmark](security/authentication/social/google-logins.md#L125)Illegal link: `[earlier on this page](#enable-googleplus)` -- missing bookmark. The file security/authentication/social/google-logins.md doesn't contain a bookmark named enable-googleplus.

Looks good other than that.

**Comment by 01binary** [comment]
Oops, on the Google provider page, all the Notes are broken. All other pages seem to have them working

**Comment by Rick-Anderson** [comment]
@01binary  The internal build looks great. I removed a bunch of the obtrusive [!NOTE] > markup and replaced it by regular text.

**Pull request merged**
