### PR TITLE
Update nano-server.rst

### PR DESCRIPTION
**Pull request by alexandair**
Minor typos fixed.

### CODE REVIEW

**Comment by shirhatti** [comment]
:shipit:

**Comment by danroth27** [comment]
:shipit:

**Comment by alexandair** [comment]
What does that comment mean?

**Comment by shirhatti** [comment]
:shipit: === "Ship it". That means we have accepted the changes and someone with push access will merge it.

**Comment by alexandair** [comment]
Thanks.

**Comment by shirhatti** [comment]
Thanks for the PR! Merged in 0c3d55a0753f0c30e91ac698b4c52154bd39764b

**Pull request closed without merging**
