### PR TITLE
Update 20_21.md

### LINKED ISSUE #6853: Default Transport is now based on managed Sockets
In the Transport documentation for the ASP.NET Core 2.1 Transport configuration it says that this change to managed sockets is a breaking change. The migration solution is also listed right there : https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x#transport-configuration

This change broke our existing code for added Trusted Proxies which were added in IPv4 Format and after the upgrade did not match the now "incoming" IPv6 Adresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #6853

### CODE REVIEW

**Comment by guardrex** [comment]
Note there are some un-escaped, un-fenced, underscores in the topic.

**Comment by Rick-Anderson** [comment]
@guardrex 
>Note there are some un-escaped, un-fenced, underscores in the topic.

Can you fix them or point them out?

**Comment by guardrex** [comment]
Yeah ... I'll drop thru and escape them.

**Comment by Rick-Anderson** [comment]
@guardrex  what's the problem with `_`?

**Comment by guardrex** [comment]
In normal markdown syntax, the parser thinks it should start to italicize the text (same as \*). However, their docs are incomplete or I can't find the guidance, so I can't verify how they're handling it. I opened an issue with them to ask. I'll report back their response.

**Comment by Rick-Anderson** [comment]
If it only impacts when rendered in the GitHub editor, I think we should back out of that change. It makes the markup hard to read.

**Comment by guardrex** [comment]
It looks like it's in their expressions tho ...

```
^_((?:__|[\s\S])+?)_\b|^\*((?:\*{2,}|[^\\*]|\\[\s\S])+?)\*(?!\*)
^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)
^_((?:_|(?>[^_]+))+?)_\b|^\*(\**(?!\s)(?:[^\\*]|\\[\s\S]|(?<=\s)\*+)+(?<!\s|\*))\*
```

Also note that their escape pattern has an underscore ...

```
Regex Escape = new Regex(@"^\\([\\`*{}\[\]()#+\-.!_>])", RegexOptionCompiled, RegexTimeOut);
```

https://github.com/dotnet/docfx/blob/dev/src/Microsoft.DocAsCode.MarkdownLite/Regexes.cs

**Comment by guardrex** [comment]
You looked at the built topic and it was ok?

**Comment by guardrex** [comment]
I heard back from the DocFX cats. They said they follow [CommonMark for emphasis](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis).

It's fine for headings ...

> \# \_Heading with leading underscore

We're fine for intraword underscores, even if they start with an underscore ...

> some_thing (ignored)
> _some_thing (ignored)
> \_some_thing\_ (this one will get emphasis: _some_thing_)

It should only be an issue if the underscore is a "left-flanking" naked underscore out in an open paragraph...

> _something

... that would need an escape ...

> \\\_something

**Pull request merged**
