### PR TITLE
Add RouteTokenTransformerConvention documentation

### PR DESCRIPTION
**Pull request by JamesNK**

### CODE REVIEW

**Comment by guardrex** [comment]
@JameNK ... If you don't mind, it's faster if I make a quick grammar pass on this with a direct edit over typing nit comments. Cool with you?

**Comment by JamesNK** [comment]
all good in the hood

**Comment by guardrex** [comment]
Thanks ... nits only. Check tho to make sure you agree with the changes.

**Comment by Rick-Anderson** [comment]
@JamesNK 	 can you add the code for `SlugifyParameterTransformer` and please check my edits.

**Comment by JamesNK** [comment]
Looks good. Ship it

**Comment by guardrex** [comment]
There's an 85 char limit on code lines, so you should break the long one on the last commit.

**Comment by JamesNK** [comment]
G2G. I'll let you guys merge it in case there is any docs ceremony I don't know about 😬 (some sort of pagan sacrifice I assume)

**Comment by guardrex** [comment]
Sometimes, we sacrifice a mouse from a certain well-branded manufacturer to the :pray: server gods :pray:, but this isn't one of those scenarios. :smile:

**Pull request merged**
