### PR TITLE
Updating index page to use correct terminology consistently

### PR DESCRIPTION
**Pull request by timheuer**
Quickstart links refer to ASP.NET Core and .NET Core...we should be consistent to what it is (ASP.NET Core)

### CODE REVIEW

**Comment by timheuer** [comment]
@guardrex But this didn't take my suggestion?  The Linux one still has just ".NET Core" isntead of "ASP.NET Core"?

**Comment by guardrex** [comment]
That's the title of the topic. Open an issue at the bottom of that topic with their **Content feedback** button and see if they'll change it, then we can change it over here.

https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-dotnetcore

**Comment by guardrex** [comment]
I've marked this PR here, so I won't lose this. I'll keep an :eye: on it. If you want me to open that issue with them, let me know.

**Comment by timheuer** [comment]
Related: https://github.com/MicrosoftDocs/azure-docs/issues/25709

**Pull request merged**
