### PR TITLE
How to trust ASP.NET Core dev cert on Win/MacOS

### LINKED ISSUE #6383: Doc section: CLI how to trust a cert
Need H2 for fwlink for CLI team. Send the link to `@danroth27`

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&branch=pr-en-us-6385&tabs=visual-studio#install-and-trust-the-aspnet-core-https-development-certificate)

Fixes #6383 and #5393
Here's the output after installing the SDK and creating an ASP.NET Core app:

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms please refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
Getting ready...
The template "ASP.NET Core Web App" was created successfully.

The fwlink 848054 points to this page. If you want a fwlink to the cert install/trust instructions, it's the same URL with `#cert`

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@livarcocc  @danroth27  do you know who on the CLI team wanted a fwlink to these instructions?

**Comment by danroth27** [comment]
@javiercn and I are the right reviewers for this.

**Comment by Rick-Anderson** [comment]
@danroth27  @javiercn  45 second review please.

**Comment by javiercn** [comment]
I think the point of this topic is to show how to trust the certificate manually (without the tool) on each platform, so that people can diagnose/troubleshoot it if they have any issue with the tool.

**Comment by Rick-Anderson** [comment]
@javiercn where would I find that information?

**Comment by Rick-Anderson** [comment]
@javiercn this is just the Win/MacOS portion. The other xplat will be covered in  #3310

**Comment by javiercn** [comment]
@Rick-Anderson Ok, I'm a bit confused now. We need to have a doc on how to do it with the tool and also how to do it manually in a platform idiomatic way on each platform. 
* powershell/trust cert store in windows
* openssl/keychain on OSX
* openssl/<<something>> on Linux (At least Ubuntu, RedHat if possible)

Does that help clarify things?

**Comment by Rick-Anderson** [comment]
@javiercn  got it. I thought we wanted a section for dotnet command line for folks that don't read the message on how to trust the cert. Suppose they `dotnet new Razor` then  `cls` the `dotnet run`. They'll have a cert problem.

So I'll close this PR and maybe include the information in this PR into  #3310 (which will cover everything you mentioned).

**Pull request closed without merging**
