### PR TITLE
add version # to VS install include

### PR DESCRIPTION
**Pull request by Rick-Anderson**
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Or should it be Update 3? Change the file if you like upade 3 better.

**Comment by scottaddie** [comment]
@Rick-Anderson @tdykstra I propose "Visual Studio 2017 version 15.3".

**Comment by Rick-Anderson** [comment]
@scottaddie  that's what I have. Approve and I'll merge.

**Comment by scottaddie** [comment]
@Rick-Anderson Looks like "2017" is still missing.

**Comment by Rick-Anderson** [comment]
arg. fixed

**Comment by scottaddie** [comment]
:shipit:

**Pull request merged**
