### PR TITLE
Add missing `<tr>` to snippet

### PR DESCRIPTION
**Pull request by badersur**

### CODE REVIEW

**Comment by badersur** [comment]
The following code was not explained:

```
@{
    foreach (var course in item.CourseAssignments)
    {
       @course.Course.CourseID @:  @course.Course.Title <br />
    }
}
```

and I'm not sure about the purpose of `@:`!

**Comment by Rick-Anderson** [comment]
@badersur  Great question. It's a https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor#explicit-line-transition-with-label - That would be a nice update to the article (adding that link)

**Comment by Rick-Anderson** [comment]
@badersur  thanks for the update.

**Comment by badersur** [comment]
You're welcome :)

**Comment by badersur** [comment]
I was thinking it's enforcing white spaces in razor blocks!

**Comment by badersur** [comment]
Thanks for the link. Now I know where to read more about razor! I don't remember reading about the syntax (or I had forgotten everything about it!)

It seems the block I was mentioning is explained but I didn't notice. I'll add the link soon :)

**Pull request merged**
