### PR TITLE
Update routing.md

### PR DESCRIPTION
**Pull request by davidich**
Routing won't work with an example provided in that doc. Change '/Products/5' to '/en-US/Products/5'

[documentation page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@rynowak  30 second review on your routing doc.

**Comment by Rick-Anderson** [comment]
@rynowak 39 second review on your routing doc.

**Comment by Rick-Anderson** [comment]
@guardrex  FYI

**Comment by scottaddie** [comment]
Ping @rynowak. Please review these changes.

**Comment by Rick-Anderson** [comment]
@davidich  sorry this took so long. You fix is much appreciated. Hope to see your improvements again.

**Pull request merged**
