### PR TITLE
Fixed R in razor to be uppercase.  Fixed CacheTagHelper vary-by-user …

### PR DESCRIPTION
**Pull request by pkellner**
Two small fixes to @Rick-Anderson 's commit on the ra-pKellner-built-in-TH branch

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@pkellner  your branch is too old. You to update your branch to make a PR. There shouldn't be any conflicts.

**Comment by Rick-Anderson** [comment]
@pkellner  when the built-in is live, use the Edit button to make the changes in the browser and submit a PR.

**Comment by Rick-Anderson** [comment]
@pkellner  it's live now.

**Comment by pkellner** [comment]
Awesome!  I'll be home tomorrow and will make some fixes. Meanwhile the show associated links at the bottom of the live pages don't work.  If 
@Rick-Anderson or @Luke could fix this page https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/CacheTagHelper.md#additional-resources I'll fix the other pages.

**Comment by pkellner** [comment]
Adding @guardrex to last comment

**Comment by pkellner** [comment]
Actually, I think all links ok.  I was looking on github and not production.

**Pull request closed without merging**
