### PR TITLE
Update logging-2.0.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging-2.0?branch=pr-en-us-3604)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@pakrym  ready to review. You can leave feedback so I can fix this up, then you can merge into your PR.

**Comment by Rick-Anderson** [comment]
@pakrym  you can:

* use the browser to edit this commit then create a new PR.
*  commit directly to this PR and I can review the hash. 
*  leave conventional feedback and I'll fix it.
* delete this branch.

**Comment by Rick-Anderson** [comment]
@pakrym let me know when you can review this.

**Comment by tdykstra** [comment]
I'll be taking parts of this into new PR to the 2.0 Release Notes doc.

**Pull request closed without merging**
