### PR TITLE
Beta8 version of sample

### PR DESCRIPTION
**Pull request by TomArcher**

### CODE REVIEW

**Comment by TomArcher** [comment]
@Rick-Anderson @danroth27 @Erikre Please review

**Comment by Rick-Anderson** [comment]
looks good :shipit:

**Comment by danroth27** [comment]
You need to also fix up all the literalincludes that reference this sample. Otherwise, when you merge this in you will break the literalincludes.

**Comment by danroth27** [comment]
:watch:

**Comment by danroth27** [comment]
Nevermind, this sample is only referenced from the DNX console app article, which only includes entire files. :shipit:

**Pull request merged**
