### PR TITLE
Oleg lviv patch 1

### PR DESCRIPTION
**Pull request by OlegLviv**
When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

### CODE REVIEW

**Comment by scottaddie** [comment]
@OlegLviv Please sign the CLA using the link above. We cannot review the PR until that's done. Also, please indicate what problem this PR is intended to solve.

**Comment by scottaddie** [comment]
@guardrex I agree. For example, we'd need to replace `Microsoft.AspNetCore.All` with `Microsoft.AspNetCore.App`.

**Comment by Rick-Anderson** [comment]
@OlegLviv Please sign the CLA using the link above ☝️. We cannot review the PR until that's done. Also, please indicate what problem this PR is intended to solve.

**Comment by Rick-Anderson** [comment]
@OlegLviv thanks for the PR. We need a signed CLA to review PR's.

**Pull request closed without merging**
