### PR TITLE
Increase visibility of alternative (none VS) approach

### PR DESCRIPTION
**Pull request by JosephWoodward**
When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

* Suggest reviewers if you know who should review the PR, using the GitHub **Reviewers** UI.

### CODE REVIEW

**Comment by scottaddie** [comment]
@Rick-Anderson I really like this PR's idea of visually separating the two options. Should we introduce tabs instead of H3 headings?

**Comment by Rick-Anderson** [comment]
@scottaddie  Yes, tabs preferred.

**Comment by Rick-Anderson** [comment]
@scottaddie  see my commit and merge when ready. @JosephWoodward  Thanks!

**Comment by Rick-Anderson** [comment]
@scottaddie  changed to .NET Core CLI

**Pull request merged**
