### PR TITLE
Add missing *

### PR DESCRIPTION
**Pull request by badersur**
Strangely, this article doesn't show the date and the contributors!

### CODE REVIEW

**Comment by scottaddie** [comment]
@badersur I'm investigating why that info doesn't display for this article. Thank you for adding the missing asterisk!

**Comment by badersur** [comment]
Good luck with the investigation and you're welcome :)

**Comment by scottaddie** [comment]
@badersur The missing info displays now. There was an anchor tag immediately before the main title in the doc. This was causing the info to not display.

**Comment by badersur** [comment]
Great news. Thanks for letting me know about the fix :)

On 15 Sep 2017 6:56 am, "Scott Addie" <notifications@github.com> wrote:

@badersur <https://github.com/badersur> The missing info displays now.
There was an anchor tag immediately before the main title in the doc. This
was causing the info to not display.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/Docs/pull/4282#issuecomment-329666320>, or mute
the thread

**Pull request merged**
