### PR TITLE
VSTS CI docs article

### LINKED ISSUE #1271: Publish to Azure Web App with VSTS Build CI
An article to outline Continuous Integration using Visual Studio Team Services with Build and/or Release features. I would see the doc outlining steps potentially being:

1. Get and install `dotnet` on build servers with script from https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1
2. `dotnet restore`
3. `dotnet publish -c Release -o $(build.stagingDirectory)/MyProject`
4. Use powershell to zip contents of published folder
4. Azure web app deployment using "Azure Web App Deployment" VSTS task with 'web deploy pacakge' as path of zipped folder from 3.

This doc could also outline an alternative between steps 3 and 4 to use "Publish Artifacts" and then use VSTS Release to do the release step

### PR DESCRIPTION
**Pull request by damienpontifex**
Resolves #1271 with article for buildings ASP.NET Core application with Team Services hosted build servers and publishing to Azure App Service.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@rachelappel  please review

**Comment by damienpontifex** [comment]
Since the RTM release, I am getting the warning as "File name doesn't indicate a full path to a executable file." when using `dotnet` in a build step. 

I have had a reply confirming RTM bits will be on hosted build servers by the end of the week, so will re-evaluate and see if any changes are required for this.

**Comment by rachelappel** [comment]
Merged, thanks 8abb6f5f5859c8e1845dbe203fd5f94c571cb4a1

**Comment by rachelappel** [comment]
Merged, thanks 8abb6f5f5859c8e1845dbe203fd5f94c571cb4a1

**Pull request closed without merging**
