### PR TITLE
Add readme & comment

### PR DESCRIPTION
**Pull request by AmirChabok**
Add comments for understand and better enforcement on:
Startup.cs (Middleware)

Add readme file for understand and better enforcement on:
StaticFiles

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/MiddlewareSample.xproj](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/MiddlewareSample.xproj) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/Startup.cs](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/Startup.cs) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/static-files/sample/ReadMe.html](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/static-files/sample/ReadMe.html) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C3%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612031908550714-2313%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/MiddlewareSample.xproj](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/MiddlewareSample.xproj) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/Startup.cs](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/Startup.cs) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/static-files/sample/ReadMe.html](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/static-files/sample/ReadMe.html) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C3%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612031939340529-2313%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AmirChabok** [comment]
Add readme file in Staticfiles project & 
Add comment for startup class (Middleware)
Best Regards.

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/MiddlewareSample.xproj](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/MiddlewareSample.xproj) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/Startup.cs](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/middleware/sample/src/MiddlewareSample/Startup.cs) | :white_check_mark:Succeeded | |
[aspnetcore/fundamentals/static-files/sample/ReadMe.html](https://github.com/tolooco/Docs/blob/master/aspnetcore/fundamentals/static-files/sample/ReadMe.html) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C3%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612032040392387-2313%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@AmirChabok  I don't understand the comments you want to add.

**Pull request closed without merging**
