### PR TITLE
fix page title

### PR DESCRIPTION
**Pull request by spottedmahn**
No issue to reference.  Just something I noticed.

### CODE REVIEW

**Comment by scottaddie** [comment]
@spottedmahn Believe it or not, the sentence casing is preferred for titles. The period, however, shouldn't be there. Please adjust accordingly, and then I'll merge.

**Comment by spottedmahn** [comment]
Hey @scottaddie - really?  That seems odd.  Is that in the style guide?

And doesn't seem like the convention is followed as most of these have Proper Case:

image

**Comment by spottedmahn** [comment]
@scottaddie done.

**Comment by scottaddie** [comment]
@spottedmahn The style recommendation hasn't been applied everywhere; however, I do see it in our internal style guide.

**Comment by scottaddie** [comment]
@spottedmahn Thank you!

**Pull request merged**
