### PR TITLE
Update model4Win.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by guardrex** [comment]
@Rick-Anderson Do u want me to revert those earlier changes to the plurality of the name so that u don't need to do this? Devs may scratch their heads on why the list is singular (just like I did), but it might be better than having a glaring exception.

**Comment by Rick-Anderson** [comment]
Did you remove the plural name that broke the tutorial? If so yes.

**Comment by guardrex** [comment]
> Did you remove the plural name

Other way around: I added it.

At the time, there was no reason to suspect that scaffolding had a bug-a-boo :beetle:. I ran the migrations, but I didn't run the scaffolding because I was working with the full sample.

I'll revert that naming change, then u can close this. I'll also open a new issue tied to the scaffolding bug you opened. Later, someone can circle back and redo the undone repairs ... if that makes sense. First tho ... real quick ... I want to repro this. It's strange that such an obvious scenario is broken.

**Comment by guardrex** [comment]
@Rick-Anderson I'll open a new tracking issue on that scaffolding issue, unless if you already know that you want to stick with singular collection names even after they solve it.

**Comment by Rick-Anderson** [comment]
at this point, if it ain't broke, don't fix it. Too low a priority and too high a risk

**Pull request closed without merging**
