### PR TITLE
CommandLine config provider overhaul

### LINKED ISSUE #1382: Configuration: Document format supported for command line arguments provider
Originally mentioned in https://github.com/aspnet/Configuration/issues/120:

> ... it is not obvious, without looking at the code, how are they supposed to be used.
> 
> For example, is I have:
> 
> ``` C#
> Configuration config = new Configuration();
> config.AddCommandLine(args);
> ```
> 
> What is the format accepted by the strings in "args" to be valid? There are many possible options: `/key value`, `--key value`, `--key:value`, `key=value`, etc.

For some initial context, by default the command line arguments provider supports converting arguments of the format `key1=value1 key2=value2 key3=value3` Additional syntax with `-key1 value1`, `--key2 value2` and `/key3 value3` are supported when providing switch mappings.

### LINKED ISSUE #2409: fundamentals/configuration "Configuration" command line providers & inject Options
- [ ] Configuration: Document format supported for command line arguments provider #1382
- [x] Markup to show how to inject Options in Configuration document #437
- [x] Address MVP summit feedback on Configuration #2408

### PR DESCRIPTION
**Pull request by guardrex**
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?branch=pr-en-us-4307&tabs=basicconfiguration#commandline-configuration-provider)
Fixes #2409 
Fixes #1382

### 🎸 *Jam'in!* 🎷

[Review site topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?branch=pr-en-us-4307#commandline-configuration-provider)

This turned out to be a considerable overhaul of the CommandLine config provider section:
* The whole topic (big IMHO here) is *toooooo console app-ish*. We want to maintain the basic config explanations. What's a :boy: to do? 💡 :zap: **3RD TAB!** :zap: :bulb: The "Basic Configuration" is a tab with the basics (as the topic currently embraces in each of its samples). We can have the 2.x and 1.x bits in tabs 2 and 3 showing how the config applies to web apps. The reader isn't left wondering how it looks in a web app setup and then annoyed by the need to go look at other topics. If u don't like this, then I recommend we pull that tab 1 content out above the tab control and create a new section for the web app config (tabs).
* I attempt to clarify the argument format situation. Lists didn't look good, so I went with tables.
* I made an effort to explain out what's happening in the switch mappings, including a table of what's in the dictionary.
* @rachelappel, you may need to gut this or make large changes to it when you come to this topic for 2.0 updates. It's cool. In the meantime tho, this fixes the two open issues pertaining to this section, and closing two issues feels really good.
* Of course, this needs a good dev team :eye: to make sure I have the logic and behaviors are correct.

cc/ @danroth27

### CODE REVIEW

**Comment by guardrex** [comment]
The build doesn't like it too much that I add a *readme.md*. They (or MS) must have that locked down a little bit, so I'm going to remove that file. However, I think someone on the MS side should add it to the *sample_snapshot* folder that I created. The contents are simply:

> The code in this folder is used for snapshots of code in the Configuration topic at: https://docs.microsoft.com/aspnet/core/fundamentals/configuration

**Comment by Rick-Anderson** [comment]
@guardrex  can you add yourself as an author?

**Comment by guardrex** [comment]
@Rick-Anderson Done.

**Comment by guardrex** [comment]
Thanks @HaoK!

**Comment by guardrex** [comment]
@Rick-Anderson If you don't want the 1.x tab there, we'd still need to work out how to show the reader the use of `ConfigurationBuilder` versus using the baked-in config bits of `CreateDefaultBuilder` of 2.x.

Do you want me to take a stab at getting the 1.x part (tab) out while keeping the content? ... imo it would be good to keep all of the content here but re-organize it to drop the 1.x tab. I can have it done by tomorrow morning.

**Comment by Rick-Anderson** [comment]
@guardrex  keep the 1.x tab. For new content updates, we'll drop the 1.x content and just update docs for 2.x (and point to https://github.com/aspnet/Docs/blob/master/aspnetcore/common/_static/9-25-17.pdf)

**Comment by Rick-Anderson** [comment]
@guardrex  can I merge or do you need more work? We can leave the 1.x tabs.

**Comment by guardrex** [comment]
@Rick-Anderson Thanks. I'm cool. Go ahead. I was only concerned about the 1.x tab situation.

**Pull request merged**
