### PR TITLE
WIP: adding a model xplat

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/adding-model?branch=pr-en-us-3119#dotnet-ef-commands)

When I run `dotnet ef database update` on a Mac I get the following error:

the keyword &#96;integrated security&#96; is not supported on this platform

Per https://github.com/aspnet/EntityFramework/issues/4915 I removed `Trusted_Connection=True;` from the connection string. I now get this error:

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 25 - Connection string is not valid)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@natemcmaster @ajcvickers @kmjungersen  how do I connect the SQL Express on Mac?

**Comment by natemcmaster** [comment]
SQL express doesn't accept remote connections by default. You must enable them. http://support.webecs.com/kb/a868/how-do-i-configure-sql-server-express-to-allow-remote-tcp-ip-connections-on-port-1433.aspx

Integrated security is a windows-only feature. Your connection string must use User ID and Password instead. 

FYI for docs purposes, some users won't have a windows box. You might add a section for connecting to SQL Server via Docker. https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-docker

**Comment by Rick-Anderson** [comment]
@natemcmaster @danroth27  adding SQL Sever via docker image is a major hurdle for an introductory tutorial.  I'm guessing less than 15% of our target audience will be able to succeed on this step. It changes the Windows/Visual Studio 20 minute, high success rate tutorial into a 3 hr marathon/gauntlet of frustration.

**Comment by Rick-Anderson** [comment]
@spboyer  please advise.

**Comment by spboyer** [comment]
My suggestions are
* PostgreSQL instead of SQL Server
* SQL Server on Linux with u/p and not integrated security
* SQL Server on Azure (link to https://docs.microsoft.com/en-us/azure/sql-database/sql-database-get-started-portal)

> It changes the Windows/Visual Studio 20 minute, high success rate tutorial into a 3 hr marathon/gauntlet of frustration.

This may be an exaggeration on the amount of time, but do agree that we want to limit the new concept count. Keep in mind that the Linux/macOS community is different in a sense of using multiple tools, technologies, efforts so there is a higher tolerance level to such items.

@squillance

**Comment by natemcmaster** [comment]
If you want the easiest xplat tutorial possible, use SQLite. No server setup required.

**Comment by danroth27** [comment]
I believe SQLite is actually what we use in our dotnet new templates.

**Comment by Rick-Anderson** [comment]
@danroth27  confirmed SQLite is trivial to use. So I'll be making this tutorial the VS Code macOS version given SQLite doesn't run on Windows (or we don't want folks using SQLite on Windows). What about Linux?

I could provide windows instructions and macOS instructions.

**Comment by ajcvickers** [comment]
@Rick-Anderson Why don't we want people using SQLite on Windows specifically?

Keep in mind that SQLite isn't a good choice for showing Migrations anywhere, unless it's trivial stuff like adding a column, because it doesn't support very many schema modifications.

**Pull request closed without merging**
