### PR TITLE
Remove the redundant character "\"

### PR DESCRIPTION
**Pull request by charliethinker**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/fundamentals/static-files.md](https://github.com/charliethinker/Docs/blob/patch-2/aspnetcore/fundamentals/static-files.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C8%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201612081459438591-2349%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@charliethinker I think DocFX needs to escape `<` altho GFM doesn't. Have you tried building this with [DocFX](https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md#test-your-changes-with-docfx)?

**Comment by charliethinker** [comment]
`Inline code` with backticks that may not need to be escape `<`.

BEFORE:
-


AFTER:
-

**Comment by Rick-Anderson** [comment]
@charliethinker  Thanks. Looks much better with your fix. Arg - I forgot with the `code` ticks '<` doesn't need to be escaped. Sorry for the extra work I caused you and keep up the great work.

**Pull request merged**
