### PR TITLE
Fixing sample code to use ASP.NET Core 2.x DefaultHostBuilder to setup a host

### PR DESCRIPTION
**Pull request by seprix91**
Though, creating a host from WebHostBuilder is supported approach, it sounds 1.x though. Took liberty to upgrade sample to use more compact static CreateDefaultBuilder method

### CODE REVIEW

**Comment by scottaddie** [comment]
@seprix91 We'll need to display both 1.x and 2.x snippets in this doc. That is accomplished by using tabs. See the following doc for an example of tabs and the syntax: https://docs.microsoft.com/aspnet/core/security/authentication/identity-configuration. Is this something you have time to do? If not, I can take care of it.

**Comment by seprix91** [comment]
@scottaddie  Thanks for the clarification. yes, i can do that.

**Comment by scottaddie** [comment]
@seprix91 Thanks for your help! Let me know if you have any questions.

**Comment by guardrex** [comment]
Thanks @seprix91 for raising this issue/PR. I'm going to close here and perform user experience update on the topic along with the 2.0 sample update. https://github.com/aspnet/Docs/pull/5315

Thanks again! :rocket:

**Pull request closed without merging**
