### PR TITLE
clarified that only properties are considered for model binding

### PR DESCRIPTION
**Pull request by slav-squat**

### CODE REVIEW

**Comment by danroth27** [comment]
@rachelappel I actually think the original text is correct. Only public members are considered for model binding, but fields in general are not supported. We could just remove "Public" and just say that "Fields are not bound" to make this clearer.

**Comment by padding-cord** [comment]
Or "properties are considered for model binding while fields are not"

**Comment by danroth27** [comment]
Sure

**Comment by danroth27** [comment]
@padding-cord Can you update this PR with the new text?

**Comment by danroth27** [comment]
:shipit:

**Comment by danroth27** [comment]
@rachelappel Please rebase, squash and merge.

**Comment by rachelappel** [comment]
Thanks. merged. 878c7406390d2232942e35d84f7f25f2cb653b0f

**Pull request closed without merging**
