### PR TITLE
added middleware extensibility sample

### PR DESCRIPTION
**Pull request by hack2root**
Added extensibility middleware sample using Build.DependecyInjection https://build.experimentalcommunity.org/

`Edit add link`
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility-third-party-container-build?view=aspnetcore-1.0&branch=pr-en-us-7262)

### CODE REVIEW

**Comment by guardrex** [comment]
ping @davidfowl

**Comment by Rick-Anderson** [comment]
@dougbu  can you review or suggest someone to review [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility-third-party-container-build?view=aspnetcore-1.0&branch=pr-en-us-7262)
cc/ @guardrex

**Comment by guardrex** [comment]
We need to determine if we want this first. I suspect that we only need one example at this time and that SimpleInjector is a good representative example.

**Comment by guardrex** [comment]
In terms of links to community projects, we're currently recommending ...

* ASP.NET Core Community Standup (Tweet link to `@jongalloway`)
* https://github.com/quozd/awesome-dotnet
* https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md
* https://github.com/Microsoft/dotnet/blob/master/dotnet-consumer-projects.md
* https://github.com/Microsoft/dotnet/blob/master/dotnet-free-oss-services.md

... some are updated more regularly than others.

cc/ @jongalloway -- are there other outlets for informing the community about open source .NET Core projects?

**Comment by guardrex** [comment]
Hello @hack2root ... We decided that one example for this topic is enough to demo the basic idea. If you're looking for visibility for your container, explore adding it to the links that I posted above. :point_up: Thanks for your submission.

**Pull request closed without merging**
