### PR TITLE
Localization middleware must run before calling app.UseMvc()

### PR DESCRIPTION
**Pull request by polishninja**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  please approve

**Comment by ryanbrandenburg** [comment]
Maybe something more like
'Note: The localization middleware must be configured before any middleware which might check the request culture (i.e. app.UseMvc()).' That way we describe the exact conditions you must meet, rather than leaving it ambiguous with "early".

Definitly a good thing to note here though for those without a complete understanding of how middleware works.

**Comment by Rick-Anderson** [comment]
@polishninja  can you make Ryan's suggest change at https://github.com/Microsoft/Docs-1 ?

**Comment by Rick-Anderson** [comment]
fixed at https://github.com/Microsoft/Docs-1/pull/51

**Pull request closed without merging**
