### PR TITLE
Fix HTTPS vs SSL app setting reference

### LINKED ISSUE #6206: Documentation error regarding skipping HTTPS in development
The documentation states that you should add "LocalTest:skipSSL" to the appsettings.Development.json file, but in the mvc options you are looking for the skipHTTPS value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by OblivionSY**
Fixes #6206

### CODE REVIEW

**Comment by guardrex** [comment]
Does this need the same treatment? ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data/samples/final/appsettings.json

**Comment by guardrex** [comment]
Also check Line 271 of the topic. I see another one.

**Comment by OblivionSY** [comment]
Hadn't got down to 271 on the tutorial yet, but have made the change in anticipation. Working on getting the code change in this PR, but it wants to make a new one

**Comment by guardrex** [comment]
Go to the landing repo page and set the branch in the drop-down to `OblivionSY:patch-1` ... then navigate to that appsettings.json file and edit it. It will go on this branch and update the PR.

**Comment by guardrex** [comment]
Cool ... review and sign the CLA so we can accept this. :point_up: You only have to do it once.

**Comment by guardrex** [comment]
@Rick-Anderson Do you want Sir `@blowdart` to TAL?

**Comment by OblivionSY** [comment]
Ta, all done, and first community contribution made :)

**Comment by guardrex** [comment]
Thanks and congrats @OblivionSY! :tada: 🎈 🍻 

I don't think we need an engineering review, but Rick will say if it's best to call for one.

**Comment by blowdart** [comment]
Wait, I missed the chance to sign off on someone's first contribution? Damnit!

**Pull request merged**
