### PR TITLE
remove unnecessary package installs

### PR DESCRIPTION
**Pull request by tugberkugurlu**
as it was not suggested on the previous line

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tugberkugurlu  would you mind making the change at https://github.com/Microsoft/Docs-1
we're migrating from RST to GFM

**Comment by Rick-Anderson** [comment]
@tugberkugurlu  we're on MD here, do you want me to fix this or do you want to resubmit?

**Comment by tugberkugurlu** [comment]
@Rick-Anderson sorry, just seen this 😞 sure, you can make the change 👍

**Comment by Rick-Anderson** [comment]
moved to #2077

**Pull request closed without merging**
