### PR TITLE
Update SPA templates references to 2.0.0-rc1-final

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
We've now published version `2.0.0-rc1-final` of the SPA templates.

The final release should be soon (pending feedback) but this PR is to update the docs to reference the rc1 version in the meantime so people know they can try it.

### CODE REVIEW

**Comment by scottaddie** [comment]
Thank you for the PR, @SteveSandersonMS!

**Comment by agegould** [comment]
HI @SteveSandersonMS

Could you confirm before you release, how is TypeScript source file debugging possible using projects built using the @Angular 2.0.0-rc1-final project template?

JavaScript Source Maps don't appear to exist. Any ideas on this. Thanks.

**Comment by asgallant** [comment]
@agegould This is a known issue in Angular CLI, not a problem with .NET Core JavaScriptServices: https://github.com/angular/angular-cli/issues/8931

**Comment by astegmaier** [comment]
To be clear, [angular/angular-cli#8931](angular/angular-cli#8931) is about debugging source files where they are being processed by node through ssr, not debugging files after they are sent to the browser. The later scenario appeared to work fine with the cli-based templates last I checked.

**Pull request merged**
