### PR TITLE
Microsoft.AspNetCore.Mvc.WebApiCompatShim docs

### LINKED ISSUE #6116: Doc WebApiCompatShim
The [compat shim](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim/) is a useful tool for porting WebAPI 2 projects to ASP.NET Core. It’s well-explained in some [third-party blogs](https://www.strathweb.com/2015/01/migrating-asp-net-web-api-mvc-6-exploring-web-api-compatibility-shim/) and [here ](http://www.dotnetcurry.com/aspnet-mvc/1149/convert-aspnet-webapi2-aspnet5-mvc6) but I couldn’t find any first-party docs or blogs on it. Even the [GitHub repo](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim) has no description.

### PR DESCRIPTION
**Pull request by mjrousos**
Add a section on `Microsoft.AspNetCore.Mvc.WebApiCompatShim` to existing Web API migration docs

Fixes #6116 

@Rick-Anderson, @coderandhiker

`Edit by  @Rick-Anderson`
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-2.1&branch=pr-en-us-6280#microsoftaspnetcoremvcwebapicompatshim)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@mjrousos  I made a couple minor edits at https://github.com/mjrousos/Docs/pull/1
Can you review/update that PR and merge it into this PR?
On the file changes tab, there is no change at line 34. That's an annoying GitHub bug.

**Comment by Rick-Anderson** [comment]
@mjrousos  this looks good to me. Let me know if we can merge this.

**Comment by mjrousos** [comment]
Yep, I think it's ready to merge. Thanks.

**Comment by scottaddie** [comment]
Thank you for the help, @mjrousos

**Pull request merged**
