### PR TITLE
Beta8 version of ClassLibrary1

### PR DESCRIPTION
**Pull request by TomArcher**

### CODE REVIEW

**Comment by TomArcher** [comment]
@Rick-Anderson @danroth27 @Erikre Please review

**Comment by Rick-Anderson** [comment]
I don't think any dependent topics will need line changes but we should double check. :shipit:

**Comment by TomArcher** [comment]
I've checked already. Only one file references this sample, and it doesn't emphasize any lines.

**Comment by danroth27** [comment]
:shipit:

**Pull request merged**
