### PR TITLE
RTM update of part2 Intro to MVC

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@rachelappel  please review

**Comment by Rick-Anderson** [comment]
@rachelappel  hold off, I've got some complicated build issues I need to sort out.

**Comment by Rick-Anderson** [comment]
@rachelappel please review  
Why does this have merge conflicts?

**Comment by rachelappel** [comment]
@Rick-Anderson We can find out when it's merge time. Git will tell us.

**Comment by rachelappel** [comment]
Merged 445b3987d337989084e77f469ece3b639027caf6

**Pull request closed without merging**
