### PR TITLE
Removed Options entry from TOC

### PR DESCRIPTION
**Pull request by TomArcher**

### CODE REVIEW

**Comment by ardalis** [comment]
This was already done in a separate PR to beta 8.

**Comment by ardalis** [comment]
Actually, not a PR; it was a commit, to master: https://github.com/aspnet/Docs/commit/d3ded9f3c93e6dd17834504e1a65c22641312f6f

**Comment by TomArcher** [comment]
I wanted to remove the warning message from beta8 builds

**Comment by TomArcher** [comment]
Can you squirrel so I can merge?

**Comment by ardalis** [comment]
I'm not sure my squirrel means anything, but LGTM...
:shipit:

**Comment by Erikre** [comment]
Looks good to me too. :shipit:

**Pull request merged**
