### PR TITLE
[WIP] Tracking PR created for modifications of project.json overview

### PR DESCRIPTION
**Pull request by MisterJames**
Start of the article.
#53

### CODE REVIEW

**Comment by MisterJames** [comment]
Hope I did this right...created a tracking PR for feedback. If this isn't necessary, please let me know.

**Comment by danroth27** [comment]
@Erikre is working on the Working with DNX Projects (#50), which has a fair bit of overlap with this article. He is starting from the content that @glennc initially worked on (https://github.com/aspnet/Docs/blob/glennc/workingWithDnx/docs/dnx/projects.rst). The goal of this article is to provide a schema and syntax reference. Presumably many of the concepts and details can be linked to in the article @Erikre is working on.

**Comment by MisterJames** [comment]
@danroth27 So, I'll hold off on this then. I have a bit of a start, but I don't want to dupe effort. I'll put this guy on the shelf and pick another topic for the time being.

**Comment by danroth27** [comment]
@MisterJames @Erikre The Working with DNX Projects PR is now out. See https://github.com/aspnet/Docs/pull/372. It does cover the project.json properties in prose, but we still want to have a more concise project.json schema reference. We want something similar for global.json as well.

**Comment by danroth27** [comment]
This PR is pretty stale at this point. Closing

**Pull request closed without merging**
