### PR TITLE
2.0 DataProtection updates

### PR DESCRIPTION
**Pull request by ajaybhargavb**
#2975 

@blowdart @natemcmaster @Rick-Anderson

### CODE REVIEW

**Comment by natemcmaster** [comment]
Changes look fine. Only feedback is that it's not obvious from the doc to which version of DataProtection it applies. Someone still using 1.x will find it inaccurate. Is there a pre-defined way we should version the doc based on ASP.NET Core release? e.g. will there be `docs.microsoft.com/aspnet/core/v1.0/` and  `docs.microsoft.com/aspnet/core/v2.0/`? If not, it seems like we ought to have a 2.0.0 branch vs a 1.x branch or something. cc @Rick-Anderson @danroth27

**Comment by Rick-Anderson** [comment]
@natemcmaster  we will do a 2.0 version of this. @tdykstra  what's the best way to create a 2.0 version of this doc?  cc @scottaddie

**Comment by tdykstra** [comment]
tabs for now, then convert to the new conceptual versioning when it's ready

**Comment by tdykstra** [comment]
Implemented versioning using tabs
https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?branch=ajbaaska%2Fdp&tabs=aspnetcore2x
https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?branch=ajbaaska%2Fdp&tabs=aspnetcore2x
https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/extensibility/key-management?branch=ajbaaska%2Fdp&tabs=aspnetcore2x

@natemcmaster @Rick-Anderson If this looks good, the PR is ready to merge

**Comment by natemcmaster** [comment]
Cool! I didn't know you could do that. 👍

**Comment by ajaybhargavb** [comment]
I missed updating a couple of flowcharts https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/extensibility/key-management. I am currently taking a stab at Visio to update them. I'll update this PR once that is done.

**Comment by ajaybhargavb** [comment]
Updated

**Pull request merged**
