### PR TITLE
Using in-memory database first web api todo api update

### PR DESCRIPTION
**Pull request by damienbod**

### CODE REVIEW

**Comment by damienbod** [comment]
@Rick-Anderson Patch could be done better, did not want to change it, unless you want it

**Comment by Rick-Anderson** [comment]
@damienbod  patch shouldn't be in this one at all - I thought I removed it.  The Patch implementation is updating everything - right? That's not a correct patch. I think we should remove it. We really need a stand-alone article on patch using our patch provider.

**Comment by damienbod** [comment]
@Rick-Anderson patch is removed

**Comment by Rick-Anderson** [comment]
@damienbod  Awesome!!!

**Pull request merged**
