### PR TITLE
Update get-started-with-the-ajax-control-toolkit-cs.md

### PR DESCRIPTION
**Pull request by SimpleSamples**
I assume my wording needs improving but I think it helps to know how easy it is to do.

For some reason the toolkit was not added to my toolbox the first time so I downloaded (installed) again and then it got added. So perhaps I did something (that these instructions say to do) that I should not have and if so then it is especially important to say exactly what we are supposed to do.

I think the reason why the first sentence here shows a change is that I deleted a space.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Hold off review/merge until the aspnet repo is moved.

**Comment by Rick-Anderson** [comment]
@SimpleSamples 	appreciate your help but this is a very old article. We haven't had problem reports so I'm inclined to leave it as is.

**Comment by SimpleSamples** [comment]
On the subject of it being very old, I am not sure where to post this 
comment, but I am unable to find the current version of Displaying Data 
with the DataList and Repeater Controls (C#) 
<https://docs.microsoft.com/en-us/aspnet/web-forms/overview/data-access/displaying-data-with-the-datalist-and-repeater/displaying-data-with-the-datalist-and-repeater-controls-cs>. 
It is in Older Versions - Data Access 
<https://docs.microsoft.com/en-us/aspnet/web-forms/overview/data-access/> so 
it is old too but when I go to Getting Started with ASP.NET Web Forms 
<https://docs.microsoft.com/en-us/aspnet/web-forms/overview/getting-started/> 
I don't see Data Access. If the DataList and Repeater Controls are 
described in a tutorial that is current then there is no problem but if 
not then it is not clear what I should do. I will go through the current 
tutorials and then hopefully I can go through the older material if 
relevant. Is there somewhere more appropriate for this comment?

**Comment by Rick-Anderson** [comment]
That is the current version. ASP.NET Web controls haven't been updated.

**Comment by SimpleSamples** [comment]
Thank you. That is enough for now for this. There is a general problem 
of documentation implying it is outdated when it is not.

**Comment by Rick-Anderson** [comment]
> There is a general problem of documentation implying it is outdated when it is not.

Agreed. 
We're trying to figure out the best way to fix that. cc @mairaw

**Pull request closed without merging**
