### PR TITLE
Fix example that uses a custom requirement

### PR DESCRIPTION
**Pull request by spewu**
I think the example is wrong, so I suggest fixing it :)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@blowdart  please review

**Comment by blowdart** [comment]
Yup fine, it was running ahead of itself, operational requirements are the next section. :shipit:

**Comment by Rick-Anderson** [comment]
@spewu  Great catch! Thanks for improving our docs.

**Comment by spewu** [comment]
@Rick-Anderson No worries!

**Pull request merged**
