### PR TITLE
http -> https

### PR DESCRIPTION
**Pull request by gdoron**
Funny thing, the very line that says HTTPS should be used when possible is using HTTP... :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@gdoron  can you fix the `docs.asp.net <http://docs.asp.net>`_  to be
`docs.asp.net <http://docs.asp.net>`__ (they need two trailing _) so Travis will succeed?

**Comment by gdoron** [comment]
@Rick-Anderson , of course I can, but I'm not sure why...
A. I only changed HTTP to use HTTPS when available, as the doc says but doesn't do. So I really can't understand why the build is failing because of this change.
B. The doc doesn't say to use two trailing underscores, is it because the text and target are the same? 

If so, it probably should be documented too.

**Comment by Rick-Anderson** [comment]
@gdoron  I can fix it. When the doc was last checked in, we must not have had the travis build system working. It's failing because the link is used more than once. Yes, we should update the doc to say this is how you need to do links.

**Comment by Rick-Anderson** [comment]
@gdoron thanks! merged

**Pull request closed without merging**
