### PR TITLE
Missing  ContentPlaceHolder in master page

### PR DESCRIPTION
**Pull request by Sadegh-Ameri**
When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

[Internal Review Page](https://review.docs.microsoft.com/aspnet/web-api/overview/getting-started-with-aspnet-web-api/using-web-api-with-aspnet-web-forms?branch=pr-en-us-4899#add-client-side-ajax)

### CODE REVIEW

**Comment by scottaddie** [comment]
Build relies on *sample8.html* file added in PR #4898

**Comment by scottaddie** [comment]
Closing and reopening to trigger the build...

**Comment by scottaddie** [comment]
@Sadegh-Ameri Thank you again for taking the time to add this missing step.

**Comment by Sadegh-Ameri** [comment]
Thank you Scott for taking the time to revise and merge to master.
Sorry, I was not familiar with the notation.

**Pull request merged**
