### PR TITLE
Match the ASP.NET 4.x cookie name with the AuthenticationScheme created at first section

### PR DESCRIPTION
**Pull request by fujiy**
Match the ASP.NET 4.x cookie name with the AuthenticationScheme created at first section

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@HaoK  please review.

**Comment by HaoK** [comment]
This is a bit hard to tell what's going on exactly, since the docs are talking about identity + non identity use cases at the same time.  Maybe its better to qualify this with something like if using identity, use this change, otherwise if using cookies directly, use the current setting?

**Comment by Rick-Anderson** [comment]
@fujiy  can you make the change HaoK suggested?

**Comment by fujiy** [comment]
Yes, I'll do it. I just need to check the cookie name when using Cookie Auth instead of Identity

**Comment by Rick-Anderson** [comment]
@HaoK changes you requested made. Please review.

**Comment by Rick-Anderson** [comment]
@fujiy  double thanks again. Your changes will go live in the next 8 hours.

**Pull request merged**
