### PR TITLE
Update swagger tutorial to reflect latest Swashbuckle changes

### PR DESCRIPTION
**Pull request by domaindrivendev**
Reflect recent changes to Swashbuckle for ASP.NET Core, most notably the package rename to Swashbuckle.AspNetCore.1.0.0.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@domaindrivendev  can you look at the error
```
Unable to resolve [!code-css[Main](web-api-help-pages-using-swagger/sample/src/TodoApi/wwwroot/swagger/ui/custom.css)] . 
Can not find reference web-api-help-pages-using-swagger/sample/src/TodoApi/wwwroot/swagger/ui/custom.css. at line 332.
```

**Comment by domaindrivendev** [comment]
@Rick-Anderson - looks like wwwroot was added to the top level .gitignore recently (29d43601f87a883f0beade5b7231097ed9c4a15f) and as a result the referenced file is no longer there. I guess my commit was the first one to pick up the new gitignore setting. How would you like me to proceed?

**Comment by Rick-Anderson** [comment]
@domaindrivendev  `git add --force my/ignore/file.foo`

I added wwwroot because you rarely need it. I thought for files in the repository, .gitignore didn't apply.

**Comment by domaindrivendev** [comment]
@Rick-Anderson gothcha - just made the updates

**Comment by Rick-Anderson** [comment]
@spboyer  please review

**Comment by spboyer** [comment]
Thanks @domaindrivendev for the updates! ...and the product.

**Pull request merged**
