### PR TITLE
Move MVC to separate project.

### PR DESCRIPTION
**Pull request by danroth27**
@ardalis @MikeWasson @Rick-Anderson 

This is the big move of the MVC content to a separate Sphinx project. The ASP.NET content now lives under the aspnet folder and the MVC content lives under the mvc folder. Common content is in the sibling common folder.

Cross project links are made possible through [intersphinx](http://sphinx-doc.org/ext/intersphinx.html), which is now enabled for both projects. Cross projects links are currently only supported using `:ref:` - you can't use `:doc:` cross-project at this time.

Note that to enable offline builds each project carries a local copy of the inventory for projects it references and these inventories will need to be updated when new cross-project links are needed. Building a project produces an objects.inv that can be copied to any projects that want to reference it.

To make it easier to review this PR I split it across two commits. The [first commit](https://github.com/aspnet/Docs/commit/11eef3634a15d74103b44089c39bb9d0266cc49e) has all the file moves. The number of moved files involved is too large for GitHub to display, so here is a summary:

* docs -> aspnet
* docs/mvc -> mvc
* docs/_static -> common/_static
* docs/samples -> common/samples
* docs/stub-* -> common/stub-*
* docs/authors.txt -> common/authors.txt
* docs/samples/MigratingFromMvc5 -> mvc/migration/migratingfrommvc5/samples

The [second commit](https://github.com/aspnet/Docs/commit/b1ff219f1b38efa6a7257837f6922b5e463568a0) has all of the content changes. Please focus your review on the second commit.

### CODE REVIEW

**Comment by MikeWasson** [comment]
Both projects build fine on my local machine - Is there a way to test the cross-project links locally, or do we need to stage it?

**Comment by danroth27** [comment]
You can try modifying the intersphinx-mappings for both projects to point to your local file system instead of the production URIs.

Once we get this initial commit in you will be able to test cross project links with the published content by updating one side of the link at a time.

**Comment by MikeWasson** [comment]
:shipit:

**Comment by danroth27** [comment]
b7613c28935ace9b24f456ee588c17abb7b142fc

**Pull request closed without merging**
