### PR TITLE
Search enhancements

### LINKED ISSUE #8000: Searchstring not displayed after search
With the implementation for the search textbox, after searching the search results are correctly displayed, but the search textbox is blank.  Recommend:

1. Add public string SearchString { get; set; } to class MovieGenreViewModel
2. Populate value in Index controller (movieGenreVM.SearchString = searchString;)
3. Change title search textbox on Index view to &lt;input asp-for="SearchString"&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by daveabrock**
Fixes #8000

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Looks great. Minor tweaks in my commit. Avoid future tense and no long sentences.

**Comment by daveabrock** [comment]
Great - thanks @Rick-Anderson! Do you need anything else from me?

**Comment by Rick-Anderson** [comment]
Nothing from this. Did you want to make the same change to the Razor Pages version?
All this will get alot easier when @tdykstra 	and I get rid of the includes.

**Comment by daveabrock** [comment]
Sure - can you give me a link to that version?

**Comment by Rick-Anderson** [comment]
I'll open an issue can tag you.

**Pull request merged**
