### PR TITLE
Fix LF in ./aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml

### LINKED ISSUE #10671: Fix LF in ./aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml
See  #10641

### PR DESCRIPTION
**Pull request by JulioJu**
Fixes #10671

Nothing is changed except line ending: CRLF line ending is changed to LF.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Sorry, reopen is not an option for me. You'll have to do another PR.

**Comment by JulioJu** [comment]
Ok, so strange, today I can reopen the current pull request, so I done it ;-)

**Comment by Rick-Anderson** [comment]
@JulioJu 	can you try going to https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro/samples/cu21/Pages/About.cshtml.cs

Edit in the browser and paste the fixed up code.

**Comment by JulioJu** [comment]
@Rick-Anderson 

I make some tests, without results. And same as before it automatically close the pull request. 

With my others tests, now we could read “ **Pull request successfully merged and closed You’re all set—the JulioJu:fix-lf-line-ending branch can be safely deleted.** ”. 

There is probably a bug with github.com, I don't know where and why. Therefore I try to make a new Pull Request.

**Comment by JulioJu** [comment]
@Rick-Anderson @herohua @spottedmahn @cillroy 

For information:

As we can see in this current PR, change a file from CRLF to LF seems cause problems with OpenPublishing.Build and github.com when we use the pre-commit hook. It automatically close the PR, say wrongly that the PR was merged, false merge conflicts.

The only solution that I've found is simply to not use the pre-commit hook, by changing the file `.gitattributes` to `* text=binary`. Then delete `CR` characters thanks a tool like `GNU sed` , then commit changes (without the local file `.gitattributes`).

**Comment by Rick-Anderson** [comment]
@JulioJu 	take a look at https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf
It looks like you're supposed to deal with that on the client side, not in the repo.

**Comment by JulioJu** [comment]
Yes it is, we could use `git config core.autolf false`, I known this command, but I don't want change global config for only one repository. At https://github.com/aspnet/Docs/issues/10641 I've already referenced https://help.github.com/articles/dealing-with-line-endings/ that explain that too ;-). 

As you which, but as I shown in https://github.com/aspnet/Docs/issues/10641#issue-403544281 , as all files has already LF line ending except ./aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml I believe it could be cool for futur Mac or Linux contributors to at least correct Line ending of this file. As it, not need to change global config of the local git or the .gitattribute. Furthermore, it's always better to have something unified ;-).

**Pull request merged**
