### PR TITLE
Update PW recovery to RP and secure templates

### LINKED ISSUE #1405: Improvements and updates to Identity docs
**Things that are out of date**

- [x]  Doc at https://docs.asp.net/en/latest/security/authentication/accconfirm.html contains out-of-date code snippet (e.g., `RedirectToAction` should be `RedirectToLocal`, and the `EnsureDatabaseCreated()` should be removed). Generally, all the code blocks in this page should be updated to match the final templates.
- [x] The screenshot of VS under "Enable SSL in Visual Studio" on https://docs.asp.net/en/latest/security/authentication/accconfirm.html is out of date - doesn't match current tooling and refers to version 1.0.0-beta7 and the ASPNET_ENV variable.
- [x] Doc at https://docs.asp.net/en/latest/security/authentication/2fa.html contains code blocks that don't match latest template (e.g., it has a link to the `RemovePhoneNumber` action, whereas the shipping template uses a `<form>` that does a POST)

- [ ] **Improvement to "account lockout" docs**
Regarding https://docs.asp.net/en/latest/security/authentication/2fa.html, we should mention that, to enable it, you also need to modify your `Login` action to pass `lockoutOnFailure: true`. Currently there's no mention of that, and it's not easy to discover.

- [ ] **Improvement to "account confirmation" docs**
We need to address the point about enabling account confirmation for existing sites that already have users. That (clearly important) scenario isn't mentioned at all, and there's a major gotcha: by enabling account confirmation, you are locking out all your existing users, because their accounts are not confirmed. To work around this, you either need to edit your DB to mark all existing users as being confirmed, or you need to confirm them somehow (batch-send emails with confirmation links, or similar).

### LINKED ISSUE #5332: security/authorization/secure-data convert to RP
address #5144

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #5332
Fixes #1405

[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?branch=pr-en-us-5383&tabs=aspnetcore2x)

The only security changes was removal of the section [Prevent login at registration](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?tabs=aspnetcore1x%2Csql-server#prevent-login-at-registration)

With the current templates, adding that code is no longer necessary. All you need is to comment out
```
// await _signInManager.SignInAsync(user, isPersistent: false);
```

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@HaoK  The only security change was removal of the section [Prevent login at registration](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?tabs=aspnetcore1x%2Csql-server#prevent-login-at-registration)

With the current templates, adding that code is no longer necessary. All you need is to comment out
```
// await _signInManager.SignInAsync(user, isPersistent: false);
```

Can you confirm that security change? 

The new sample uses RP (Razor Pages) with the  .NET Core SDK, version 2.1.4 and addresses aspnet/Announcements#284
aspnet/Announcements#285

**Comment by Rick-Anderson** [comment]
@smitpatel please review.

**Comment by Rick-Anderson** [comment]
@HaoK  or @smitpatel please very quick/short review.  The only security change was removal of the section [Prevent login at registration](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?tabs=aspnetcore1x%2Csql-server#prevent-login-at-registration)

**Comment by HaoK** [comment]
Ok if we are just removing a section seems fine...  @blowdart any issues with removing this?

**Comment by Rick-Anderson** [comment]
@HaoK @blowdart  I removed that section **and** built the project with RP (Razor Pages)  with the  .NET Core SDK, version 2.1.4 to  addresses aspnet/Announcements#284 and aspnet/Announcements#285

So it does change from MVC controllers to RP - but all the code changes are the same with the noted exception.

**Comment by Rick-Anderson** [comment]
@HaoK Is there any support for adding a time limit on [ConfirmEmailAsync(user, code)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.confirmemailasync?view=aspnetcore-2.0#Microsoft_AspNetCore_Identity_UserManager_1_ConfirmEmailAsync__0_System_String_)

If not can you suggest how to limit time?

**Comment by smitpatel** [comment]
@Rick-Anderson - Since its been long time I went through docs and I m not expert in this domain, I may not be best person to review this. @HaoK could give approval to this. And if there are any pending issues from previous verification item which still persists should be easily caught when it will be verified again in upcoming release.

**Comment by HaoK** [comment]
@Rick-Anderson the default time for confirm tokens to be valid is 1 day

**Comment by blowdart** [comment]
remove all you want :)

**Pull request merged**
