### PR TITLE
Fix localization highlighting issues

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@hishamco  nice fixes. Next time I update this article I'll replace hard coded string ranges with snippet tags.

**Comment by hishamco** [comment]
Which snippet tags that you mean? I can help you on that

**Comment by Rick-Anderson** [comment]
Take a look at the [middleware doc](https://raw.githubusercontent.com/aspnet/Docs/master/aspnetcore/fundamentals/middleware.md).

You can use [`#region snippet` ](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/sample/Chain/Startup.cs#L9 )to reference code and avoid hard coding line numbers and ranges. You can even nest snippets and the OPS tool will remove the  `#region snippet`  from the rendered code. 

It's not worth updating the MD/code samples just to replace line numbers with snippets. When we're updating the doc or working on it, it's nice to upgrade to snippets.

**Comment by Rick-Anderson** [comment]
see also https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md#code-snippets

**Comment by hishamco** [comment]
Thanks seems the `#region snippet` is better option, but it become tedious when the highlighting lines scattered

**Pull request merged**
