### PR TITLE
Changed Web Api Help Pages using Swagger, added sub pages for NSwag & Swashbuckle

### PR DESCRIPTION
**Pull request by zuckerthoben**
Concerning #4258 

Mainly I changed the [existing documentation](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md) concerning Swagger and subpaged the Swashbuckle specific content. I then also created a sub page for NSwag, together with some sample code. 

I had issues figuring out how the code snippets and image links work in the article.

Commit [2896729](https://github.com/zuckerthoben/Docs/commit/2896729456ee79da000694f65a429deb683b1b2a) is a rebase of all other commits for easier reviewing of changes.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@zuckerthoben  can you fix the 


13  errors and 1 warning in aspnetcore/tutorials/getting-started-with-swashbuckle.md  and 2 errors in
aspnetcore/tutorials/getting-started-with-NSwag.md

**Comment by scottaddie** [comment]
@zuckerthoben Please let me know once the errors are fixed, and then I'll review your PR.

**Comment by Rick-Anderson** [comment]
@zuckerthoben  do you need some help fixing the errors?

**Comment by zuckerthoben** [comment]
I will look at these errors today after work. I will come back to you if I need help, thank you :)

**Comment by Rick-Anderson** [comment]
@zuckerthoben you can see the errors in  the [Details](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C2%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201711020821007080-4710%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kWy%2F3w2D7G12giHYYWfMZP%2BeBChTC%2BpkQg3p1AgV0jw%3D&st=2017-11-02T08%3A19%3A25Z&se=2017-12-03T08%3A24%3A25Z&sp=r) report

**Comment by Rick-Anderson** [comment]
@zuckerthoben do you want some help with the errors?

**Comment by Rick-Anderson** [comment]
@zuckerthoben  let me know if you need some help with the errors and when you're ready to work on this and we can reopen it.

**Pull request closed without merging**
