### PR TITLE
WIP: Pkellner built-in TH

### PR DESCRIPTION
**Pull request by Rick-Anderson**
replaces #2644

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Pkellner - impossible to rebase and fix the TOC so I created a new branch.  Make sure you follow the format/style of [Working with Forms](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms)

cc/ @GuardRex

**Comment by spboyer** [comment]
This covers #1948 as well correct. Appears the content is there. Please be sure to set `Fixes #1948` in PR.

**Comment by GuardRex** [comment]
When I did the outline, I thought that each TH would get its own sample. It might be possible to have one sample cover all (or most) of the TH's in one shot :gun: (perhaps with a few alternate `Startup`s required). Otherwise, I think you covered everything in that outline. The `<distributed-cache>` TH is a different doc, so those bits aren't relevant (yet).

**Comment by pkellner** [comment]
@GuardRex I've not completely thought through the example aspect of the built-in TH docs I'm working through. I am keeping a Visual Studio project with all my sample code in a very organized way so it could become the "example" but because of the nature of TH's (each being so simple and discrete) I'm not sure they need a sample project.  Might be worth taking offline and hashing out and then putting summary notes/suggestions here.  The Distributed TH is a different beast because of the nature of, well, "distributed".  That opens up a world of options. I think all the other tag helpers are more straight forward.  I was thinking for my 4th TH I should work on Distributed because we are all thinking about it.

**Comment by Rick-Anderson** [comment]
distributed cache TH will be it's own doc

**Comment by GuardRex** [comment]
> each being so simple and discrete

Yeah ... and if the goal isn't to have a ton of doc stubs lying around for months, then it makes sense to **NOT** put samples in for the first round of these. Could always come back later and add sample(s).

**Comment by pkellner** [comment]
@Rick-Anderson I've not got this PR (2698) on my local checked out and it looks to me like it has all the latest changes I made.  @GuardRex made another 10 or so suggestions I'd like to incorporate before you review the three built in TH's here.  I'm assuming I should just make changes and then commit to this branch?  I don't see the TOC entry on top of any of the docs. Am I right in assuming you will do that? Luke gave a format for it I could follow if you'd rather me do it.

**Comment by GuardRex** [comment]
The TOC is a doc tho. What I posted was the metadata that goes at the top of a doc. if surf around the repo, you'll see the TOC docs.

**Comment by pkellner** [comment]
Sorry, but lost again in GitHub Pull Request. I have my changes ready on my local branch ra-pKellner-built-in-TH that I've pushed to my fork of docs (https://github.com/pkellner/Docs).  When I try to create the pull request with github (see picture below), it looks like it wants to change everything. Any clue how I have gotten lost here? I would have expected the pull request would be small since I pulled that branch so recently to my local, made changes locally, checked those in and pushed to my repo.  

My Attempted Pull Request

**Comment by pkellner** [comment]
I've reset my local fork and am going through and making a pass of changes.  I will have those checked in later today.  I'm removing the "warning" I have about CacheItemPriority.NeverRemove because based on the source code here: https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs I don't think that cache will ever be removed. If I'm wrong, please LMK @GuardRex or @Rick-Anderson

**Comment by Rick-Anderson** [comment]
>> [!WARNING]
> The `priority` attribute does not guarantee a specific level of cache retention. `CacheItemPriority` is only a suggestion to the Cache Provider. Setting this attribute to `NeverRemove` does not guarantee that the cache will not be evicted. `CacheItemPriority` sets the priority the cache evicts items under memory pressure. 

@JunTaoLuo can you confirm the following?

Setting this attribute to `NeverRemove` does ~~not~~ guarantee that the cache will not be evicted.

**Comment by JunTaoLuo** [comment]
For the current FTS and LTS releases, setting the attribute to `NeverRemove` guarantees that the memory pressure triggered compaction will not evict that entry. It may still be evicted due to expiration or expiration tokens. Note that this behaviour is likely to change, see https://github.com/aspnet/Caching/issues/221.

**Pull request closed without merging**
