### PR TITLE
Update Getting Started with ASP.NET MVC 5 to VS 2017 #4557

### PR DESCRIPTION
**Pull request by isaac2004**
Running PR to upgrade [Getting Started with ASP.NET MVC 5](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/) to VS 2017 per #4557

### CODE REVIEW

**Comment by isaac2004** [comment]
@Rick-Anderson this is done, let me know if there any additional changes

**Comment by Rick-Anderson** [comment]
For IN  aspnet/mvc/overview/getting-started/introduction/getting-started/_static/image1.png use

image

**Comment by isaac2004** [comment]
!!! Totally didn't even think of all my projects there. Update done

**Comment by Rick-Anderson** [comment]
Can you make  aspnet/mvc/overview/getting-started/introduction/getting-started/_static/image1.png look more like the original? Use paint to resize it down 50%.

**Comment by Rick-Anderson** [comment]
image under project, and it's a good place to start your application.
image4.png
is too big. Can you use a smaller window? You can shoot it with the snipping tool - I'm going through the changes now. Really nice work.

**Comment by Rick-Anderson** [comment]
under
 the image below, the port number is 1234. When you run the application, you'll see a different port number. 

image5.png is too big

**Comment by Rick-Anderson** [comment]
Oops, accidental closure.

**Comment by isaac2004** [comment]
updated getting-started images

**Comment by Rick-Anderson** [comment]
edit the big images in notepad and resize to 50%
some you can get away with that. For 
image4.png (under The controller is open in the IDE.)  it would be nice to reshoot. Make VS much smaller and take the shot.

**Comment by Rick-Anderson** [comment]
image4.png resize 50 %
image

**Comment by Rick-Anderson** [comment]
image5.png resize 50%

**Comment by Rick-Anderson** [comment]
adding a view.
image7.png -I'd crop that to show just the markup or just the solution explorer. Or resize to 40%

**Comment by Rick-Anderson** [comment]
The rest of the images look great. Nice work.

**Comment by isaac2004** [comment]
updated all images

**Comment by Rick-Anderson** [comment]
@isaac2004  fantastic work. Much appreciated.

**Pull request merged**
