### PR TITLE
1385000, implement basic crud functionality with EF6

### PR DESCRIPTION
**Pull request by john-par**
Update for task to use .NET tutorial template.

### CODE REVIEW

**Comment by john-par** [comment]
@tdykstra this PR is ready for your review. Please let me know what you'd like changed.

Also, I received an email from Tami Fosmark letting me know that, when I submit PRs, I am welcome to make recommendations about removing screenshots and to ask for your feedback. For this PR, I had already removed the screenshots I determined to be repetitive or unnecessary. If you'd like me to revert any of those changes, please let me know.

In the future, after I submit my PR to you for review, I will add comments in-line to the images that I think should be removed and you can let me know your thoughts.

Tami mentioned that conceptual images are unlikely to require change, so I will not consider those as I 
work through the articles.

**Comment by Rick-Anderson** [comment]
>  I had already removed the screenshots I determined to be repetitive or unnecessary

The more images you can remove, the better. cc @tdykstra 	in case he has a different idea

**Comment by tdykstra** [comment]
>The more images you can remove, the better. cc @tdykstra in case he has a different idea

The more images **of the IDE** you can remove, the better.  Conceptual diagrams (and by that I refer to anything that isn't a how-to-do-it-in-the-IDE image) are helpful, don't go out of date and so don't require maintenance time.

**Comment by tdykstra** [comment]
>>The more images of the IDE you can remove, the better. Conceptual diagrams (and by that I refer to anything that isn't a how-to-do-it-in-the-IDE image) are helpful, don't go out of date and so don't require maintenance time.

Images of the the sample app's UI are also candidates for deletion, as they get out of date when template styles change.  But each tutorial has to keep at least one of those at the start to show people what it is they're going to build.

**Comment by john-par** [comment]
Thanks! In that case, this PR is ready to be merged.

**Pull request merged**
