### PR TITLE
Clarify 1.1 features require 1.1

### LINKED ISSUE #2579: Clarify in docs for 1.1 features that the app must consistently target 1.1
We've seen issues where customers are trying to use 1.1 features in a project that targets netcoreapp1.0. Customers create a new project in VS, which target 1.0, and then add a 1.1 package and then don't understand why it doesn't work. This happened recently, for example, with someone following https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging#appservice and running into issues because they used the Microsoft.Extensions.Logging.AzureAppServices package in a 1.0 project.

We should clarify everywhere we discuss 1.1 features that your entire project should target Current bits.

### PR DESCRIPTION
**Pull request by GuardRex**
Fixes #2579

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@GuardRex really nice changes

**Comment by GuardRex** [comment]
@Rick-Anderson Thanks!

One thing bothering me tho. We're going sentence case for headings. It just hits my :eye: wrong to see ...

### Additional resources

What do you think about going with ...

### Resources

Of course, these are "additional" resources. We could just drop that word.

... and *prevent serious eye injuries!* :smile:

cc/ @ardalis @danroth27 @spboyer @tdykstra

**Comment by Rick-Anderson** [comment]
Resources is probably better, i'm all for cutting fat. I'll defer to @tdykstra

**Comment by tdykstra** [comment]
The capitalization issue is just what comes with using sentence capitalization for headings; I wouldn't be inclined to use that as a reason for changing the content of the headings.  That said, I'm OK with "Resources" for conceptual article types.  The standard heading for this section in the past has always been "Next steps" and I'm inclined to stick with that at least in tutorials.

**Pull request merged**
