### PR TITLE
Removed mention of ASPNET_ENV

### PR DESCRIPTION
**Pull request by leonardlabat**
Addresses #872

### CODE REVIEW

**Comment by danroth27** [comment]
ASPNET_ENV actually still works in RC1, although the tooling uses Hosting:Environment. There are issues with the colon in the env var name on Linux.

**Comment by leonardlabat** [comment]
Oh ... Maybe I misunterstood the original issue. Wasn't it stating that ASPNET_ENV should be removed ?

**Comment by danroth27** [comment]
Yeah, the issue wasn't very clear. I do think it is a good idea to update the screenshots to show what is actually shown by VS in RC1 (Hosting:Environment). So your change is good. However, on Linux the colon in the env var name is problematic, so we need to account for that somewhere. @shirhatti can you help out with this?

**Comment by shirhatti** [comment]
Thanks for the PR. Merged in 3e5d5f817277cb8cd8565bd8314bdd76c1504bf1

**Pull request closed without merging**
