### PR TITLE
Show how to bind options to a specific config section

### PR DESCRIPTION
**Pull request by diddledan**
- fixes issue #867.
- Based on suggested code from @danroth27.

Code builds successfully using `dotnet.exe` command line utility.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@divega please review

**Comment by divega** [comment]
Please have @haok review instead.

**Comment by HaoK** [comment]
Looks fine, maybe we should consider updating the parent options to also have a MySubOptions property, to demonstrate that nested complex options bind recursively.

**Comment by Rick-Anderson** [comment]
Updated #829  with consider updating the parent options to also have a MySubOptions property, to demonstrate that nested complex options bind recursively.

@rachelappel  please resolve merge conflict and merge.

**Comment by rachelappel** [comment]
Merged b1faedae64f6c1884bf260449e69a20dead4eb43

**Pull request closed without merging**
