### PR TITLE
CC60988: New paragraph added

### PR DESCRIPTION
**Pull request by v-maudel**
Hello, @zuckerthoben,
This proposed file change comes from https://github.com/aspnet/Docs.de-de/pull/22 
"The actions outlined under "Customize and Extend" are actually mandatory and not performing these steps will produce an error. The documentation is misleading about this fact."

Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by zuckerthoben** [comment]
Seems fine @scottaddie

**Comment by Rick-Anderson** [comment]
We usually don't like to add warnings of errors when you skip steps. Someone will always skip a step and they often want to put in a warning "Don't skip the next step".

Unless there is some reason people will routinely skip the step I think we're better off not adding the warning.

**Comment by v-maudel** [comment]
Hi @Rick-Anderson , @scottaddie, 

Could you please let me know if there is any update on this?

Thanks.

**Comment by scottaddie** [comment]
@v-maudel Sorry for the delay. It's on my todo list for today.

**Comment by v-maudel** [comment]
Thanks @scottaddie

**Comment by scottaddie** [comment]
@v-maudel I've confirmed that the tutorial is fully functional after following all the steps before the [Customize and extend](https://docs.microsoft.com/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1#customize-and-extend) section. No errors were encountered. We do, however, really appreciate the PR. Apologies again for the delay in reviewing it.

**Comment by v-maudel** [comment]
Thanks @scottaddie

**Pull request closed without merging**
