### PR TITLE
Document limitations of updating the Identity schema when targeting SQLite #1210

### LINKED ISSUE #1210: Document limitations of updating the Identity schema when targeting SQLite
https://github.com/aspnet/identity/issues/816

### PR DESCRIPTION
**Pull request by isaac2004**
Document limitations of updating the Identity schema when targeting SQLite

Added note include to be placed on Identity pages that may use SQLite as datastore

  Fixes #1210

### CODE REVIEW

**Comment by isaac2004** [comment]
@blowdart please provide aspnet core pages to add this note

**Comment by scottaddie** [comment]
Your help is appreciated, @isaac2004. Nice work on this one.

**Comment by isaac2004** [comment]
@scottaddie are we not worrying about the core docs?

**Comment by scottaddie** [comment]
@isaac2004 If Barry sees a need, then we'll address that in a separate PR. Thoughts, @blowdart?

**Pull request merged**
