### PR TITLE
added warning you can't deploy 64 bit to free Azure

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Need a warning to tell folks they can't publish 64 bit version. Many customers will create app in VS and use the publish dialog, which gives you two 64 bit options.

### CODE REVIEW

**Comment by danroth27** [comment]
This doesn't feel like the right article to put this in. This should go under Publishing and Deployment somewhere.

**Comment by Rick-Anderson** [comment]
@danroth27  I think it needs to go in multiple places. I think we should leave it here and I'll add it Publishing and Deployment. The title is "Choosing the Right .NET For You on the Server" with a section on ".NET Core" - so customers will want to take advantage of core - and many will want to take advantage of 64 bit. If they do from VS15,  they'll get back a 500 error with no information.

**Comment by Rick-Anderson** [comment]
@danroth27 can you merge this PR? It's a short warning for what I think will be a common problem.

**Comment by danroth27** [comment]
I want to get this issue documented, but I still think this is the wrong doc. This doc was specifically for helping you pick your .NET *flavor* (.NET Core vs .NET Framework vs Mono). It has no discussion of bitness or specific hosting environments. Ideally I would put this in our topics on deploying to Azure (ex https://github.com/aspnet/Docs/issues/104).

**Comment by Rick-Anderson** [comment]
close for now, monitor customer problems with this

**Pull request closed without merging**
