### PR TITLE
replace GetTempFileName

### LINKED ISSUE #3589: Consider replacing GetTempFileName with GetTempPath and GetRandomFileName
Consider removing uses of `GetTempFileName` as

> The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files.

The following files use this:
ProfileController
StreamingController
UploadFilesController

See aspnet/Coherence-Signed#510 for more information.

cc @Eilon

### PR DESCRIPTION
**Pull request by Rick-Anderson**
fixes #3589

### CODE REVIEW

**Comment by jbagga** [comment]
Consider making the same changes to the following (and any other uses of `GetTempFileName()`):

https://github.com/aspnet/Docs/blob/74a44669d5e7039e2d4d2cb3f8b0c4ed742d1124/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Controllers/UploadFilesController.cs

https://github.com/aspnet/Docs/blob/74a44669d5e7039e2d4d2cb3f8b0c4ed742d1124/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Controllers/StreamingController.cs

**Comment by jbagga** [comment]
Ah I see. This is fine. Thanks! @Eilon

**Comment by Rick-Anderson** [comment]
(Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?branch=pr-en-us-3639) and search for `GetTempFileName`

@ardalis  what's the profile controller for? Can we delete it?

**Comment by Rick-Anderson** [comment]
@jbagga  please review addition:
The 65535 files limit is per server, so another app on the server can use up all 65535 files.

**Comment by rharor** [comment]
I get "Error	CS1503	Argument 1: cannot convert from 'Microsoft.Extensions.Primitives.StringSegment' to 'string'" in MultipartRequestHelper for 'boundry' on line "if (string.IsNullOrWhiteSpace(boundary))"

**Pull request merged**
