### PR TITLE
Aftab ansari/angular js solution explorer

### PR DESCRIPTION
**Pull request by AftabAnsari10662**
Correct and right image added.

Instead of AngularSample it must be AngularJsSample.
Bower dependencies should appear at top.

### CODE REVIEW

**Comment by aftab10662** [comment]
@Rick-Anderson Please review the changes.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  please review.

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson reviewed. looks good :)

**Comment by Rick-Anderson** [comment]
@AftabAnsari10662  @fiyazbinhasan  Thanks guys.

**Pull request merged**
