### PR TITLE
C19382: <script> tags in code should be removed

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @tfitzmac,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

Many thanks in advance.

When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @tfitzmac ... we get it squared away.

@scottaddie @Rick-Anderson I took a peek ... I think Twitter depreciated this approach. Therefore, the whole topic could be scrapped. I'll have some free time later ... after June 4th ... would u like me to remove the topic later? If so, I'd like to patch this for now by code-fencing the script tags and not deleting the opening tags of each.

**Comment by Rick-Anderson** [comment]
@carolinacmoravia  can you give us an example of where the format is broken?

**Comment by guardrex** [comment]
https://docs.microsoft.com/en-us/aspnet/web-pages/overview/ui-layouts-and-themes/twitter-helper#see-the-results

**Comment by Rick-Anderson** [comment]
[Spanish ](https://docs.microsoft.com/es-es/aspnet/web-pages/overview/ui-layouts-and-themes/twitter-helper#see-the-results)looks OK

**Comment by guardrex** [comment]
They be buttons and timelines tho.

**Comment by guardrex** [comment]
AFAICT Twitter has completely depreciated the approach pitched by the topic.

**Comment by Rick-Anderson** [comment]
I get it, it's not just localized.

**Comment by guardrex** [comment]
That's right. They're doing it differently now. Different script ... different tag setup.

**Comment by Rick-Anderson** [comment]
The PR doesn't get it right
image

**Comment by guardrex** [comment]
Yes ... I agree.

I was going to pitch just code-fencing those scripts for now. Come back later and delete the whole topic. ...... or you could mark it for overhaul/update.

**Comment by guardrex** [comment]
I don't mind re-writing it, too. I'd do it after June 4th tho.

**Comment by Rick-Anderson** [comment]
See #6578

**Pull request closed without merging**
