### PR TITLE
move sub tocs to main toc

### LINKED ISSUE #2406: Improvements to site navigation
- [x] Make expandable TOC nodes go to index.md page for the group rather than just expand/collapse the TOC, similar to how the docs.ms.com/dotnet/articles site works.
  - [x] Fundamentals and Fundamentals/Server - make overview topic for Fundamentals #2364
  - [x] Security/Authentication/Social #2341 #2361
  - [x] Tutorials - index.md should organize the list of tutorials and facilitate navigation to tutorials in other parts of the TOC
- [x] Revise structure of MVC section of TOC. 
- [x] Revise structure of Deployment section of TOC. 
- [x] Review and revise TOC node titles to make them work better with the TOC filter box. E.g., on the .NET site entering "tutorials" gets you to all of the TOC sections that have tutorials, but doing that on the ASP.NET Core site misses many of them.

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #2406

[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/?branch=td-toc)

### CODE REVIEW

**Comment by tdykstra** [comment]
Nothing else.

**Comment by guardrex** [comment]
@tdykstra I don't guess you intended to have the *Performance* topics to end up inside the *Security* node, right?

capture1

**Comment by tdykstra** [comment]
Right, thanks, I'll fix it.

Sent from iPhone
________________________________

**Comment by guardrex** [comment]
I was like ... "Whatttt??? ... It was right there a second ago!" lol

**Pull request merged**
