### PR TITLE
remove nonsense about in-memory caching

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by ardalis** [comment]
Because it should be obvious, or ? It's not distributed, which is the issue (thus requests may get inconsistent results based on which node serves a given request)

**Comment by Rick-Anderson** [comment]
@ardalis  not true. I'll be updating the in-memory version this week. ARR makes it work fine as I explain.

**Comment by ardalis** [comment]
Isn't ARR for IIS only?

**Comment by Rick-Anderson** [comment]
Yup, but I explain sticky bits. You can’t category dismiss in-memory for distributed.

**Pull request merged**
