### PR TITLE
RazorPages is ambiguous - rename app MyRazorPages #4695

### PR DESCRIPTION
**Pull request by isaac2004**
#4695 

Rename RazorPages with RazorPagesSample. 

- Renamed Folders/Files in sample folder
- Rename namespace and references in sample projects
- Changed all references in document

@Rick-Anderson please review

### CODE REVIEW

**Comment by guardrex** [comment]
I was under the impression that the word "Sample" would appear at the end of the name (i.e.,  "RazorPagesMovieSample" instead of "RazorPagesSampleMovie") ... and even that perhaps only "RazorPages" needed to become "RazorPagesSample" to avoid the ambiguity that was pointed out (i.e., the rest of them are fine).

The other thing that seems a little curious is that the `@model` directives have full namespaces in many (or most) cases, but I thought we were angling to use the *_ViewImports.cshtml* file to avoid that, including in sub-folder situations (e.g., *Pages/Customers/*.cshtml).

Couple of other tiny nits:

* A double "n" in "namespace" :point_right: aspnetcore/mvc/razor-*pages/index/sample/RazorPagesSampleContacts2/Pages/_ViewImports.cshtml*
* Consistency: Use "InMemoryDb" for the name of the in-memory dB :point_right: *mvc/razor-pages/index/sample/RazorPagesSampleContacts/StartupDebug.cs*

**Comment by isaac2004** [comment]
@guardrex can do these that's fine. All I really did was a bulk replace of the text. Do we even really need RazorPages in the namespace at all?

**Comment by guardrex** [comment]
I defer to them on both suggestions. I just thought that it sounded a bit off to have "Sample" in the middle. I've been in the habit of having it on the end for new samples (e.g., ChangeTokensSample, LoggerMessageSample, ResponseCompressionSample, etc.).

**Comment by isaac2004** [comment]
@guardrex I agree. My thought is people will know what the sample is since it is accessed from the Razor Page doc. My 2 cents

**Comment by Rick-Anderson** [comment]
@isaac2004  this looks good to me. Is it ready to merge?

**Comment by isaac2004** [comment]
@Rick-Anderson if you have no issue with @guardrex comments you can merge this pull. Otherwise, I would to rename the namespace in the samples again

**Comment by guardrex** [comment]
I still think naming like "RazorPagesSampleMovie" is very strange ... very strange indeed! lol :smile:

**Comment by Rick-Anderson** [comment]
@isaac2004  would you mind changing back to `RazorPagesMovie` ?

**Comment by isaac2004** [comment]
No sweat, I will do that tomorrow and tag you

**Comment by isaac2004** [comment]
@Rick-Anderson @guardrex  take a look now

**Comment by Rick-Anderson** [comment]
@isaac2004  looks good, Thanks!

**Pull request merged**
