### PR TITLE
Add docs on updated SPA templates preview

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
In the next week or so, we'll be publishing a preview of the next version of the SPA templates (for Angular, React, and React+Redux). This documentation covers both how to get the preview release, and how to use it.

We should not actually merge this PR until the preview is released, though I can (hopefully) do that at the right time if this PR is approved. There is still a package name to be updated in these docs when the final preview package name is confirmed, which also I will do before merging.

Once the final SPA templates updates are released as RTM (hopefully in January) I'll submit a further update that removes all the statements about this being "preview", so this can become the final permanent SPA templates docs.

As a separate matter, we should remove a large portion of the existing "client-side development" content, because it's outdated - not just because of the changes this PR documents, but just because the industry as a whole has moved on.

**Internal Review Pages:**
- [Index Page](https://review.docs.microsoft.com/aspnet/core/spa/?branch=pr-en-us-4919)
- [Angular](https://review.docs.microsoft.com/aspnet/core/spa/angular?branch=pr-en-us-4919)
- [React](https://review.docs.microsoft.com/aspnet/core/spa/react?branch=pr-en-us-4919)
- [React w/ Redux](https://review.docs.microsoft.com/aspnet/core/spa/react-with-redux?branch=pr-en-us-4919)

### CODE REVIEW

**Comment by scottaddie** [comment]
@Rick-Anderson @danroth27 Please see Steve's comment above regarding removal of client-side dev docs. Thoughts?

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS  can you give us a list of topics to remove? Once you give us the list I'll remove them.

**Comment by Rick-Anderson** [comment]
@scottaddie  can you post a list of  client-side dev docs to remove then I'll get Steve to approve the list. We should be focusing on ASP.NET Core which is primarily server technology.

**Comment by SteveSandersonMS** [comment]
Thanks @scottaddie for the copyediting! I've also pushed a few further commits which updates this to the final state for the 2.0.0-preview1-final release.

**Is this OK to be merged and published now?** Since the 2.0.0-preview1-final template has now been published [1] it would be good to have the docs easily available.

> Also, should these new docs be located under a new "Single-Page Apps" node in the TOC? Or should they live under the existing "Client-Side Development" node?

Not sure whether you were asking me or someone else, but I don't mind either way. Totally happy with you choosing how the content should be grouped.

> can you give us a list of topics to remove? Once you give us the list I'll remove them.

Yes, if you could file a bug and assign it to me, I'll figure out a set of recommendations.

[1] Technically still [waiting for NuGet.org to index it](https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates/2.0.0-preview1-final), but that should complete automatically in the next 30 minutes or so.

**Comment by scottaddie** [comment]
@SteveSandersonMS I've assigned https://github.com/aspnet/Docs/issues/4944 to you. Once we determine the appropriate TOC location, I'll update the associated files. Then this PR is ready to merge and publish.

@Rick-Anderson Do you have a preference for TOC location of these docs?

**Comment by Rick-Anderson** [comment]
@scottaddie  No pref on TOC
@scottaddie  can you change each of the notes from
This documentation is not about the existing Angular project template. This documentation is about the next version of the Angular template which ships in early 2018.

To something like

This documentation is not about the released Angular project template. This documentation is about the preview version of the Angular template. We hope to ship the released version in early 2018.

**Comment by SteveSandersonMS** [comment]
Thanks for approving. Squashed and merged.

> can you change each of the notes...

Done

**Comment by SteveSandersonMS** [comment]
@Rick-Anderson @scottaddie Can we get this to go live today? I'm guessing that happens when `master` is merged to `live`, but will leave that for one of you to do (or tell me I can do) in case you have any extra processes around this. Thanks!

**Comment by scottaddie** [comment]
@SteveSandersonMS Thank you for making the note changes. This will go live once https://github.com/aspnet/Docs/pull/4949 is merged, which should happen today. @Rick-Anderson Are you able to confirm that this PR will merge today?

**Comment by Rick-Anderson** [comment]
@scottaddie  done

**Pull request merged**
