### PR TITLE
damienbod/aspnetcore-data-ef-mvc-intro-samples-cu-final-update-csproj

### PR DESCRIPTION
**Pull request by damienbod**

### CODE REVIEW

**Comment by damienbod** [comment]
@Rick-Anderson 
The docs need to be updated for this as well as the
C:\git\Docs\aspnetcore\data\ef-mvc\intro\samples\cu sample.

**Comment by damienbod** [comment]
cu sample here: https://github.com/aspnet/Docs/pull/2765

**Comment by Rick-Anderson** [comment]
@tdykstra  owns this.

**Comment by Rick-Anderson** [comment]
@damienbod Thanks for the contribution – we appreciate the help with the _project.json_ to ._csproj_ conversion effort.  However, this is a tutorial and sample that @tdykstra is working on.  Please see the [Contributing]( https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md) guide – The contributing guide suggests creating an issue before you make changes to prevent duplicate work (and to make sure it's something we're interested in so will have a good chance of getting accepted).

The code is not standalone, any code changes need to be consistent with the tutorial (MD file).

Keep in mind we don’t  change author attribution unless there’s a substantial amount of new or changed content. Merged PR automatically get added to the smaller Contributors list. 

Thanks again for your significant contributions.

**Comment by damienbod** [comment]
@Rick-Anderson @tdykstra  ok, thanks for the info. Should I delete the pull requests, maybe he can use them, everything works, md is also updated as well as the cu sample.

**Comment by Rick-Anderson** [comment]
@damienbod  leave it for now and @tdykstra  can close them . Sorry for the confusion, I should have mentioned this to you when you started.

**Pull request closed without merging**
