### PR TITLE
Added note RE: @RenderSection scripts

### PR DESCRIPTION
**Pull request by DaveVoyles**
Found the solution from this StackOverflow post: http://stackoverflow.com/questions/10971149/the-following-sections-have-been-defined-but-have-not-been-rendered-for-the-layo

It means that you have defined a section in your master Layout.cshtml, but you have not included anything for that section in your View.

The final div within _Layout.cshtml should look like this:

    <div class="container body-content">
        @RenderBody()
        @RenderSection("scripts", required: false)
        <hr />
        <footer>
            <p>&copy; 2016 - MvcMovie</p>
        </footer>
    </div>

Another user reported the same issue within the comments on this post. I replicated the issue myself, and this resolved it.

### CODE REVIEW

**Comment by danroth27** [comment]
@Rick-Anderson Please review

**Comment by Rick-Anderson** [comment]
The template generated code works fine. The SO post was for MVC 4 Beta, more than two generations old.

**Comment by DaveVoyles** [comment]
I understand that it was for an older version of for the MVC 4 beta, but it
still applied for this project.

I couldn't get it to work without it. Added that one line of code, and it
all works.

Dave Voyles | DaveVoyles.com | @DaveVoyles
<http://www.twitter.com/DaveVoyles>

**Comment by Rick-Anderson** [comment]
@DaveVoyles  have you tried with the RTM bits? I can't repro the problem and we have several thousand customers reporting success without it. Try scaffolding a new model and then test create.

**Comment by DaveVoyles** [comment]
I've got 5.2.4 installed (I think that's the latest version)? but difficult
to tell.

It may have to do with the fact that I have VS Community 2015 installed,
but only Update 2. Was hoping it would push update 3 to me, but for some
reason I am never prompted, and it doesn't appear in updates.

I may have to just uninstall and re-install fresh from this link, as I may
have hit a bug:
https://blogs.msdn.microsoft.com/visualstudio/2016/06/27/visual-studio-2015-update-3-and-net-core-1-0-available-now/

Dave Voyles | DaveVoyles.com | @DaveVoyles
<http://www.twitter.com/DaveVoyles>

**Comment by Rick-Anderson** [comment]
RTM won't install without VS13.3, so I don't think you have the latest. 
capture

**Comment by DaveVoyles** [comment]
OK, thank you for clarifying! I'll dive into that

Dave Voyles | DaveVoyles.com | @DaveVoyles
<http://www.twitter.com/DaveVoyles>

**Pull request closed without merging**
