### PR TITLE
Remove wwwroot from .gitignore

### PR DESCRIPTION
**Pull request by guardrex**
@Rick-Anderson Can we? ... *Pleeeeeeeeze!* :smile:

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@scottaddie  if you're convinced this is best - merge.

**Comment by guardrex** [comment]
Case of :beer: for @scottaddie if he merges this ... *MAKE that TWO CASES!* :grinning:

**Comment by guardrex** [comment]
graff

*"The time saved would be worth the risk."* - Graff Vynda-K ([Paul Seed](http://www.imdb.com/name/nm0781477/))
Dr Who: [The Ribos Operation](http://www.bbc.co.uk/doctorwho/classic/episodeguide/ribosoperation/detail.shtml), ©1978 [BBC](https://www.bbc.co.uk/)

**Comment by guardrex** [comment]
:tada: 🎈 :cake: :sunny: 👍 😍 

Thanks ... this will make things go a bit more smoothly.

**Comment by Rick-Anderson** [comment]
@guardrex @scottaddie  what's the best way to keep wwwroot out when you don't need it? I've been copying the root ignore file to the sample folder and adding wwwroot.

**Comment by scottaddie** [comment]
I recommend creating a solution-specific *.gitignore* file. That should override what's defined in the root file.

**Comment by guardrex** [comment]
In response to ...

> With this being said, I think it's reasonable to exclude folders like wwwroot/lib, since folders/files are copied here during bower install. Any opposition to me adding this to .gitignore?

Samples without the *lib* folder contents will break tho when Bower isn't in use and the system is offline (i.e., fallbacks kick in looking for *lib* folder contents). Bower should replace files anyway, right? If so, it wouldn't matter if they're there. I think the worst UE tho is someone downloads a sample and it :boom: for any reason.

Another thing ... I "get it" on templates ... Bower, Gulp, flavor-of-the-month technologies get put into some of the larger, it-does-everything-OOB templates. What we have over here tho are *samples*. I think samples should be as least opinionated as possible. I think they should be xplat, cross-IDE, and not depend on JS task runners or specialized packages/technologies whenever possible.

**Pull request merged**
