### PR TITLE
Update package-lock.json

### LINKED ISSUE #10853: Update "lodash": ">=4.17.11"

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #10853

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
SHould I change that to ` "lodash": "^4.17.11",` ?

**Comment by scottaddie** [comment]
Looking into this right now, but it will likely require a new version of the top-level package `html-webpack-plugin`. We don't want to update the *package-lock.json* file. It's regenerated each time `npm install` runs.

**Comment by Rick-Anderson** [comment]
Let's delete it so we can get rid of the warning.

**Comment by scottaddie** [comment]
@Rick-Anderson See my linked PR. That fixes the issue.

**Pull request merged**
