### PR TITLE
Configure Apache as a reverse proxy

### LINKED ISSUE #1348: Fundamentals/servers/overview.html "Servers"
Replace mention of HTTP Platform Handler with ASP.NET Core Module.
General cleanup.

### LINKED ISSUE #1630: Sample/instructions for configuring Apache as a proxy server - under publishing/index.rst
Should go somewhere under https://docs.asp.net/en/latest/publishing/index.html
Originally requested at https://github.com/aspnet/Docs/issues/1348

### PR DESCRIPTION
**Pull request by spboyer**
Fixes #1348 
Fixes #1630 

@danroth27

### CODE REVIEW

**Comment by danroth27** [comment]
@blowdart @shirhatti Can you guys take a look?

**Comment by danroth27** [comment]
@shanselman @glennc

**Comment by blowdart** [comment]
Not me, I don't understand any of how apache works.

**Comment by spboyer** [comment]
Add notes on securing access to proxy: http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#access

**Comment by shirhatti** [comment]
What's the intended scope of this document? Have we intentionally omitted any guidance around SSL termination on the proxy?

**Comment by spboyer** [comment]
@shirhatti it was intended to show the reverse proxy of Apache, I will be adding the ssl termination as well to the doc.

**Pull request closed without merging**
