### PR TITLE
mvc mig round2

### PR DESCRIPTION
**Pull request by Rick-Anderson**
@rachelappel @shirhatti 30K deletions must be a mistake. I have all the changes backed up, should I try another PR?

This is https://github.com/aspnet/Docs/pull/615 updated with dan.roth feedback/changes plus updated for RC1.

### CODE REVIEW

**Comment by shirhatti** [comment]
@Rick-Anderson It looks like you've deleted the one of the [sample projects](https://github.com/aspnet/Docs/tree/master/mvc/migration/migratingfrommvc5/samples/Mvc5Project) included with the docs. Did you mean to delete that?

**Comment by Rick-Anderson** [comment]
@shirhatti Ya, the MVC5 starter is not needed. The completed project is all that's needed.

**Comment by Rick-Anderson** [comment]
@shirhatti as mentioned This is #615 updated with dan.roth feedback/changes plus updated for RC1. 
Can we get this merged today?

**Comment by shirhatti** [comment]
Travis failed because of a build error 
````
build/aspnet/Docs/mvc/migration/migratingauthmembership.rst:110: WARNING: undefined label: migrate-controllers-views-static (if the link has no caption the label must precede a section header)
````

Can you resolve that?

**Comment by Rick-Anderson** [comment]
@shirhatti I'm guessing I deleted a label in mvc/migration/migratingfrommvc5.rst needed in build/aspnet/Docs/mvc/migration/migratingauthmembership.rst

I didn't change migratingauthmembership.rst. Given they are both in the MVC branch a label shouldn't be required.

I need to study the build details, I looked at the build output and missed that.
I'll investigate and fix the problem.

**Comment by shirhatti** [comment]
Merged in a8c831da0b6a05b471cb09c9fdf6530ae2c8a8f5

**Pull request closed without merging**
