### PR TITLE
Adding note about added "textInput" binding.

### PR DESCRIPTION
**Pull request by brentconey**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS can you review?

**Comment by brentconey** [comment]
I also thought about maybe replacing the section with the text binding to just use textInput instead of mentioning it in the notes? I've found myself using textInput instead of value for most of my binding to text boxes. 

Thoughts?

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS, @fiyazbinhasan please review.

**Comment by SteveSandersonMS** [comment]
This change looks fine to me :)

**Comment by fiyazbinhasan** [comment]
information in the note looks good! I don't think you should change the whole section though @brentconey @Rick-Anderson :)

**Comment by Rick-Anderson** [comment]
@brentconey  Thanks!

**Pull request merged**
