### PR TITLE
improve doc and sample for https redirect

### LINKED ISSUE #7811: Primary example should address most common use case http to https port 443
The example provided does not address the most common use case of having a redirect from http to https (on port 443). Feel free to provide a second example for edge cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#require-https)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by barry-schneider**
Fixes #7811

Updated the sample to reflect the most common option settings. Provided other options in the comment in the code.

Update MD file to make more readable.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@barry-schneider  It looks like you created the PR from a stale branch. Have you reviewed the **Files changed** tab?

**Comment by guardrex** [comment]
@Rick-Anderson In addition, we need to discuss this further with @shirhatti (and possibly `@Tratcher`) before we proceed. We'll need a more nuanced approach to clarifying the scenarios.

https://github.com/aspnet/Docs/pull/7812#issuecomment-407937125

**Comment by barry-schneider** [comment]
I am going to pull the latest into my repo and redo the pull request with my changes.

**Comment by guardrex** [comment]
@barry-schneider I recommend holding off until we get feedback from the engineers. @shirhatti can comment on the situation with Azure Apps ... for example ... 'Does the Azure switch remove the need to set the port manually?' He said earlier that he prefers we tell devs to use the Azure switch and not set the port explicitly.

Also, the content you're cutting here is accurate in the local environment. We need to find out how the engineers want to advise devs in the non-local environment. I suspect we need to split out the instruction by the hosting environment, which would mean placing the current content into a subsection, not cutting it from the topic.

@Tratcher, would u like to advise us as well?

**Comment by Tratcher** [comment]
Yes the Azure switch would be preferred over using AddHttpsRedirection, that redirect takes place before the request reaches the application. However you still want AddHttpsRedirection for Development and other non-Azure environments.

Setting HttpsPort to 443 is fine. Consider only setting it in Production. The VS dev tools set it for you in Development. If you've already set the Azure switch then this will have no effect.

307 is the default redirect status code and I don't expect users will need to change it. You can remove it from the examples.

I agree removing IServerAddressesFeature is overkill.

**Comment by barry-schneider** [comment]
My main object was to have the documentation reflect the most common use case, which is having http be redirected to https using port 443. As a developer, I followed the current documentation and was not working on my Azure web site. I suggested we start with that example. Then provide additional examples for redirect response and setting the ports, that specifies the order of priority.

What is the .net core convention for the order of priority of applying configuration setting? 

- code
- appsetting
- environment variable
- other

Does [TryGetHttpsPort](https://github.com/aspnet/BasicMiddleware/blob/d8a90ce88fb8c5d26a6604963e1dbc50c12c0dae/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionMiddleware.cs#L106) function in [HttpsRedirectionMiddleware]
(https://github.com/aspnet/BasicMiddleware/blob/master/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionMiddleware.cs) confirm to the convention?

**Comment by guardrex** [comment]
That's fine. The content will (probably) end up in a couple of subsections ...

* Azure Apps (no port set; use the portal)
* Local and IIS (set the port to 443 in the Production environment only; leave the existing content for IServerAddressesFeature)

**Pull request closed without merging**
