### PR TITLE
Fixed AspNetCore URL

### PR DESCRIPTION
**Pull request by kuashe**
Since ASP became AspNetCore , the url of the repo changed.

From : 

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Abstractions/IActionResult.cs

To 

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/IActionResult.cs

### CODE REVIEW

**Comment by danroth27** [comment]
We should just remove these GitHub links and point to the [API ref docs](https://docs.asp.net/projects/api) instead. Could you update your PR accordingly?

**Comment by kuashe** [comment]
Now that i'm thinking about it , you really have a point here. I'm going to change that for sure.

**Comment by kuashe** [comment]
It's done , but note this won't work when the doc will be refactored :disappointed:.

The API doc namespace is not "AspNetCore" it's still using old namespace.

Also many things seems to be not in the right place, ActionResult for example is in "AspNet.MVC"  in API but in real it's in "AspNet.MVC.Core".

**Comment by danroth27** [comment]
This change is correct for RC1, which is fine for now. We will be doing a pass on all of the docs to update them based on the new naming for RC2. 

The current API docs were generated for RC1, so they don't reflect the new names yet. We will generate new API ref docs for RC2, which will have the new names.

The API refs are organized by namespace, not package ID. ActionResult lives in the Microsoft.AspNet.Mvc namespace in RC1 (see https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNet.Mvc.Core/ActionResult.cs#L6).

**Comment by danroth27** [comment]
:shipit:

**Comment by danroth27** [comment]
Thanks for this change! 630c17a028c6a22a5dacd85926856d49c8667c4c

**Pull request closed without merging**
