### PR TITLE
Added initial data protection documentation.

### PR DESCRIPTION
**Pull request by blowdart**
Initial commit for  #84

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@blowdart__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by blowdart** [comment]
Silly CLA bot :)

**Comment by danroth27** [comment]
8956be165366ceb9830476afb0b173fe5d4c5309

**Comment by danroth27** [comment]
Fixes https://github.com/aspnet/Docs/issues/91

**Pull request closed without merging**
