### PR TITLE
1385001 redirect publish to azure

### PR DESCRIPTION
**Pull request by john-par**
Requested updates from [PR10667](https://github.com/aspnet/Docs/pull/10667).

### CODE REVIEW

**Comment by john-par** [comment]
@tdykstra this PR is ready for your review. Please let me know what you'd like changed.

These are your requested updates from [PR10667](https://github.com/aspnet/Docs/pull/10667).

**Comment by Rick-Anderson** [comment]
@john-par 	I think you can batch apply all @tdykstra 	suggestions and you don't need to do any work. Then I'll S&M.

**Comment by john-par** [comment]
Thanks for the suggestion @Rick-Anderson. I batch applied the suggestions. There was [one suggestion](https://github.com/aspnet/Docs/pull/10723#discussion_r252845533) that wasn't a suggested code change. Is there a way to get that incorporated using GitHub?

**Comment by Rick-Anderson** [comment]
@john-par 	I took care of it via edit in browser on the files tab.

**Comment by john-par** [comment]
Closing and reopening PR to try and get past the cryptic error.

**Comment by john-par** [comment]
Closing and reopening PR to try and get past the cryptic error.

**Comment by john-par** [comment]
Thanks @Rick-Anderson and @tdykstra. All of your feedback has been incorporated. This PR is ready to be merged.

**Pull request merged**
