### PR TITLE
Ng15 component fixes

### PR DESCRIPTION
**Pull request by aftab10662**
Dear @danroth27 as discussed yesterday i am submitting the PR for Angular 1.5 Component topic ,   request you to review the content and share feedback.
Thanks!

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@aftab10662  we'll look at this in about a week when @spboyer joins us.

**Comment by Rick-Anderson** [comment]
@spboyer please review

**Comment by Rick-Anderson** [comment]
@aftab10662  can I close this now? It looks like it contains a bunch of incorrect commits.

**Comment by aftab10662** [comment]
@Rick-Anderson yes rick, looks like i did something wrong and spoiled this PR.
I will submit fresh new PR.
Please close , sorry for inconvenience.

**Comment by Rick-Anderson** [comment]
NP, I  seem to do that about once a month myself.

**Pull request closed without merging**
