### PR TITLE
Create toc node for landing page

### LINKED ISSUE #10316: Make "ASP.NET Documentation" node at top of TOC
The new node should link to the ASP.NET Core documentation landing landing page.

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #10316 

[ASP.NET internal staging link](https://review.docs.microsoft.com/en-us/aspnet/overview?branch=pr-en-us-10317)

[ASP.NET Core internal staging link](https://review.docs.microsoft.com/en-us/aspnet/core/index?branch=pr-en-us-10317&view=aspnetcore-2.2)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Top link throws you out of our docs. That won't work

image

**Comment by Rick-Anderson** [comment]
Can you make **Introduction to ASP.NET Core** the top link?

**Comment by tdykstra** [comment]
This is the standard MVC structure that we missed earlier.  Top node goes to landing page.  See https://review.docs.microsoft.com/en-us/help/contribute/contribute-toc-mvc-how-to?branch=master

**Comment by tdykstra** [comment]
the node name "[area] documentation" for the landing page node is also standard

**Comment by Rick-Anderson** [comment]
I don't like it. The bread crums do the same thing. Can you merge to live?

**Pull request merged**
