### PR TITLE
update intro page

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Addresses one issue on #2057
@danroth27  please review. This is the cleaned up version of the [Intro](https://review.docs.microsoft.com/en-us/aspnet/core/intro) page. Once you approve this, I'll delete the intro page.

**Comment by danroth27** [comment]
I don't think we want to duplicate the content.

**Comment by Rick-Anderson** [comment]
Per triage I won't dup content, I'll delete the other version. I'll update the PR and verify TOC works.

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Docs/pull/2058 is a better approach

**Pull request closed without merging**
