### PR TITLE
App secrets update

### LINKED ISSUE #6523: Missing a step
Nothing was working until I found an example that added a required line to the startup constructor:
```
if (env.IsDevelopment())
{
    builder.AddUserSecrets();
}
```
You might want to add that vital piece of info. :/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #6523

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-1.0&branch=pr-en-us-6528)

Tiny nits in the app secrets update: "or later" and a couple of comma splices.

What I wrote for another version of this was more explicit. I'm concerned that the current version doesn't tell devs exactly why/how `AddUserSecrets` is added, and it doesn't say that if `CreateDefaultBuilder` isn't used that they'll still need to do it manually.

Starting with ...

> \- Add the user secrets configuration source to the `Startup` constructor:

> Add the user secrets configuration source with a call to \[AddUserSecrets](/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets) in the `Startup` constructor:
>
> \[!code-csharp\[](app-secrets/samples/1.1/UserSecrets/Startup.cs?name=snippet_StartupConstructor&highlight=5-8)]
> ::: moniker-end
> ::: moniker range=">= aspnetcore-2.0"
> When a project calls \[CreateDefaultBuilder](/dotnet/api/microsoft.aspnetcore.webhost.createdefaultbuilder) to initialize a new instance of the host with preconfigured defaults, \[AddUserSecrets](/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets) is called when the \[EnvironmentName](/dotnet/api/microsoft.aspnetcore.hosting.ihostingenvironment.environmentname) is \[Development](/dotnet/api/microsoft.aspnetcore.hosting.environmentname.development):
>
> \[!code-csharp\[](app-secrets/samples/2.1/UserSecrets/Program.cs?name=snippet_CreateWebHostBuilder&highlight=2)]
>
> When `CreateDefaultBuilder` isn't called during host construction, add the user secrets configuration source with a call to \[AddUserSecrets](/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets) in the `Startup` constructor:
>
> \[!code-csharp\[](app-secrets/samples/1.1/UserSecrets/Startup.cs?name=snippet_StartupConstructor&highlight=5-8)]
> ::: moniker-end

Snippet the call to `CreateDefaultBuilder` to show it (line 2 is highlighted) ...

```csharp
#region snippet_CreateWebHostBuilder
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>();
#endregion
```

... and the sample naming issue remains ("1.1" and "2.1" instead of "1.x" and "2.x").

If anything here looks good, I can mod this branch to make additional updates. Otherwise, nevermind. Just spit-ball'in here.

### CODE REVIEW

**Comment by scottaddie** [comment]
@guardrex I also really like what you proposed above for clarifying how `AddUserSecrets` is called. Go ahead with those changes too in this PR.

**Comment by guardrex** [comment]
@scottaddie WRT paragraph on Line 189: Difficult to say everything in one sentence without it getting too long, so I went with two sentences: A general topic sentence that explains the "2.0 or later" and that the user secrets config source is added automatically. There's a second sentence that fleshes it out with the specifics on `CreateDefaultBuilder`, `AddUserSecrets`, etc.

**Comment by guardrex** [comment]
One other point/question ...

```
::: moniker range="<= aspnetcore-1.1"
-[View or download sample code](https://github.com/aspnet/Docs/tree/master/aspnetcore/security/app-secrets/samples/1.1) ([how to download](xref:tutorials/index#how-to-download-a-sample))
+[View or download sample code](https://github.com/aspnet/Docs/tree/master/aspnetcore/security/app-secrets/samples/1.x) ([how to download](xref:tutorials/index#how-to-download-a-sample))
 ::: moniker-end
 ::: moniker range=">= aspnetcore-2.0"
-[View or download sample code](https://github.com/aspnet/Docs/tree/master/aspnetcore/security/app-secrets/samples/2.1) ([how to download](xref:tutorials/index#how-to-download-a-sample))
+[View or download sample code](https://github.com/aspnet/Docs/tree/master/aspnetcore/security/app-secrets/samples/2.x) ([how to download](xref:tutorials/index#how-to-download-a-sample))
 ::: moniker-end
```

If we do that on all of our topics, it's going to get more-and-more difficult to maintain as time rolls on. How about we just reference the samples folder. We'll never need to mess with these links again in this area of the topics ...

```
[View or download sample code](https://github.com/aspnet/Docs/tree/master/aspnetcore/security/app-secrets/samples) ([how to download](xref:tutorials/index#how-to-download-a-sample))
```

**Comment by scottaddie** [comment]
@guardrex I'm okay with pointing to the samples folder.

**Comment by guardrex** [comment]
:smile: ... I **DO** like this ...

```
<xref:fundamentals/configuration/index>
```
... as I'll mention in my upcoming dissertation on the subject. (🤦‍♂️ oh dear!)

**Comment by guardrex** [comment]
Ok ... ready for :eyes:.

**Comment by scottaddie** [comment]
One nit ☝️, and then this looks good to me.

**Pull request merged**
