### PR TITLE
Extended "Binding source parameter inference"part

### LINKED ISSUE #10248: Add expected behavior of Binding source parameter inference for collection
[This table](https://github.com/aspnet/Mvc/issues/8536#issuecomment-426695828) should be included:

| Parameter type   |      Binding source| 
|----------|:-------------:|
| Simple type |  Query |
| Complex type |    Body   |
| Simple collection | Body |
| Complex collection | Body |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.1#binding-source-parameter-inference)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by Abarbz**
Fixes #10248
Update suggested by @pranavkm: 
Added clarification regarding expected behavior for collection in binding source parameter inference.
Following [a bug](https://github.com/aspnet/Mvc/issues/8536) in version 2.1 of Asp.net Core, it was clear that the expected behavior of the inference system for collections was not explicit enough in the existing documentation.
The expected behavior is clearly stated [here](https://github.com/aspnet/Mvc/issues/8536#issuecomment-426695828).

### CODE REVIEW

**Comment by pranavkm** [comment]
@Abarbz wouldn't it be better to pose this as a remark that says in 2.1, collection types are treated as `FromQuery`. This bug is fixed in later versions? We really don't make a distinction between complex and collection types in 2.2 and later

**Comment by Abarbz** [comment]
Oh, if version specific stuff are allowed inside the documentation I could also do that.
Still, I find that clarifying the case of collection of simple type is a real plus.

**Comment by Abarbz** [comment]
(actually I found the small summary by mkArtakMSFT [here](https://github.com/aspnet/Mvc/issues/8536#issuecomment-426695828) very clear, but did not find a proper place to insert it)

**Comment by Rick-Anderson** [comment]
@pranavkm 	do you want the following table added?

| Parameter type   |      Binding source| 
|----------|:-------------:|
| Simple type |  Query |
| Complex type |    Body   |
| Simple collection | Body |
| Complex collection | Body |

> in 2.1, collection types are treated as FromQuery. 

We can add that around 2.1 monikers

@scottaddie 	can you take this over. Back out "as well as collections (of complex or simple type)" par @pranavkm

**Comment by scottaddie** [comment]
We appreciate your PR, @Abarbz. It really sparked some great conversation. Closing this PR in favor of https://github.com/aspnet/Docs/pull/10348.

**Pull request closed without merging**
