### PR TITLE
Update metapackage-app.md

### PR DESCRIPTION
**Pull request by watashiSHUN**
relative links are broken

### CODE REVIEW

**Comment by scottaddie** [comment]
Thank you for your contribution, but I've verified that the links work properly as is. They link to the document found at https://docs.microsoft.com/dotnet/core/packages. We use relative paths to other docs as a best practice.

**Comment by watashiSHUN** [comment]
may I ask how did you verify? if I click on the doc I got redirected to https://github.com/aspnet/Docs/blob/master/dotnet/core/packages which is a 404

**Comment by scottaddie** [comment]
Go to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1 in your browser, and click the links from there. Does that work for you?

**Comment by watashiSHUN** [comment]
I see

**Pull request closed without merging**
