### PR TITLE
Add sub-app config and common error entry

### PR DESCRIPTION
**Pull request by GuardRex**
Fixes https://github.com/aspnet/Docs/issues/1764

### CODE REVIEW

**Comment by GuardRex** [comment]
@Rick-Anderson Want to try the green button for the green dino? (or I can squash these commits if you like)

**Comment by Rick-Anderson** [comment]
@shirhatti please approve

**Comment by shirhatti** [comment]
I get what we are trying to do here is ensure people don't attempt to register an already registered handler. However, I don't necessarily agree that I advocate setting up a * mapping at the root application level. It might give the impression it is not possible to have an ASP.NET app with an ASP.NET Core sub-app.

I'd recommend one of the following:
* Don't actually provide a web.config and make this advice more high-level; OR
* Explicitly call running an ASP.NET app with ASP.NET Core sub-app is a supported scenario

/cc @jhkimnew

**Comment by GuardRex** [comment]
> It might give the impression it is not possible to have an ASP.NET app with an ASP.NET Core sub-app.

You can tell how much in :heart: I am with .NET Core! lol ..... i.e., Why in the world would anyone want to put a beautiful .NET Core app inside of a crummy .NET Framework app ... oh, the horror! lol :smile:

I agree with removing the `web.config` files here. They aren't really necessary to make the point. I'll have a revision committed in a few minutes.

**Comment by shirhatti** [comment]
> Why in the world would anyone want to put a beautiful .NET Core app inside of a crummy .NET Framework app ... oh, the horror! lol :smile:

I can definitely see people migrating large apps starting to piece-wise move functionality over to .NET Core as a sub-app within their existing application.

**Comment by GuardRex** [comment]
Got it. Thx @shirhatti :beers:

**Comment by shirhatti** [comment]
Looks good to me!

**Comment by Rick-Anderson** [comment]
@GuardRex  no need the squash, the green button does that. Thanks!

**Pull request merged**
