### PR TITLE
Order of IHostingStartup Configure calls

### LINKED ISSUE #6951: What will be the order of middleware execution?
Middleware in configure method is executed in sequence. If I implement a middleware using IHostingStartup abstraction and use it in my project, when will this get executed? What if I want to include this only in development and after exception handler is executed? 

Here is the configure in your example:
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseMvc();
        }
```

And here is the configure implementation of the StartupDiagnosticsHostingStartup 
```
public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
        {
            return app =>
            {
                // Use a terminal middleware that branches on a request for
                // /services. The middleware uses a factory to obtain the services
                // registered for the app and outputs them in a webpage.
                app.Map("/services", builder => builder.Run(async ctx =>
                {
                    // Make sure this only runs in the Development environment.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a759e56-4ba4-c464-ae74-e2705df72811
* Version Independent ID: 7a4ee224-ce61-ac3f-6b60-88c7a5a24f2c
* Content: [Enhance an app from an external assembly in ASP.NET Core with IHostingStartup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/platform-specific-configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/platform-specific-configuration.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #6951 

This doesn't address *Split dynamic loading section into separate document* #6896 and the new exclusion bits provided by https://github.com/aspnet/Hosting/pull/1243. I'll hit those on #6896.

### CODE REVIEW

**Comment by guardrex** [comment]
ping @davidfowl

**Comment by davidfowl** [comment]
Wait, I just read this. Nobody should *ever* call Configure in an IHostingStartup. It overrides the normal one. Those do not compose.

**Comment by guardrex** [comment]
@davidfowl Easy to do, but now *I'm confused!* lol

This is about the order of `Configure` executions ... not calling them.

The first blurb is saying that the `IHostingStartup.Configure` is called before `Startup.Configure` in user code (in the app where the hosting startup assembly is added).

The second blurb is saying that when multiple hosting startup assembles are present, their `Configure` methods are executed in the order that the assemblies are listed in `DOTNET_ADDITIONAL_DEPS`.

**Comment by guardrex** [comment]
Would it be better as ...

> `IHostingStartup.Configure` is called by the runtime before `Startup.Configure` in user code ...

**Comment by davidfowl** [comment]
Ahhh my bad. yes that's fine. I was thinking about WebHostBuilder.Configure.

**Pull request merged**
