### PR TITLE
Update overview.rst

### PR DESCRIPTION
**Pull request by joeaudette**
Hi Rick,

I fixed the parts I could, but I could not find the alternatives for certificates and custom crypto, some of the crypto stuff is available as methods but maybe need different params

### CODE REVIEW

**Comment by danroth27** [comment]
@blowdart Please review

**Comment by blowdart** [comment]
I had this half done, but great, saves me doing it :)

**Comment by danroth27** [comment]
@blowdart OK to merge?

**Comment by blowdart** [comment]
Sure

**Comment by joeaudette** [comment]
@blowdart it still needs some more fixes, I wasn't sure about the sections for x509cert and the parts about crypto algos, so I left those alone

**Comment by rachelappel** [comment]
@blowdart  if it's ok to merge, toss a squirrel in here so I can do so. Unless you are asking to hold off for a bit, @joeaudette?

**Comment by Rick-Anderson** [comment]
:shipit:

**Comment by Rick-Anderson** [comment]
@rachelappel  please merge - and open an issue to address @joeaudette  concerns

**Comment by rachelappel** [comment]
Thank you Joe! Appreciate the contribution! 00b3d01074bdd9ec24ad5efaa1f2b59765e51606

**Pull request closed without merging**
