### PR TITLE
correct small typo in logging.md  for How filtering rules are applied" table

### PR DESCRIPTION
**Pull request by itsashish-patel**
as per configuration JSON example in  "Create filter rules in configuration" section, "How filtering rules are applied" table rule # 6 should  at Debug log level instead of Warring log level.

When creating a new PR, please do the following and delete this template text:

* Reference the issue number if there is one:

  Fixes #Issue_Number

  > The "Fixes #nnn" syntax in the PR description causes
  > GitHub to automatically close the issue when this PR is merged.

* Suggest reviewers if you know who should review the PR, using the GitHub **Reviewers** UI.

### CODE REVIEW

**Comment by scottaddie** [comment]
@ardalis Please review.

**Comment by pakrym** [comment]
@scottaddie LGTM

**Comment by scottaddie** [comment]
@itsashish-patel Thank you for your contribution. It will go live within the next 24 hours.

**Comment by ardalis** [comment]
Agreed

**Comment by itsashish-patel** [comment]
Thank every one to considering my small contribution.

**Pull request merged**
