### PR TITLE
update configuration samples and docs

### PR DESCRIPTION
**Pull request by anurse**
* update samples to RTM
* update refs to API docs
* convert some inline code to external samples so they are always buildable.

**NOTE**: I put a NuGet.config in the root so that all the samples would be able to access the 1.0.0 packages... Not sure if that's the ideal way to do this right now, but I'm leaving it in for comment.

/cc @Rick-Anderson @rachelappel @danroth27

### CODE REVIEW

**Comment by anurse** [comment]
@danroth27 have the API docs been updated for RTM? I'm getting missing references in build again...

**Comment by cesarbs** [comment]
LGTM, but I don't think we should ship the `Nuget.config` file. When we ship everything will be up on `nuget.org`.

**Comment by Rick-Anderson** [comment]
@anurse I don't think Dan's updated them yet.

**Comment by anurse** [comment]
@cesarbs I agree in general but a) this NuGet.config file isn't "shipped", it's just part of the repo for building and b) removing `aspnet1` from the feed list would be something that should happen on the day we ship (so we can continue testing and building the existing samples)

**Comment by Rick-Anderson** [comment]
@anurse this builds cleanly now. Can you rebase?

**Comment by danroth27** [comment]
I'll take care of rebasing this one: https://github.com/aspnet/Docs/pull/1531

**Comment by danroth27** [comment]
0566cbd11c8dbce7472ea3517f4445894be9e1fb

**Pull request closed without merging**
