### PR TITLE
Damienbod/safelist security

### PR DESCRIPTION
**Pull request by damienbod**
@tdykstra 

Greetings Damien

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@damienbod  it looks like you created your branch in the wrong place, it's picking up alot of commits it shouldn't.

cc @scottaddie

**Comment by damienbod** [comment]
@Rick-Anderson I created it from nearly the latest master, but @tdykstra asked me to merge this into his branch first, which was creted further back. I can change this as you want.

Greetings Damien

**Comment by scottaddie** [comment]
This looks a lot better now.

**Comment by tdykstra** [comment]
Yes, thanks Scott for your help.

**Comment by Rick-Anderson** [comment]
@damienbod  sorry, it was Tom, not you.

**Comment by scottaddie** [comment]
Yay, teamwork! 🎉 Thank you for your help, @damienbod!

**Pull request merged**
