### PR TITLE
Angular Documentation

### PR DESCRIPTION
**Pull request by fiyazbinhasan**
[Review URL ](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/angular2?branch=pr-en-us-3261)(for internal folks)
Document using ASP.NET Core with Angular 2 issue - [#2461](https://github.com/aspnet/Docs/issues/2461#issuecomment-292568739)

Done except the Docker Deployment Part! VS 2017 is giving me weird errors after adding docker support from context menu.

@Rick-Anderson @tdykstra @@FabianGosebrink @damienbod

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan - can you complete the CLA?

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson signed 👍

**Comment by Rick-Anderson** [comment]
I think we can skip Docker and make that another article.

**Comment by fiyazbinhasan** [comment]
yes I agree. do you have any plans to split the article in smaller parts?

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  I won't be able to work on this until July 2017. Maybe @FabianGosebrink or @damienbod  could work on it. cc @tdykstra  @danroth27

**Comment by Rick-Anderson** [comment]
@scottaddie  can you review and do a full edit pass?  Make the changes directly and not ask @fiyazbinhasan  to make them.

**Comment by Rick-Anderson** [comment]
@scottaddie When you're finished, as [@]jawache for a review.

**Comment by Rick-Anderson** [comment]
replaced by https://github.com/aspnet/Docs/pull/3495

**Pull request closed without merging**
