### PR TITLE
Update publish-to-azure-webapp-using-vs.md

### PR DESCRIPTION
**Pull request by garfbradaz**
The document is little vague with regards publishing a site that uses appsettings.json. This lead me to raise a SO query which you guys kindly answered:

https://stackoverflow.com/questions/44768865/asp-net-core-latest-appsettings-json-connectionstring-not-overriding-on-azur/44771419#44771419

I think the document needs to be clearer on how this option effects the use of appsettings.json. I had to manually remove the Config Settings on Azure post-publish (which I wasnt aware of).

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@garfbradaz  that's insecure and we don't want to promote an insecure approach. I don't know who answered that SO question but they should explain what's going on and remove the tacit approval for using a file to store sensitive information.

**Comment by garfbradaz** [comment]
Thaanks @RickAndMSFT !

Is there a ASP.NET Core Version of this for appsettings.json?

https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/best-practices-for-deploying-passwords-and-other-sensitive-data-to-aspnet-and-azure

**Comment by scottaddie** [comment]
@garfbradaz One option that comes to mind for storing sensitive data in production environments is Azure Key Vault. I recommend reading the [Azure Key Vault configuration provider](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration) doc. An alternative to this for local development is the Secret Manager tool. Read the [Safe storage of app secrets during development](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets) doc for more info on that option.

**Comment by garfbradaz** [comment]
@scottaddie Beautiful  - thanks again - awesome response times.

**Pull request closed without merging**
