### PR TITLE
Add a section about storing data protection keys using the EF Core provider

### PR DESCRIPTION
**Pull request by natemcmaster**
Adding documentation about a new feature coming in 2.2. https://github.com/aspnet/DataProtection/pull/323

cref https://github.com/aspnet/Home/issues/2505

@rick-anderson edit below:
[Internal review url](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.2&branch=pr-en-us-8328#entity-framework-core)

~Do not merge until preview-2 ships.~

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@natemcmaster  I've got .NET Core SDK 2.2 preview installed and set my project to use 2.2, but I can't find `IDataProtectionKeyContext` and it's not listed at https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.entityframeworkcore.idataprotectionkeycontext

**Comment by Rick-Anderson** [comment]
@natemcmaster  looks like https://github.com/aspnet/DataProtection/pull/323/ needs to merge first.

**Comment by Rick-Anderson** [comment]
@natemcmaster should we hold off merging until 2.2 Preview-2?

**Comment by natemcmaster** [comment]
Yes. Do you have a staging branch for preview 2 work?

**Comment by natemcmaster** [comment]
Also, why is the indentation wrong in the code snippet?

image

https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.2&branch=pr-en-us-8328#entity-framework-core

**Comment by Rick-Anderson** [comment]
@natemcmaster no, we don't have a staging branch. We rarely start docs before a preview is released. I'll label this WIP so it can't be merged. Once preview-2 comes out, I'll replace your inline code with imported snippets.

**Comment by natemcmaster** [comment]
Why https://github.com/aspnet/DataProtection/pull/323 was merged and the feature will be in 2.2 Preview 2.

**Comment by Rick-Anderson** [comment]
@natemcmaster  I'll fix the formatting.

```
dotnet --version
2.2.100-preview2-009404
```

But `IDataProtectionKeyContext` is unresolved.  

`using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;` 
Error	CS0234	The type or namespace name 'EntityFrameworkCore' does not exist in the namespace 'Microsoft.AspNetCore.DataProtection' (are you missing an assembly reference?)

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>aspnet-RPkeys-B4E1BF1C-6B91-45B1-870A-BE8861EAD4FD</UserSecretsId>
    <AspNetCoreHostingModel>inprocess</AspNetCoreHostingModel>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App"/>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0-preview2-35157" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0-preview2-35157" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

**Comment by natemcmaster** [comment]
> The type or namespace name 'EntityFrameworkCore' does not exist in the namespace

You need to add package reference to Microsoft.AspNetCore.DataProtection.EntityFrameworkCore. This feature, like the Redis and Azure providers, are not part of the AspNetCore.App metapackage.

**Comment by natemcmaster** [comment]
LGTM

**Comment by Rick-Anderson** [comment]
@natemcmaster 	 please review `@blowdart`'s comments and my commit.

**Comment by natemcmaster** [comment]
LGTM. :shipit:

**Pull request merged**
