### PR TITLE
Fix for pkcs12 certificate export

### PR DESCRIPTION
**Pull request by Roman-Blinkov**
Hi,
This pull request fixes pkcs12 certificate export command for macos and linux.

Regards, Roman

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@Roman-Blinkov  thanks. Will it also work on Windows?

**Comment by Roman-Blinkov** [comment]
I tried both light and full x64 windows packages from https://slproweb.com/products/Win32OpenSSL.html
- https://slproweb.com/download/Win64OpenSSL_Light-1_1_0f.exe (3 Mb)
- https://slproweb.com/download/Win64OpenSSL-1_1_0f.exe (33 Mb)


Does not work on Windows with default install. Works on macOS 10.12.5
```

PS C:\Users\Roman Blinkov> C:\OpenSSL-Win64\bin\openssl req -new -x509 -newkey rsa:2048 -keyout localhost.key -out localhost.cer -days 365 -subj /CN=localhost
Can't open C:\Program Files\Common Files\SSL/openssl.cnf for reading, No such file or directory
11008:error:02001003:system library:fopen:No such process:crypto\bio\bss_file.c:74:fopen('C:\Program Files\Common Files\SSL/openssl.cnf','r')
11008:error:2006D080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:81:
Generating a 2048 bit RSA private key
.........................+++
...........................................+++
writing new private key to 'localhost.key'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
unable to find 'distinguished_name' in config
problems making Certificate Request
11008:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto\conf\conf_lib.c:272:
```
I checked [docs](https://wiki.openssl.org/index.php/Manual:Req(1)) and I don't see way to generate cert without openssl config file (I can be wrong here)

**Comment by Rick-Anderson** [comment]
@Roman-Blinkov  Thanks - does the original work on Windows? If so, we can provide instructions for windows and then for macOS/linux

**Comment by Roman-Blinkov** [comment]
Got you. Yes :) 
Windows instruction few lines before this instruction

**Comment by Rick-Anderson** [comment]
@Roman-Blinkov  Thanks!

**Comment by Roman-Blinkov** [comment]
I updated formatting for Window
Now Windows manual visible in change request

**Pull request merged**
