### PR TITLE
Logging -> RC2

### PR DESCRIPTION
**Pull request by ardalis**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
There is a bug in the CLI that doesn't show console colors, could you publish your app and run the .exe it produces to get the images since those should have the colors?

**Comment by danroth27** [comment]
@kichalla Please review these RC2 updates

**Comment by kichalla** [comment]
> @kichalla can you help me get TraceSource configured to work in an MVC app? It requires full net framework but "Microsoft.NETCore.App" does not support .NET 4.6, so how do I configure it to work? I'm updating the Logging docs to RC2. Thanks!

I do not have much knowledge regarding TraceSource logger. Probably @cesarbs, @moozzyk, @davidfowl  can help here.

I tried following sample where all of this is on .net core

```c#
var testSwitch = new SourceSwitch("displayName", "defaultSwitchValue");
testSwitch.Level = SourceLevels.Warning;

var loggerfactory = new LoggerFactory()
    .AddTraceSource(testSwitch, new TextWriterTraceListener(writer: Console.Out));

var logger = loggerfactory.CreateLogger<Program>();

logger.LogInformation("info message");
logger.LogCritical("critical message");
logger.LogDebug("verbose message");
logger.LogError("error message");
logger.LogWarning("warning message");
```

**Comment by ardalis** [comment]
@kichalla Thanks for the sample; unfortunately I don't see a Core version of TextWriterTraceListener. What package/namespace would you get that from?

**Comment by ardalis** [comment]
The samples and article work as they stand now. The bulk of the article covers Core features; the TraceSource and EventLogTraceListener are NET461 only, but this is noted. Should we :shipit: now so the RC2 changes are live and people aren't seeing RC1 code, and then make any updates later as separate issues? @danroth27

**Comment by kichalla** [comment]
Just FYI...whenever you have this sort of question you can check with http://packagesearch.azurewebsites.net/ which gives you the info about the package where an API could exist in .NET core. I find it very helpful.

regarding your question, its in `System.Diagnostics.TextWriterTraceListener`

**Comment by ardalis** [comment]
@kichalla Thanks, I'm aware of the package search, and Visual Studio even suggests pulling in System.Diagnostics.TextWriterTraceListener. It was just concerning me that the latest version I see is "4.0.0-beta-23516", not an "rc2-final" version, which I'm not sure we want to be using here. 

Testing with it, it seems to work fine. Will there be an RTM version of that package when ASP.NET Core RTMs?

**Comment by ardalis** [comment]
@kichalla Updated to use TextWriterTraceListener. ship?

**Comment by kichalla** [comment]
:shipit:

**Pull request merged**
