### PR TITLE
DI -> Dependency Injection

### PR DESCRIPTION
**Pull request by pavanagrawal123**
I'm not sure if using an abbreviation in a first time, tutorial doc is a good idea...

### CODE REVIEW

**Comment by guardrex** [comment]
It's defined on Line 178 ...

> In ASP.NET Core, services such as the DB context must be registered with the \[dependency injection (DI)](xref:fundamentals/dependency-injection) container. The container provides the service to controllers.

**Comment by pavanagrawal123** [comment]
@guardrex Whoops missed that! Also noticed this doc still uses [ApiController]... AFAIK, we're supposed to use [Controller] now?

**Comment by guardrex** [comment]
I don't see anything in Scott's text that raises concern in general ... https://docs.microsoft.com/aspnet/core/web-api/#annotation-with-apicontroller-attribute

**Comment by pavanagrawal123** [comment]
Ahh I was using an older version of ASP.Net, sorry for the noob questions, and thank you for the prompt responses @guardrex  :)

**Pull request closed without merging**
