### PR TITLE
Surface latest Redis dist caching package

### LINKED ISSUE #11118: RedisCache links should go to the newer Caching.StackExchangeRedis package
The page still links to the older RedisCache package that is effectively deprecated.
There's the newer Microsoft.Extensions.Caching.StackExchangeRedis package that uses the 2.x versions of stack exchange redis and is also built for 2.2 (and I'm guessing later 3.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#distributed-redis-cache)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #11118

### CODE REVIEW

**Comment by marekr** [comment]
Technically there's still references to AddDistributedRedisCache on the page. In the _new_ package, it became AddStackExchangeRedisCache

**Comment by marekr** [comment]
@guardrex There's still references to AddDistributedRedisCache on the page. In the _new_ package, it became AddStackExchangeRedisCache

**Comment by guardrex** [comment]
I was hoping that more wouldn't have been required given that the sample is 2.1. Let me see if I can patch it up a bit more. I'm not going to upgrade the sample app at this time.

**Comment by marekr** [comment]
I didn't know there was a sample app. I was just talking about the small "Distributed Redis Cache" section on the page with some links and 4 lines of code.

**Comment by guardrex** [comment]
I see it. I'm tracking down the API ref for it now. Should have it shortly.

**Pull request merged**
