### PR TITLE
Fixed ambiguous wording #759

### PR DESCRIPTION
**Pull request by cmatskas**
As discussed on this issue, I fixed one sentence that didn't read as well. Every little helps :)

### CODE REVIEW

**Comment by cmatskas** [comment]
The last few builds today seem to be failing even though the files that raise the warnings (which subsequently are dealt as errors) are in the repo. Access rights maybe?

**Comment by ardalis** [comment]
Looks good to me - the build issues are unrelated. :shipit: when you can @rachelappel

**Comment by cmatskas** [comment]
Hi @rachelappel! Let's do this ;) thanks team

**Comment by rachelappel** [comment]
It built for me, so merged, Thank you! e275c47db0310f56e80e7e0cfeb11dc70d1e491f

**Pull request closed without merging**
