### PR TITLE
Updated Migrating From MVC 5 article to use Gulp rather than Grunt

### PR DESCRIPTION
**Pull request by ardalis**

### CODE REVIEW

**Comment by danroth27** [comment]
@madskristensen @DamianEdwards Could you guys please look these changes over for correctness?

**Comment by madskristensen** [comment]
Why use `gulp-clean` instead of `rimraf` or `del`? The project templates are using `rimraf` because it's super light weight. `del` is the recommended approach though

**Comment by ardalis** [comment]
I chose gulp-clean because it was analogous to grunt-clean (which was the code I had previously), and it seemed like it would be the most discoverable option (who's going to know to search for "rimraf"?). If del is the recommended approach (recommended where?) I'm happy to use that, though, thanks.

**Comment by danroth27** [comment]
Let's keep our docs consistent with the templates. If we decide to move the templates to use del then we can update the docs at that point.

**Comment by ardalis** [comment]
Sounds good - will update to use rimraf now.

**Comment by danroth27** [comment]
:shipit:

**Comment by madskristensen** [comment]
Beautiful. Thanks

**Pull request merged**
